### Filtragem de Questões do ENEM com base na API

Na API a ordem segue a do caderno Azul.

In [2]:
import pandas as pd
import json
from pprint import pprint
import os
import re
import numpy as np
import matplotlib.pyplot as plt

#### Modularização da Limpeza

In [3]:
def load_json(caminho):
    with open(caminho, 'r', encoding='utf-8') as f:
        return json.load(f)

def filtrar_questoes(data, disciplina="linguagens"):
    questions = data.get("questions", data)

    filtradas = [
        item for item in questions
        if (
            item.get("files", []) == [] and
            item.get("language") is None and
            item.get("discipline", "").lower() == disciplina.lower()
        )
    ]

    return filtradas

def limpar_texto(texto): #limpeza de texto
    if pd.isna(texto):
        return ""

    texto = str(texto)
    texto = re.sub(r"\*\*", "", texto)
    texto = texto.replace("\xa0", " ")
    texto = texto.replace("/", " ")
    texto = texto.replace("\n", " ")
    texto = re.sub(r"\s+", " ", texto)

    return texto.strip()

def extrair_alternativas(lista):
    resultado = {"A": None, "B": None, "C": None, "D": None, "E": None}

    if isinstance(lista, list):
        for alt in lista:
            letra = alt.get("letter")
            texto = limpar_texto(alt.get("text"))
            if letra in resultado:
                resultado[letra] = texto

    return pd.Series(resultado)

def transformar_dataframe(filtered):
    df = pd.json_normalize(filtered)

    # limpar textos
    df["context"] = df["context"].apply(limpar_texto)
    df["alternativesIntroduction"] = df["alternativesIntroduction"].apply(limpar_texto)

    # montar pergunta
    df["question"] = (
        df["context"].fillna("") + " " +
        df["alternativesIntroduction"].fillna("")
    ).apply(limpar_texto)

    # extrair alternativas
    alts = df["alternatives"].apply(extrair_alternativas)
    df = pd.concat([df, alts], axis=1)

    # dataset final
    df_final = df[[
        "index", "question",
        "A", "B", "C", "D", "E",
        "correctAlternative"
    ]].rename(columns={
        "index": "id",
        "correctAlternative": "correct"
    })

    df_final = df_final.reset_index(drop=True)

    return df_final

def montar_opcoes(row):
    return [
        f"A. {row['A']}",
        f"B. {row['B']}",
        f"C. {row['C']}",
        f"D. {row['D']}",
        f"E. {row['E']}",
    ]

def gerar_dataset_json(df_final):
    df_final["options"] = df_final.apply(montar_opcoes, axis=1)

    dataset = []

    for _, row in df_final.iterrows():
        dataset.append({
            "id": int(row["id"]),
            "question": row["question"],
            "options": row["options"]
        })

    return dataset

def pipeline_enem(caminho):
    data = load_json(caminho)
    filtradas = filtrar_questoes(data)
    df_final = transformar_dataframe(filtradas)
    dataset = gerar_dataset_json(df_final)

    return df_final, dataset

def exportar_json(dataset, caminho_saida):
    with open(caminho_saida, "w", encoding="utf-8") as f:
        json.dump(dataset, f, indent=2, ensure_ascii=False)

In [ ]:
def carregar_itens(caminho):
    return pd.read_csv(caminho, sep=';', encoding='latin1')

def filtrar_itens(itens, area='LC', cor='AZUL', co_prova=None):
    df = itens.copy()
    if area:
        df = df[df["SG_AREA"] == area]
    if cor:
        df = df[df["TX_COR"] == cor]
    if co_prova:
        df = df[df["CO_PROVA"] == co_prova]
    return df

def cruzar_itens_com_dataset(itens_df, df_final):
    return itens_df[itens_df["CO_POSICAO"].isin(df_final["id"])]

#### ENEM 2022 - LC

In [12]:
caminho_2022 = r"D:\ODG\outputs n8n\API Response\questões_enem_2022_lc.json"
df2022, dataset_json2022 = pipeline_enem(caminho_2022)
print(df2022.shape)
df2022

(31, 9)

,id,question,A,B,C,D,E,correct,options
0,6,"Urgência emocional Se tudo é para ontem, se a ...","Impessoalização ao longo do texto, como em: “s...","Construção de uma atmosfera de urgência, em pa...",Repetição de uma determinada estrutura sintáti...,"Ênfase no emprego da hipérbole, como em: “uma ...","Emprego de metáforas, como em: “a vida engata ...",E,"[A. Impessoalização ao longo do texto, como em..."
1,8,É ruivo? Tem olhos azuis? É homem ou mulher? U...,Contribuir para a formação cidadã dos jogadores.,Refutar modelos estereotipados de beleza e ele...,Estimular a competitividade entre potenciais c...,Exemplificar estratégias de arrecadação financ...,Desenvolver conhecimentos lúdicos específicos ...,A,[A. Contribuir para a formação cidadã dos joga...
2,10,"Ciente de que, no campo da criação, as inovaçõ...",Sucesso dos artistas.,Valorização dos suportes.,Proteção da produção estética.,Modo de distribuição de obras.,Compartilhamento das obras artísticas.,C,"[A. Sucesso dos artistas., B. Valorização dos ..."
3,11,"Ora, sempre que surge uma nova técnica, ela qu...",Dificuldade na apropriação da nova linguagem.,Valorização da utilização da nova tecnologia.,Recorrência das mudanças tecnológicas.,Suplantação imediata dos conhecimentos prévios.,Rapidez no aprendizado do manuseio das novas i...,A,[A. Dificuldade na apropriação da nova linguag...
4,12,Papos — Me disseram… — Disseram-me. — Hein? — ...,Falta de compreensão causada pelo choque entre...,Contexto de comunicação em que a conversa se dá.,Grau de polidez distinto entre os interlocutores.,Diferença de escolaridade entre os falantes.,Nível social dos participantes da situação.,B,[A. Falta de compreensão causada pelo choque e...
5,13,"São vários os fatores, internos e externos, qu...",Apontam o desenvolvimento econômico com soluçã...,Questionam a crença de que o acesso à informaç...,Afirmam que o uso comercial da rede é a causa ...,Refutam o vinculo entre níveis de escolaridade...,Condicionam a expansão da rede à elaboração de...,B,[A. Apontam o desenvolvimento econômico com so...
6,14,"TEXTO I A língua não é uma nomenclatura, que s...",Expediente próprio do sistema linguístico que ...,Ato inventivo de nomear novas realidades que s...,Mecanismo de apropriação de formas linguística...,Processo de incorporação de preconceitos que s...,Recurso de expressão marcado pela objetividade...,D,[A. Expediente próprio do sistema linguístico ...
7,16,"Ela era linda. Gostava de dançar, fazia teatro...","Narrar, por meio de imagem e poesia, cenas da ...","Descrever, por meio das memórias de Petra, a s...","Sintetizar, por meio das principais cenas do f...","Lançar, por meio da história de vida do autor,...","Avaliar, por meio de análise crítica, o filme ...",E,"[A. Narrar, por meio de imagem e poesia, cenas..."
8,17,PALAVRA As gramáticas classificam as palavras ...,"Tematiza o fazer poético, como em ""Os poetas c...","Utiliza o recurso expressivo da metáfora, como...","Valoriza a gramática da língua, como em ""subst...","Estabelece comparações, como em ""As palavras t...",Apresenta informações pertinentes acerca do co...,B,"[A. Tematiza o fazer poético, como em ""Os poet..."
9,18,Morte lenta ao luso infame que inventou a calç...,Justaposição de sequências verbais e nominais.,Mudança de eventos resultante do jogo temporal.,Uso de adjetivos qualificativos na descrição d...,Encadeamento semântico pelo uso de substantivo...,Inter-relação entre orações por elementos ling...,A,[A. Justaposição de sequências verbais e nomin...
10,19,"Pisoteamento, arrastão, empurra-empurra, agres...",Problema social localizado numa região do país.,Desafio para as torcidas organizadas dos clubes.,Reflexo da precariedade da organização social ...,Inadequação de espaço nos estádios para recebe...,Consequência da insatisfação dos clubes com a ...,C,[A. Problema social localizado numa região do ...
11,20,Seis em cada dez pessoas com 15 anos ou mais n...,"Promovam a melhoria da aptidão da população, d...",Combatam o sedentarismo presente em parcela si...,"Facilitem a adoção da prática de exercícios, c...",Auxiliem na construção de mais instalações esp...,Estimulem o incentivo fiscal para a iniciativa...,C,[A. Promovam a melhoria da aptidão da populaçã...
12,21,"A escrava – Admira-me —, disse uma senhora de ...",Revelar a imposição de crenças religiosas a pe...,Apontar a hipocrisia do discurso conservador n...,Sugerir práticas de violência física e moral e...,Relacionar o declínio da produção agrícola e c...,Ironizar o comportamento dos proprietários de ...,B,[A. Revelar a imposição de crenças religiosas ...
13,22,TEXTO I Projeto Mural Eletrônico desenvolvido ...,Garantem a igualdade entre as pessoas.,Foram criados por uma pesquisadora surda.,Tiveram origem em um curso de pós-graduação.,Estão circunscritos ao espaço institucional da...,Têm como objetivo a disseminação do conhecimento.,E,"[A. Garantem a igualdade entre as pessoas., B...."
14,23,"Mas seu olhar verde, inconfundível, impression...",Caracterização da personagem como mestiça.,Construção do enredo de conquistas da família.,Relação conflituosa das mulheres e seus maridos.,Nostalgia do desejo de viver como os antepassa...,Marca de antigos sofrimentos no fluxo de consc...,E,[A. Caracterização da personagem como mestiça....
15,25,A conquista da medalha de prata por Rayssa Lea...,Conciliação do jornalismo com a prática do skate.,Inserção das mulheres na modalidade skate street.,Desconstrução da noção do skate como modalidad...,Vanguarda de ser a atleta mais jovem a subir n...,Conquista de medalha nos Jogos Olímpicos de Tó...,C,[A. Conciliação do jornalismo com a prática do...
16,26,Assentamento Assentamento Zanza daqui Zanza pr...,“Zanza pra acolá”.,"“Fim de feira, periferia afora”.",“A cidade não mora mais em mim”.,"""Onde só vento se semeava outrora”.","“Ó Manuel, Miguilim”.",C,"[A. “Zanza pra acolá”., B. “Fim de feira, peri..."
17,28,As línguas silenciadas do Brasil Para aprender...,Denuncia o processo de perseguição histórica s...,Conjuga o ato de resistência étnica à preserva...,Associa a preservação linguística ao campo da ...,Estimula o retorno de povos indígenas a suas t...,Aumenta o número de línguas indígenas faladas ...,B,[A. Denuncia o processo de perseguição históri...
18,29,"Esaú e Jacó Bárbara entrou, enquanto o pai peg...",Modo de vestir dos moradores do morro carioca.,Senso prático em relação às oportunidades de r...,Mistério que cerca as clientes de práticas de ...,Misto de singeleza e astúcia dos gestos da per...,Interesse do narrador pelas figuras femininas ...,D,[A. Modo de vestir dos moradores do morro cari...
19,30,"A senhora manifestava-se por atos, por gestos,...","Capitalista, marcado pela distribuição funcion...","Liberal, buscando a igualdade entre pessoas es...","Científico, considerando o ser humano como um ...","Religioso, fundamentado na fé e na aceitação d...","Afetivo, manifesto na determinação de acolher ...",C,"[A. Capitalista, marcado pela distribuição fun..."
20,31,Era o êxodo da seca de 1898. Uma ressurreição ...,Desenho cru da realidade dramática dos retiran...,Indefinição dos espaços para efeito de general...,Análise psicológica da reação dos personagens ...,Engajamento político do narrador ante as desig...,Contemplação lírica da paisagem transformada e...,A,[A. Desenho cru da realidade dramática dos ret...
21,33,"Notas Soluços, lágrimas, casa armada, veludo p...",Enumeração de objetos e fatos,Predominância de linguagem objetiva,Ocorrência de período longo no trecho,Combinação de verbos no presente e no pretérito,Presença de léxico do campo semântico de funerais,A,"[A. Enumeração de objetos e fatos, B. Predomin..."
22,34,"Criado há cerca de 20 anos na Califórnia, o mo...",Competitividade entre seus praticantes.,Atividade com padrões técnicos definidos.,Modalidade com regras predeterminadas.,Criatividade para adaptações a novos espaços.,Necessidade de espaços definidos para a sua re...,D,"[A. Competitividade entre seus praticantes., B..."
23,35,"Ser cronista Sei que não sou, mas tenho medita...",Relação distanciada entre os interlocutores.,Articulação de vários núcleos narrativos.,Brevidade no tratamento da temática,Descrição minuciosa dos personagens,Público leitor exclusivo.,C,[A. Relação distanciada entre os interlocutore...
24,36,Projeto na Câmara de BH quer a vacinação gratu...,Fiscalizar as ações de saúde e saneamento da c...,Defender os serviços gratuitos de atendimento ...,Conscientizar a população sobre grave problema...,Propor campanhas para a ampliação de acesso ao...,Responsabilizar os agentes públicos pela demor...,C,[A. Fiscalizar as ações de saúde e saneamento ...
25,37,“Vida perfeita” em redes sociais pode afetar a...,Representações estereotipadas e superficiais d...,Ressignificações contemporâneas do conceito de...,Estilos de vida inacessíveis para a sociedade ...,Atitudes contraditórias de influenciadores dig...,Padrões idealizados e nocivos de beleza física.,A,[A. Representações estereotipadas e superficia...
26,40,"Firmo, o vaqueiro No dia seguinte, à hora em q...",Plasticidade da imagem do rebanho reunido.,Sugestão da firmeza do sertanejo ao arrear o c...,Situação de pobreza encontrada nos sertões bra...,Afetividade demonstrada ao noticiar a morte do...,Preocupação do vaqueiro em demostrar sua viril...,D,[A. Plasticidade da imagem do rebanho reunido....
27,41,O bebê de tarlatana rosa – \[…\] Na terça desl...,Consagração da alegria do povo.,Atração e asco perante atitudes libertinas.,Espanto com a quantidade de foliões nas ruas.,Intenção de confraternizar com desconhecidos.,Reconhecimento da festa como manifestação cult...,B,"[A. Consagração da alegria do povo., B. Atraçã..."
28,42,10 de maio Fui na delegacia e falei com o tene...,Lição de vida comunicada pelo tenente.,Predisposição materna para se emocionar.,Atividade política marcante da comunidade.,Resposta irônica ante o discurso da autoridade.,Necessidade de revelar seus anseios mais íntimos.,D,"[A. Lição de vida comunicada pelo tenente., B...."
29,43,Vanda vinha do interior de Minas Gerais e de d...,Citação a referências literárias tradicionais.,Alusão à inocência das crianças da época.,Estratégia de questionar a bondade humana.,Descrição detalhada das pessoas do interior.,Representação anedótica de atos de violência.,E,[A. Citação a referências literárias tradicion...
30,45,O Recife fervilhava no começo da década de 199...,Utilização de aparelhos musicais eletrônicos e...,Ocupação de espaços da natureza local para a p...,"Substituição de antigas práticas musicais, com...",Recuperação de composições tradicionais folcló...,Integração de referenciais culturais de difere...,E,[A. Utilização de aparelhos musicais eletrônic...

In [5]:
dataset_json2022

[{'id': 6,
  'question': 'Urgência emocional Se tudo é para ontem, se a vida engata uma primeira e sai em disparada, se não há mais tempo para paradas estratégicas, caímos fatalmente no vício de querer que os amores sejam igualmente resolvidos num átimo de segundo. Temos pressa para ouvir “eu te amo”. Não vemos a hora de que fiquem estabelecidas as regras de convívio: somos namorados, ficantes, casados, amantes? Urgência emocional. Uma cilada. Associamos diversas palavras ao AMOR: paixão, romance, sexo, adrenalina, palpitação. Esquecemos, no entanto, da palavra que viabiliza esse sentimento: “paciência”. Amor sem paciência não vinga. Amor não pode ser mastigado e engolido com emergência, com fome desesperada. É uma refeição que pode durar uma vida. MEDEIROS, M. Disponível em: http: porumavidasimples.blogspot.com.br. Acesso em: 20 ago. 2017 (adaptado). Nesse texto de opinião, as marcas linguísticas revelam uma situação distensa e de pouca formalidade, o que se evidencia pelo(a)',
  'options': ['A. Impessoalização ao longo do texto, como em: “se não há mais tempo”.',
   'B. Construção de uma atmosfera de urgência, em palavras como: “pressa”.',
   'C. Repetição de uma determinada estrutura sintática, como em: “Se tudo é para ontem”.',
   'D. Ênfase no emprego da hipérbole, como em: “uma refeição que pode durar uma vida”.',
   'E. Emprego de metáforas, como em: “a vida engata uma primeira e sai em disparada”.']},
 {'id': 8,
  'question': 'É ruivo? Tem olhos azuis? É homem ou mulher? Usa chapéu? Quem jogou Cara a Cara na infância sabe de cor o roteiro de perguntas para adivinhar quem é o personagem misterioso do seu oponente. Agora, o jogo está prestes a ganhar uma nova versão. A designer polonesa Zuzia Kozerska-Girard está desenvolvendo uma variação do _Guess Who?_ (nome do Cara a Cara em inglês), em que as personalidades do tabuleiro são, na verdade, mulheres notáveis da história e da atualidade, como a artista Frida Kahlo, a ativista Malala Yousafzai, a astronauta Valentina Tereshkova e a aviadora Amelia Earhart. O _Who’s She?_ (“Quem é ela?”, em português) traz, no total, 28 mulheres que representam diversas profissões, nacionalidades e idades. A ideia é que, em vez de perguntar sobre a aparência das personagens, as questões sejam direcionadas aos feitos delas: ganhou algum Nobel, fez alguma descoberta? Para cada personagem há um cartão com fatos divertidos e interessantes sobre sua vida. Uma campanha entrou no ar com o objetivo de arrecadar dinheiro para desenvolver o _Who’s She?_. A meta inicial era reunir 17 mil dólares. Oito dias antes de a campanha acabar, o projeto já angariou quase 350 mil dólares. A chegada do jogo à casa do comprador varia de acordo com a quantia doada — quanto mais você doou, mais rápido vai poder jogar. Disponível em: www.super.abril.com.br. Acesso em: 4 dez. 2018 (adaptado). Ao divulgar a adaptação do jogo para questões relativas a ações e habilidades de mulheres notáveis, o texto busca',
  'options': ['A. Contribuir para a formação cidadã dos jogadores.',
   'B. Refutar modelos estereotipados de beleza e elegância.',
   'C. Estimular a competitividade entre potenciais compradores.',
   'D. Exemplificar estratégias de arrecadação financeira pela internet.',
   'E. Desenvolver conhecimentos lúdicos específicos dos tempos atuais.']},
 {'id': 10,
  'question': 'Ciente de que, no campo da criação, as inovações tecnológicas abrem amplo leque de possibilidades – ao permitir, e mesmo estimular, que o artista explore a fundo, em seu processo criativo, questões como a aleatoriedade, o acaso, a não linearidade e a hipermídia –, Leo Cunha comenta que, no que tange ao campo da divulgação, as alternativas são ainda mais evidentes: “Afinal, é imensa a capacidade de reprodução, multiplicação e compartilhamento das obras artísticas culturais. Ao mesmo tempo, ganham dimensão os dilemas envolvidos com a questão da autoria, dos direitos autorais, da reprodução e intervenção não autorizadas, entre outras questões”. Já segundo a professora Yacy-Ara Froner, o uso de ferramentas tecnológicas não pode ser visto como um fim em si mesmo. Isso porque computadores, samplers, programas de imersão, internet e intranet, vídeo, televisão, rádio, GPD etc. são apenas suportes com os quais os artistas exercem sua imaginação. SILVA JR., M. G. Movidas pela dúvida. Minas faz Ciências, n. 52, dez-fev. 2013 (adaptado). Segundo os autores citados no texto, a expansão de possibilidades no campo das manifestações artísticas promovida pela internet pode pôr em risco o(a)',
  'options': ['A. Sucesso dos artistas.',
   'B. Valorização dos suportes.',
   'C. Proteção da produção estética.',
   'D. Modo de distribuição de obras.',
   'E. Compartilhamento das obras artísticas.']},
 {'id': 11,
  'question': 'Ora, sempre que surge uma nova técnica, ela quer demonstrar que revogará as regras e coerções que presidiram o nascimento de todas as outras invenções do passado. Ela se pretende orgulhosa e única. Como se a nova técnica carreasse com ela, automaticamente, para seus novos usuários, uma propensão natural a fazer economia de qualquer aprendizagem. Como se ela se preparasse para varrer tudo que a precedeu, ao mesmo tempo transformando em analfabetos todos os que ousassem repeli-la. Fui testemunha dessa mudança ao longo de toda a minha vida. Ao passo que, na realidade, é o contrário que acontece. Cada nova técnica exige uma longa iniciação numa nova linguagem, ainda mais longa na medida em que nosso espírito é formatado pela utilização das linguagens que precederam o nascimento da recém-chegada. ECO, U.; CARRIÈRE, J.-C. Não contem com o fim do livro. Rio de Janeiro: Record, 2010 (adaptado). O texto revela que, quando a sociedade promove o desenvolvimento de uma nova técnica, o que mais impacta seus usuários é a',
  'options': ['A. Dificuldade na apropriação da nova linguagem.',
   'B. Valorização da utilização da nova tecnologia.',
   'C. Recorrência das mudanças tecnológicas.',
   'D. Suplantação imediata dos conhecimentos prévios.',
   'E. Rapidez no aprendizado do manuseio das novas invenções.']},
 {'id': 12,
  'question': 'Papos — Me disseram… — Disseram-me. — Hein? — O correto é “disseram-me”. Não “me disseram”. — Eu falo como quero. E te digo mais… Ou é “digo-te”? — O quê? — Digo-te que você… — O “te” e o “você” não combinam. — Lhe digo? — Também não. O que você ia me dizer? — Que você está sendo grosseiro, pedante e chato. \\[…\\] — Dispenso as suas correções. Vê se esquece-me. Falo como bem entender. Mais uma correção e eu… — O quê? — O mato. — Que mato? — Mato-o. Mato-lhe. Mato você. Matar-lhe-ei-te. Ouviu bem? Pois esqueça-o e para-te. Pronome no lugar certo é elitismo! — Se você prefere falar errado… — Falo como todo mundo fala. O importante é me entenderem. Ou entenderem-me? VERISSIMO, L. F. Comédias para se ler na escola. Rio de Janeiro: Objetiva, 2001 (adaptado). Nesse texto, o uso da norma-padrão defendido por um dos personagens torna-se inadequado em razão do(a)',
  'options': ['A. Falta de compreensão causada pelo choque entre gerações.',
   'B. Contexto de comunicação em que a conversa se dá.',
   'C. Grau de polidez distinto entre os interlocutores.',
   'D. Diferença de escolaridade entre os falantes.',
   'E. Nível social dos participantes da situação.']},
 {'id': 13,
  'question': 'São vários os fatores, internos e externos, que influenciam os hábitos das pessoas no acesso à internet, assim como nas práticas culturais realizadas na rede. A utilização das tecnologias de informação e comunicação está diretamente relacionada aos aspectos como conhecimento de seu uso, acesso à linguagem letrada, nível de instrução, escolaridade, letramento digital etc. Os que detêm tais recursos (os mais escolarizados) são os que mais acessam a rede e também os que possuem maior índice de acumulatividade das práticas. A análise dos dados nos possibilita dizer que a falta de acesso à rede repete as mesmas adversidades e exclusões já verificadas na sociedade brasileira no que se refere a analfabetos, menos escolarizados, negros população indígena e desempregados. Isso significa dizer que a internet, se não produz diretamente a exclusão, certamente a reproduz, tendo em vista que os que mais a acessam são justamente os mais jovens, escolarizados, remunerados, trabalhadores qualificados, homens e brancos. SILVA, F. A. B ZIVIANE, P; GHEZZI, D. R. As tecnologias digitais e seus usos Brasília, Rio de Janeiro. Ipea. 2019 (adaptado) Ao analisarem a correlação entre os hábitos e o perfil socioeconômico dos usuários da internet no Brasil, os pesquisadores',
  'options': ['A. Apontam o desenvolvimento econômico com solução para ampliar o uso da rede.',
   'B. Questionam a crença de que o acesso à informação é igualitário e democrático.',
   'C. Afirmam que o uso comercial da rede é a causa da exclusão de minorias.',
   'D. Refutam o vinculo entre níveis de escolaridade e dificuldade de acesso.',
   'E. Condicionam a expansão da rede à elaboração de politicas inclusivas.']},
 {'id': 14,
  'question': 'TEXTO I A língua não é uma nomenclatura, que se apõe a uma realidade pré-categorizada, ela é que classifica a realidade. No léxico, percebe-se, de maneira mais imediata, o fato de que a língua condensa as experiências de um dado povo. FIORIN, J. L Língua, modernidade e tradição. Diversitas, n. 2. mar-set 2014 TEXTO II As expressões coloquiais ainda estão impregnadas de discriminação contra os negros. Basta recordar algumas delas, como passar um “dia negro”, ter um “lado negro”, ser a “ovelha negra” da família ou praticar “magia negra”. Disponível em: https: brasil.elpais.com Acesso em: 22 maio 2018. O Texto II exemplifica o que se afirma no Texto I, na medida em que defende a ideia de que as escolhas lexicais são resultantes de um',
  'options': ['A. Expediente próprio do sistema linguístico que nos apresenta diferentes possibilidades para traduzir estados de coisas.',
   'B. Ato inventivo de nomear novas realidades que surgem diante de uma comunidade de falantes de uma língua.',
   'C. Mecanismo de apropriação de formas linguísticas que estão no acervo da formação do idioma nacional.',
   'D. Processo de incorporação de preconceitos que são recorrentes na história de uma sociedade.',
   'E. Recurso de expressão marcado pela objetividade que se requer na comunicação diária.']},
 {'id': 16,
  'question': 'Ela era linda. Gostava de dançar, fazia teatro em São Paulo e sonhava ser atriz em Hollywood. Tinha 13 anos quando ganhou uma câmera de vídeo – e uma irmã. As duas se tornaram suas companheiras de experimentações. Adolescente, Elena vivia a criar filminhos e se empenhava em dirigir a pequena Petra nas cenas que inventava. Era exigente com a irmã. E acreditava no potencial da menina para satisfazer seus arroubos de diretora precoce. Por cinco anos, integrou algumas das melhores companhias paulistanas de teatro e participou de preleções para filmes e trabalhos na TV. Nunca foi chamada. No início de 1990, Elena tinha 20 anos quando se mudou para Nova York para cursar artes cênicas e batalhar uma chance no mercado americano. Deslocada, ansiosa, frustrada após alguns testes de elenco malsucedidos, decepcionada com a ausência de reconheci mento e vitimada por uma depressão que se agravava com a falta de perspectivas, Elena pôs fim à vida no segundo semestre. Petra tinha 7 anos. Vinte anos depois, é ela, a irmã caçula, que volta a Nova York para percorrer os últimos passos da irmã, vasculhar seus arquivos e transformar suas memórias em imagem e poesia. _Elena_ é um filme sobre a irmã que parte e sobre a irmã que fica. É um filme sobre a busca, a perda, a saudade, mas também sobre o encontro, o legado, a memória. Um filme sobre a Elena de Petra e sobre a Petra de Elena, sobre o que ficou de uma na outra e, essencialmente, um filme sobre a delicadeza. VANUCHI, C. Época, 19 out. 2012 (adaptado) O texto é exemplar de um gênero discursivo que cumpre a função social de',
  'options': ['A. Narrar, por meio de imagem e poesia, cenas da vida das irmãs Petra e Elena.',
   'B. Descrever, por meio das memórias de Petra, a separação de duas irmãs.',
   'C. Sintetizar, por meio das principais cenas do filme, a história de Elena.',
   'D. Lançar, por meio da história de vida do autor, um filme autobiográfico.',
   'E. Avaliar, por meio de análise crítica, o filme em referência.']},
 {'id': 17,
  'question': 'PALAVRA As gramáticas classificam as palavras em substantivo, adjetivo, verbo, advérbio, conjunção, pronome, numeral, artigo e preposição. Os poetas classificam as palavras pela alma porque gostam de brincar com elas, e para brincar com elas é preciso ter intimidade primeiro. É a alma da palavra que define, explica, ofende ou elogia, se coloca entre o significante e o significado para dizer o que quer, dar sentimento às coisas, fazer sentido. A palavra nuvem chove. A palavra triste chora. A palavra sono dorme. A palavra tempo passa. A palavra fogo queima. A palavra faca corta. A palavra carro corre. A palavra “palavra” diz. O que quer. E nunca desdiz depois. As palavras tem corpo e alma, mas são diferentes das pessoas em vários pontos. As palavras dizem o que querem, está dito, e pronto. FALCÃO, A. Pequeno dicionário de palavras ao vento. São Paulo: Salamandra, 2013 (adaptado). Esse texto, que simula um verbete para a palavra “palavra”, constitui-se como um poema porque',
  'options': ['A. Tematiza o fazer poético, como em "Os poetas classificam as palavras pela alma".',
   'B. Utiliza o recurso expressivo da metáfora, como em "As palavras têm corpo e alma".',
   'C. Valoriza a gramática da língua, como em "substantivo, adjetivo, verbo, advérbio, conjunção".',
   'D. Estabelece comparações, como em "As palavras têm corpo e alma, mas são diferentes das pessoas".',
   'E. Apresenta informações pertinentes acerca do conceito de "palavra", como em "As gramáticas classificam as palavras".']},
 {'id': 18,
  'question': 'Morte lenta ao luso infame que inventou a calçada portuguesa. Maldito D. Manuel l e sua corja de tenentes Eusébios. Quadrados de pedregulho irregular socados à mão. À mäo! É claro que ia soltar, ninguém reparou que ia soltar? Branco, preto, branco, preto, as ondas do mar de Copacabana. De que me servem as ondas do mar de Copacabana? Me deem chão liso, sem protuberâncias calcárias. Mosaico estúpido. Mania de mosaico. Joga concreto em cima e aplaina. Buraco, cratera, pedra solta, bueiro-bomba. Depois dos setenta, a vida se transforma numa interminável corrida de obstáculos. A queda é a maior ameaça para o idoso. “Idoso”, palavra odienta. Pior, só “terceira idade”. A queda separa a velhice da senilidade extrema. O tombo destrói a cadeia que liga a cabeça aos pés. Adeus, corpo. Em casa, vou de corrimão em corrimão, tateio móveis e paredes, e tomo banho sentado. Da poltrona para a janela, da janela para a cama, da cama para a poltrona, da poltrona para a janela. Olha aí, outra vez, a pedrinha traiçoeira atrás de me pegar. Um dia eu caio, hoje não. TORRES. F. Fim. São Paulo: Cia das Letras, 2013. O recurso que caracteriza a organização estrutural desse texto é o(a)',
  'options': ['A. Justaposição de sequências verbais e nominais.',
   'B. Mudança de eventos resultante do jogo temporal.',
   'C. Uso de adjetivos qualificativos na descrição do cenário.',
   'D. Encadeamento semântico pelo uso de substantivos sinônimos.',
   'E. Inter-relação entre orações por elementos linguisticos lógicos.']},
 {'id': 19,
  'question': 'Pisoteamento, arrastão, empurra-empurra, agressões, vandalismo e até furto a um torcedor que estava caído no asfalto após ter sido atropelado nas imediações do estádio do Maracanã. As cenas de selvageria tiveram como estopim a invasão de milhares de torcedores sem ingresso, que furaram o bloqueio policial e transformaram o estádio em terra de ninguém. Um reflexo não só do quadro de insegurança que assola o Rio de Janeiro, mas também de como a violência social se embrenha pelo esporte mais popular do país. Em 2017, foram registrados 104 episódios de violência no futebol brasileiro, que resultaram em 11 mortes de torcedores. Desde 1995, quando 101 torcedores ficaram feridos e um morreu durante uma batalha campal no estádio do Pacaembu, autoridades brasileiras têm focado as ações de enfrentamento à violência no futebol em grupos uniformizados, alguns proibidos de frequentar estádios. Porém, a postura meramente repressiva contra torcidas organizadas é ineficaz em uma sociedade que registra mais de 61000 homicídios por ano. “É impossível dissociar a escalada de violência no futebol do panorama de desordem pública, social, econômica e política vivida pelo país”, de acordo com um doutor em sociologia do esporte. Disponível em: https: brasil.elpais.com. Acesso em: 22 jun. 2019 (adaptado). Nesse texto, a violência no futebol está caracterizada como um(a)',
  'options': ['A. Problema social localizado numa região do país.',
   'B. Desafio para as torcidas organizadas dos clubes.',
   'C. Reflexo da precariedade da organização social no país.',
   'D. Inadequação de espaço nos estádios para receber o público.',
   'E. Consequência da insatisfação dos clubes com a organização dos jogos.']},
 {'id': 20,
  'question': 'Seis em cada dez pessoas com 15 anos ou mais não praticam esporte ou atividade física. São mais de 100 milhões de sedentários. Esses são dados do estudo _Práticas de esporte e atividade física_, da Pnad 2015, realizado pelo IBGE. A falta de tempo e de interesse são os principais motivos apontados para o sedentarismo. Paralelamente, 73,3% das pessoas de 15 anos ou mais afirmaram que o poder público deveria investir em esporte ou atividades físicas. Observou-se uma relação direta entre escolaridade e renda na realização de esportes ou atividades físicas. Enquanto 17,3% das pessoas que não tinham instrução realizavam diversas práticas corporais, esse percentual chegava a 56,7% das pessoas com superior completo. Entre as pessoas que têm práticas de esporte e atividade física regulares, o percentual de praticantes ia de 31,1%, na classe sem rendimento, a 65,2%, na classe de cinco salários mínimos ou mais. A falta de tempo foi mais declarada pela população adulta, com destaque entre as pessoas de 25 a 39 anos. Entre os adolescentes de 15 a 17 anos, o principal motivo foi não gostarem ou não quererem. Já o principal motivo para praticar esporte, declarado por 11,2 milhões pessoas, foi relaxar ou se divertir, seguido de melhorar a qualidade de vida ou o bem-estar. A falta de instalação esportiva acessível ou nas proximidades foi um motivo pouco citado, demonstrando que a não prática estaria menos associada à infraestrutura disponível. Disponível em: www.esporte.gov.br. Acesso em: 9 ago. 2017 (adaptado). Com base na pesquisa e em uma visão ampliada de saúde, para a prática regular de exercícios ter influência significativa na saúde dos brasileiros, é necessário o desenvolvimento de estratégias que',
  'options': ['A. Promovam a melhoria da aptidão da população, dedicando-se mais tempo aos esportes.',
   'B. Combatam o sedentarismo presente em parcela significativa da população no território nacional.',
   'C. Facilitem a adoção da prática de exercícios, com ações relacionadas à educação e à distribuição de renda.',
   'D. Auxiliem na construção de mais instalações esportivas e espaços adequados para a prática de atividades físicas e esportes.',
   'E. Estimulem o incentivo fiscal para a iniciativa privada destinar verbas aos programas nacionais de promoção da saúde pelo esporte.']},
 {'id': 21,

In [28]:
itens2022 = carregar_itens(r'D:\ODG\ITENS_PROVA_2022.csv')

itens_filtrados2022 = filtrar_itens(
    itens2022,
    area='LC',
    cor='AZUL',
    co_prova=1065 #1179
)

itens_final2022 = cruzar_itens_com_dataset(itens_filtrados2022, df2022)
itens_final2022 = itens_final2022.sort_values("CO_POSICAO")
itens_final2022

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
445,6,LC,60382,E,25,0,NaN,1.77346,0.68047,0.08704,AZUL,1065,NaN,0
443,8,LC,118120,A,23,0,NaN,1.53331,2.16698,0.23705,AZUL,1065,NaN,0
441,10,LC,49544,C,28,0,NaN,2.43974,1.15872,0.12513,AZUL,1065,NaN,0
440,11,LC,41810,A,29,0,NaN,0.92958,0.15096,0.01173,AZUL,1065,NaN,0
439,12,LC,42674,B,27,0,NaN,2.26956,0.51892,0.23370,AZUL,1065,NaN,0
438,13,LC,120622,B,30,0,NaN,2.55800,0.65099,0.12178,AZUL,1065,NaN,0
437,14,LC,42940,D,22,0,NaN,1.30734,-0.29879,0.00797,AZUL,1065,NaN,0
435,16,LC,141427,E,3,0,NaN,2.40522,2.28139,0.11370,AZUL,1065,NaN,0
434,17,LC,141464,B,4,0,NaN,0.94658,1.25172,0.21415,AZUL,1065,NaN,0
433,18,LC,67229,A,18,0,NaN,2.64295,1.76932,0.18786,AZUL,1065,NaN,0
432,19,LC,120124,C,9,0,NaN,2.93292,0.03337,0.17638,AZUL,1065,NaN,0
431,20,LC,45201,C,10,0,NaN,2.64453,1.04534,0.13269,AZUL,1065,NaN,0
430,21,LC,140827,B,15,0,NaN,2.05337,0.67994,0.17382,AZUL,1065,NaN,0
429,22,LC,39101,E,22,0,NaN,2.07003,1.19098,0.13567,AZUL,1065,NaN,0
428,23,LC,9716,E,16,0,NaN,0.90360,1.48142,0.05685,AZUL,1065,NaN,0
426,25,LC,141203,C,9,0,NaN,1.71461,-0.15137,0.18763,AZUL,1065,NaN,0
425,26,LC,96502,C,19,0,NaN,1.14926,-0.51604,0.00912,AZUL,1065,NaN,0
423,28,LC,120626,B,20,0,NaN,0.82491,0.89707,0.03562,AZUL,1065,NaN,0
422,29,LC,111954,D,15,0,NaN,0.78612,1.19878,0.06459,AZUL,1065,NaN,0
421,30,LC,26545,C,15,0,NaN,4.15101,1.34800,0.09280,AZUL,1065,NaN,0
420,31,LC,89149,A,16,0,NaN,1.05565,0.45772,0.03348,AZUL,1065,NaN,0
418,33,LC,86703,A,1,0,NaN,2.08922,0.96392,0.23742,AZUL,1065,NaN,0
417,34,LC,119767,D,11,0,NaN,2.11177,-0.55865,0.18565,AZUL,1065,NaN,0
416,35,LC,140898,C,1,0,NaN,1.69478,2.32558,0.16355,AZUL,1065,NaN,0
415,36,LC,111961,C,2,0,NaN,1.68380,0.70642,0.29621,AZUL,1065,NaN,0
414,37,LC,141390,A,30,0,NaN,1.54579,-0.30477,0.00839,AZUL,1065,NaN,0
411,40,LC,6864,D,16,0,NaN,0.57225,0.09790,0.01556,AZUL,1065,NaN,0
410,41,LC,10776,B,17,0,NaN,1.35922,-0.10494,0.00701,AZUL,1065,NaN,0
409,42,LC,90238,D,17,0,NaN,1.32058,0.69547,0.07827,AZUL,1065,NaN,0
408,43,LC,78112,E,17,0,NaN,0.76335,0.46065,0.00865,AZUL,1065,NaN,0
406,45,LC,141261,E,14,0,NaN,2.31367,0.48334,0.18144,AZUL,1065,NaN,0

In [26]:
#itens_azul = itens2022.query("SG_AREA == 'LC' and TX_COR == 'AZUL'")
#itens_azul
#itens_azul.query("CO_POSICAO == 6 and TX_GABARITO == 'E'")
#itens_azul.query("CO_POSICAO == 8 and TX_GABARITO == 'A'")
#itens_azul.query("CO_POSICAO == 45 and TX_GABARITO == 'E'")

#peguei duas questões e o gabarito delas pra ver qual é o co_prova que a API utiliza
# CO_PROVA é 1201

In [59]:
exportar_json(dataset_json2022, r"D:\ODG\outputs n8n\API Response\datasets\enem2022_lc.json")

In [30]:
#itens_final2022.to_csv("itens_enem_2022_azul.csv", index=False, encoding="utf-8")

In [56]:
#itens_final2022.to_excel("itens_enem_2022_azul.xlsx",index=False)

#### ENEM 2021 - LC

In [7]:
caminho_2021 = r"D:\ODG\outputs n8n\API Response\questoes_enem_2021_lc.json"
df2021, dataset_json2021 = pipeline_enem(caminho_2021)
print(df2021.shape)
dataset_json2021

(25, 9)

[{'id': 6,
  'question': 'Um asteroide de cerca de um mil metros diâmetro, viajando a 288 mil quilômetros por hora, passou a uma distância insignificante – em termos cósmicos – da Terra, pouco mais do dobre da distância que nos separa da Lua. Segundo os cálculos matemáticos, o asteroide cruzou a órbita da Terra e somente não colidiu porque ela não estava naquele ponto de interseção. Se ele tivesse sido capturado pelo campo gravitacional do nosso planeta e colidido, o impacto equivaleria a 40 bilhões de toneladas de TNT, ou o equivalente à explosão de 40 mil bombas de hidrogênio, conforme calcularam os computadores operados pelos astrônomos do programa de Exploração do Sistema Solar da Nasa; se caísse no continente, abriria uma cratera de cinco quilômetros, no mínimo, e destruiria tudo o que houvesse num raio de milhares de outros; se desabasse no oceano, provocaria maremotos que devastariam imensas regiões costeiras. Enfim, uma visão do Apocalipse. Disponível em: http: bdjur.stj.jus.br. Acesso em: 23 abr. 2010. Qual estratégia caracteriza o texto como uma notícia alarmante?',
  'options': ['A. A descrição da velocidade do asteroide.',
   'B. A recorrência de formulações hipotéticas.',
   'C. A referência à opinião dos astrônomos.',
   'D. A utilização da locução adverbial "no mínimo".',
   'E. A comparação com a distância da Lua à Terra.']},
 {'id': 7,
  'question': 'A draga A gente não sabia se aquela draga tinha nascido ali, no porto, como um pé de árvore ou uma duna. – E que fosse uma casa de peixes? Meia dúzia de loucos e bêbados moravam dentro dela, enraizados em suas ferragens. Dos viventes da draga era um o meu amigo Mário-pega-sapo. \\[…\\] Quando Mário morreu, um literato oficial, em necrológico caprichado, chamou-o de Mário-Captura-Sapo! Ai que dor! Ao literato cujo fazia-lhe nojo a forma coloquial. Queria _captura_ em vez de _pega_ para não macular (sic) a língua nacional lá dele… \\[…\\] Da velha draga Abrigo de vagabundos e de bêbados, restaram as expressões: _estar na draga_, _viver na draga_ por estar _sem dinheiro_, _viver na miséria_ Que ora ofereço ao filólogo Aurélio Buarque de Hollanda Para que as registre em seus léxicos Pois o povo já as registrou. BARROS, M. Gramática expositiva do chão: poesia quase toda. Rio de Janeiro: Civilização Brasileira, 1990 (fragmento). Ao criticar o preciosismo linguístico do literato e ao sugerir a dicionarização de expressões locais, o poeta expressa uma concepção de língua que',
  'options': ['A. Contrapõe características da escrita e da fala.',
   'B. Ironiza a comunicação fora da norma-padrão.',
   'C. Substitui regionalismos por registros formais.',
   'D. Valoriza o uso de variedades populares.',
   'E. Defende novas regras gramaticais.']},
 {'id': 8,
  'question': 'O documentário _O menino que fez um museu_, direção de Sérgio Utsch, produção independente de brasileiro e britânicos, gravado no Nordeste em 2016, mais precisamente no distrito Dom Quintino, zona rural do Crato, foi premiado em Londres, pela _Foreign Press Associations_ (FPA), a associação de correspondentes estrangeiros mais antiga do mundo, fundada em 1888. De acordo com o diretor, _O menino que fez um museu_ foi o único trabalho produzido por equipes fora do eixo Estados-Unidos-Europa entre os finalistas. O documentário conta a história de um Brasil profundo, desconhecido até mesmo por muitos brasileiros. É apresentado com o carisma de Pedro Lucas Feitosa, 11 anos. Quanto tinha 10 anos, Pedro Lucas criou o Museu de Luyiz Gonzaga, que fica distrito de Dom Quintino. A ideia surgiu após uma visita que o garoto fez, em 2013, quando tinha 8 anos, ao Museu do Gonzagão, em Exu, Pernambuco. Pedro decidiu criar o próprio lugar de exposição para homenagear o rei e o local escolhido foi a casa da sua bisavó já falecida, que fica ao lado da casa dele, na rua Alto de Antena. Disponível em: www.opovo.com.br. Acesso em> 18 abr. 2018 No segundo parágrafo, uma citação afirma que o documentário “foi o único trabalho produzido por equipes fora do eixo Estados Unidos-Europa entre os finalistas”. No texto, esse recurso expressa uma estratégia argumentativa que reforça a',
  'options': ['A. Originalidade da iniciativa de homenagem à vida vida e à obra de Luiz Gonzaga.',
   'B. Falta de concorrentes ao prêmio de uma das associações mais antigas do mundo.',
   'C. Proeza da premiação de uma história ambientada no interior do Nordeste brasileiro.',
   'D. Escassez de investimentos para a produção cinematográfica independente no país.',
   'E. Importância da parceria entre brasileiros e britânicos para a realização das filmagens']},
 {'id': 10,
  'question': 'Intenso e original, Son of Saul retrata horror do holocausto Centenas de filmes sobre o holocausto já foram produzidos em diversos países do mundo, mas nenhum é tão intenso como o húngaro Son of Saul, do estreante em longa-metragens László Nemes, vencedor do Grande Prêmio do Júri no último Festival de Cannes. Ao contrário da grande maioria das produções do gênero, que costuma oferecer uma variedade de informações didáticas e não raro cruza diferentes pontos de vista sobre o horror do campo de concentração, o filme acompanha apenas um personagem. Ele é Saul (Géza Rohrig), um dos encarregados de conduzir as execuções de judeus como ele que, por um dia e meio, luta obsessivamente para que um menino já morto – que pode ou não ser seu filho – tenha um enterro digno e não seja simplesmente incinerado. O acompanhamento da jornada desse prisioneiro é no sentido mais literal que o cinema pode proporcionar: a câmera está o tempo todo com o personagem, seja por sobre sobre seus ombros, seja como um _close_ em primeiro plano ou em sua visão subjetiva. O que se passa ao seu redor é secundário, muitas vezes desfocado. Saul percorre diferentes divisões de Auschwitz à procura de um rabino que possa conduzir o enterro da criança, e por isso pouco se envolve nos planos de fuga que os companheiros tramam e, quando o faz, geralmente atrapalha. “Você abandonou os vivos para cuidar de um morto”, acusa um deles. Ver toda essa _via crucis_ é por vezes duro e exige certa entrega do espectador, mas certamente é daquelas experiências cinematográficas que permanecem na cabeça por muito tempo. O longa já está sendo apontado como o grande favorito ao Oscar de filme estrangeiro. Se levar a estatueta, certamente não faltará quem diga que a Academia tem uma preferência por quem aborda a 2ª Guerra. Por mais que exista uma dose de verdade na afirmação, premiar uma abordagem tão ousada e radical como _Son of Soul_ não deixaria de ser um passo à frente dos votantes. Carta Capital. n. 873, 22 out. 2015. A resenha é, normalmente, um texto de base argumentativa. Na resenha do filme Son of Saul, o trecho da sequência argumentativa que se constitui como opinião implícita é',
  'options': ['A. "[...] do estreante em longa-metragens László Nemes, vencedor do Grande Prêmio do Júri no último Festival de Cannes".',
   'B. "Ele é Saul (Géza Rohring), um dos encarregados de conduzir as execuções de judeus [...]".',
   'C. "[...] a câmera está o tempo todo com o personagem, seja por sobre seus ombros, seja como um close [...]".',
   'D. "Saul percorre diferentes divisões de Auschwitz à procura de um rabino que possa conduzir o enterro da criança [...]".',
   'E. "[...] premiar uma abordagem tão ousada e radical como Son of Saul não deixaria de ser um passo à frente dos votantes".']},
 {'id': 11,
  'question': 'Sinhá Se a dona se banhou Eu não estava lá Por Deus Nosso Senhor Eu não olhei Sinhá Estava lá na roça Sou de olhar ninguém Não tenho mais cobiça Nem enxergo bem Para que me pôr no tronco Para que me aleijar Eu juro a vosmecê Que nunca vi Sinhá \\[…\\] Por que talhar meu corpo Eu não olhei Sinhá Para que que vosmincê Meus olhos vai furar Eu choro em iorubá Mas oro por Jesus Para que que vassuncê Me tira a luz. CHICO BUARQUE; JOÃO BOSCO. Chico. Rio de Janeiro: Biscoito Fino, 2011 (fragmento). No fragmento da letra da canção, o vocabulário empregado e a situação retratada são relevantes para o patrimônio linguístico e identitário do país, na medida em que',
  'options': ['A. Remetem à violência física e simbólica contra os povos escravizados.',
   'B. Valorizam as influências da cultura africana sobre a música nacional.',
   'C. Relativizam o sincretismo constitutivo das práticas religiosas brasileiras.',
   'D. Narram os infortúnios da relação amorosa entre membros de classes sociais diferentes.',
   'E. Problematizam as diferentes visões de mundo na sociedade durante o período colonial.']},
 {'id': 15,
  'question': 'TEXTO I Correu à sala dos retratos, abriu o piano, sentou-se e espalmou as mãos no teclado. Começou a tocar alguma coisa própria, uma inspiração real e pronta, uma polca, uma polca buliçosa, como dizem os anúncios. Nenhuma repulsa da parte do compositor; os dedos iam arrancando as notas, ligando-as, meneando-as; dir-se-ia que a musa compunha e bailava a um tempo. \\[…….\\] Compunha só, teclando ou escrevendo, sem os vãos esforços da véspera, sem exasperação, sem nada pedir ao céu, sem interrogar os olhos de Mozart. Nenhum tédio. Vida, graça, novidade, escorriam-lhe da alma como de uma fonte perene. ASSIS, M. Um homem célebre. Disponivel em: www.biblio.com.br. Acesso em: 2 jun. 2019. TEXTO II Um homem célebre expõe o suplicio do músico popular que busca atingir a sublimidade da obra-prima clássica, e com ela a galeria dos imortais, mas que é traído por uma disposição interior incontrolável que o empurra implacavelmente na direção oposta. Pestana, célebre nos saraus, salões, bailes e ruas do Rio de Janeiro por suas composições irresistivelmente dançantes, esconde-se dos rumores à sua volta num quarto povoado de ícones da grande música europeia, mergulha nas sonatas do classicismo vienense, prepara-se para o supremo salto criativo e, quando dá por si, é o autor de mais uma inelutável e saltitante polca. WISNIK, J. M. Machado maxixe: o caso Pestana. Teresa: revista de literatura brasileira, 2004 (adaptado). O conto de Machado de Assis faz uma referência velada a maxixe, gênero musical inicialmente associado à escravidão e à mestiçagem. No Texto II, o conflito do personagem em compor obras do gênero é representativo da',
  'options': ['A. Pouca complexidade musical das composições ajustadas ao gosto do grande público.',
   'B. Prevalência de referências musicais africanas no imaginário da população brasileira.',
   'C. Incipiente atribuição de prestígio social a músicas instrumentais feitas para a dança.',
   'D. Tensa relação entre o erudito e o popular na constituição da música brasileira.',
   'E. Importância atribuída à música clássica a sociedade brasileira do século XIX.']},
 {'id': 16,
  'question': 'Devagar, devagarinho Desacelerar é preciso. Acelerar não é preciso. Afobados e voltados para o próprio umbigo, operamos, automatizados, falas robóticas e silêncios glaciais. Ilustra bem esse estado de espírito a música Sinal fechado (1969), de Paulinho de Viola. Trata-se da história de dois sujeitos que se encontram inesperadamente em um sinal de trânsito. A conversa entre ambos, porém, se deu rápida e rasteira. Logo, os personagens se despedem, com a promessa de se verem em outra oportunidade. Percebe-se um registro de comunicação vazia e superficial, cuja tônica foi o contato ligeiro e superficial construído pelos interlocutores: “Olá, como vai? Estou indo, e você, tudo bem? Tudo bem, eu vou indo correndo, pegar meu lugar no futuro. E você? Quanto tempo… Pois é, quanto tempo… Me perdoe a pressa é a alma dos nossos negócios… Oh! Não tem de quê. Eu também só ando a cem”. O culto à velocidade, no contexto apresentado, se coloca como fruto de um imediatismo processual que celebra o alcance dos fins sem dimensionar a qualidade dos meios necessários para atingir determinado propósito. Tal conjuntura favorece a lei do menor esforço – a comodidade – e prejudica a lei do maior esforço – a dignidade. Como modelo alternativo à cultura _fast_, temos o movimento _slow life_, cujo propósito, resumidamente, é conscientizar as pessoas de que a pressa é inimiga da perfeição e do prazer, buscando assim reeducar seus sentidos para desfrutar melhor os sabores da vida. SILVA, M. F. L. Boletim UFMG, n. 1 749, set. 2011 (adaptado). Nesse artigo de opinião, a apresentação da letras da canção Sinal Fechado é uma estratégia argumentativa que visa sensibilizar o leitor porque',
  'options': ['A. Adverte sobre os riscos que o ritmo acelerado da vida oferece.',
   'B. Exemplifica o fato criticado no texto com uma situação concreta.',
   'C. Contrapõe situações de aceleração e de serenidade na vida das pessoas.',
   'D. Questiona o clichê sobre a rapidez e a aceleração da vida moderna',
   'E. Apresenta soluções para a cultura da correria que as pessoas vivenciam hoje.']},
 {'id': 17,
  'question': 'A história do futebol brasileiro contém, ao longo de um século, registros de episódios racistas. Eis o paradoxo: se, de um lado, a atividade futebolística era depreciada aos olhos da “boa sociedade” como profissão destinada aos pobres, negros e marginais, de outro, achava-se investida do poder de representar e projetar a nação em escala mundial. A Copa do Mundo no Brasil, em 1950, viria a se constituir, nesse sentido, em uma rara oportunidade. Contudo, na decisão contra o Uruguai sobreveio o inesperado revés. As crônicas esportivas elegiam o goleiro Barbosa e o defensor Bigode como bodes expiatórios, “descarregando nas costas” dos jogadores os “prejuízos” da derrota. Uma chibata moral, eis a a sentença proferida no tribunal do brancos. Nos anos 1970, por não atender às expectativas normativas suscitadas pelo estereótipo do “bom negro”, Paulo César Lima foi classificado como “jogador – problema”. Ele esboçava a revolta da chibata no futebol brasileiro. Enquanto Barbosa e Bigode, sem alternativa suportaram o linchamento moral na derrota 1950, Paulo César contra-atacava os que pretendiam condená-lo pelo insucesso de 1974. O jogador assumia as cores e as causas defendidas pela esquadra dos pretos em todas as esferas da vida social. “Sinto na pele esse racismo subjacente” revelou a imprensa francesa: “Isto é, ninguém ousa pronunciar a palavra ‘racismo’. Mas posso garantir que ele existe, mesmo na seleção Brasileira”. Sua ousadia constituiu em pronunciar a palavra interdita no espaço simbólico do discurso oficial para reafirmar o mito da democracia racial. Disponível em: https: observatorioracialfutebol.com.br. Acesso em: 22 jun. 2019 (adaptado) O texto atribui o enfraquecimento do mito da democracia racial no futebol à',
  'options': ['A. Responsabilização dos jogadores negros pela derrota na final da Copa de 1950.',
   'B. Projeção mundial da nação por um esporte antes destinados aos pobres.',
   'C. Depreciação de um esporte associado a marginalidade.',
   'D. Interdição da palavra "racismo" no contexto esportivo.',
   'E. Atitude contestadora de um "jogador-problema".']},
 {'id': 19,
  'question': 'Coincidindo com o Dia Internacional dos Direitos da Infância, foram apresentados diversos trabalhos que mostram as mudanças que afetam a vida das crianças. Um desses estudos compara o que sonham e brincam as crianças hoje em relação às dos anos de 1990. E o que se descobriu é que as crianças têm agora menos lazer e estão mais sobrecarregadas por deveres e atividades extracurriculares do que as de 25 anos atrás. As crianças de hoje não só dedicam menos tempo para brincar, como também, quando brincam, a maioria não o faz com outros crianças no parque, na rua ou na praça, mas em casa e muitas vezes sozinhas. E já não brincam tanto com brinquedos, mas com aparelhos eletrônicos, entre os quais predemonia o jogo individual com a máquina. OLIVIA, M. P. O direito da criança ao lazer… e a crescer sem carências. El País, 20 nov. 2015 (adaptado). O texto indica que as transformações nas experiências lúdicas na infância',
  'options': ['A. Fomentaram as relações sociais entre as crianças.',
   'B. Tornaram o lazer uma prática difundida entre as crianças.',
   'C. Incentivaram a criação de novos espaços para se divertir.',
   'D. Promoveram uma vivência corporal menor ativa.',
   'E. Contribuíram para o aumento do tempo dedicado para brincar.']},
 {'id': 20,
  'question': 'O coreógrafo e bailarino Didier Mulleras se destaca como um dos criadores que descobriram a dança de outro ponto de vista. _Mini@tures_ é uma experiência emblemática entre movimento, computador, internet e vídeo. Com os recursos da computação gráfica, a dança das miniaturas pode caber na palma da mão. Pelo fato de usar a internet como palco, o processo de criação das miniaturas de dança levou em consideração os limites de tempo de download e o tamanho do arquivo, para que um número maios de “espectadores” pudesse assistir. A graça das miniaturas está justamente na contaminação entre mídias: corpo dança computação gráfica internet. De fato, é a rede que faz a maior diferença nesse grupo. _Mini@tures_ explora uma nova dimensão que descobre o espaço-tempo da web e conquista um novo território para a dança contemporânea. A qualquer hora, dança on-line. SPANGHERO, M. A dança dos encéfalos acesos. São Paulo: Itaú Cultural, 2003 (adaptado). Considerado o primeiro projeto de dança contemporânea concebido para a rede, esse trabalho é apresentado como inovador por',
  'options': ['A. Adotar uma perspectiva conceitual como contraposição à tradição de grandes espetáculos.',
   'B. Criar novas formas de financiamento ao utilizar a internet para divulgação das apresentações',
   'C. Privilegiar movimentos gerados por computação gráfica, com a substituição do palco pela tela.',
   'D. Produzir uma arte multimodal, com o intuito de ampliar as possibilidades de expressão estética',
   'E. Redefinir a extensão e o propósito do espetáculo para adaptá-lo ao perfil de diferentes usuários']},
 {'id': 21,
  'question': 'Texto I O mito da estiagem em São Paulo Os estoques de água doce são inesgotáveis, na medida em que são alimentados principalmente pelos oceanos, infinitos via evaporação e precipitação, ou seja, pelo ciclo hidrológico, que depende de forças físicas as quais o homem nunca poderá interromper. Enquanto existirem, o ciclo funcionará e os estoques de água doce nos continentes serão repostos indefinidamente. Obviamente que a água não se distribui equitativamente pelo planeta. Há regiões com muita água, normalmente na zona tropical, na qual a evaporação é maior, e regiões áridas, onde, por razões específicas da dinâmica climática, as taxas de evaporação são maiores do que a precipitação, gerando déficit de reposição de estoques de água doce. Disponível em: www.cartanaescola.com.br. Acesso em: 17 jan. 2015 (adaptado) Texto II O processo de sedimentação no fundo do lago de reservatório é um processo lento. Os sedimentos vão formando argila, que é uma rocha impermeável. Então, a água daquele lago não vai alimentar os aquíferos. Mesmo tendo muita quantidade de água superficial, ela não consegue penetrar no solo para alimentar os aquíferos. Se não for usada no consumo, ela vai simplesmente evaporar e vai cair em outro lugar, qual os aquíferos não conseguem recuperar seu nível, porque não recebem água. Disponível em: www.jornalopcao.com.br. Acesso em: 17 jan. 2015 (adaptado) Os textos I e II abordam a situação dos reservatórios de água doce do planeta. Entretanto, a divergência entre eles está na ideia de que é possível',
  'options': ['A. Manter os estoques de água doce.',
   'B. Utilizar a água superficial para o consumo.',
   'C. Repor os estoques de água doce em regiões áridas.',
   'D. Reduzir as taxas de precipitação e evaporação da água.',
   'E. Equalizar a distribuição de água doce nas diferentes regiões']},
 {'id': 22,

In [33]:
df2021

,id,question,A,B,C,D,E,correct,options
0,6,Um asteroide de cerca de um mil metros diâmetr...,A descrição da velocidade do asteroide.,A recorrência de formulações hipotéticas.,A referência à opinião dos astrônomos.,"A utilização da locução adverbial ""no mínimo"".",A comparação com a distância da Lua à Terra.,B,"[A. A descrição da velocidade do asteroide., B..."
1,7,A draga A gente não sabia se aquela draga tinh...,Contrapõe características da escrita e da fala.,Ironiza a comunicação fora da norma-padrão.,Substitui regionalismos por registros formais.,Valoriza o uso de variedades populares.,Defende novas regras gramaticais.,D,[A. Contrapõe características da escrita e da ...
2,8,"O documentário _O menino que fez um museu_, di...",Originalidade da iniciativa de homenagem à vid...,Falta de concorrentes ao prêmio de uma das ass...,Proeza da premiação de uma história ambientada...,Escassez de investimentos para a produção cine...,Importância da parceria entre brasileiros e br...,C,[A. Originalidade da iniciativa de homenagem à...
3,10,"Intenso e original, Son of Saul retrata horror...","""[...] do estreante em longa-metragens László ...","""Ele é Saul (Géza Rohring), um dos encarregado...","""[...] a câmera está o tempo todo com o person...","""Saul percorre diferentes divisões de Auschwit...","""[...] premiar uma abordagem tão ousada e radi...",E,"[A. ""[...] do estreante em longa-metragens Lás..."
4,11,Sinhá Se a dona se banhou Eu não estava lá Por...,Remetem à violência física e simbólica contra ...,Valorizam as influências da cultura africana s...,Relativizam o sincretismo constitutivo das prá...,Narram os infortúnios da relação amorosa entre...,Problematizam as diferentes visões de mundo na...,A,[A. Remetem à violência física e simbólica con...
5,15,"TEXTO I Correu à sala dos retratos, abriu o pi...",Pouca complexidade musical das composições aju...,Prevalência de referências musicais africanas ...,Incipiente atribuição de prestígio social a mú...,Tensa relação entre o erudito e o popular na c...,Importância atribuída à música clássica a soci...,E,[A. Pouca complexidade musical das composições...
6,16,"Devagar, devagarinho Desacelerar é preciso. Ac...",Adverte sobre os riscos que o ritmo acelerado ...,Exemplifica o fato criticado no texto com uma ...,Contrapõe situações de aceleração e de serenid...,Questiona o clichê sobre a rapidez e a acelera...,Apresenta soluções para a cultura da correria ...,B,[A. Adverte sobre os riscos que o ritmo aceler...
7,17,"A história do futebol brasileiro contém, ao lo...",Responsabilização dos jogadores negros pela de...,Projeção mundial da nação por um esporte antes...,Depreciação de um esporte associado a marginal...,"Interdição da palavra ""racismo"" no contexto es...","Atitude contestadora de um ""jogador-problema"".",E,[A. Responsabilização dos jogadores negros pel...
8,19,Coincidindo com o Dia Internacional dos Direit...,Fomentaram as relações sociais entre as crianças.,Tornaram o lazer uma prática difundida entre a...,Incentivaram a criação de novos espaços para s...,Promoveram uma vivência corporal menor ativa.,Contribuíram para o aumento do tempo dedicado ...,D,[A. Fomentaram as relações sociais entre as cr...
9,20,O coreógrafo e bailarino Didier Mulleras se de...,Adotar uma perspectiva conceitual como contrap...,Criar novas formas de financiamento ao utiliza...,Privilegiar movimentos gerados por computação ...,"Produzir uma arte multimodal, com o intuito de...",Redefinir a extensão e o propósito do espetácu...,D,[A. Adotar uma perspectiva conceitual como con...
10,21,Texto I O mito da estiagem em São Paulo Os est...,Manter os estoques de água doce.,Utilizar a água superficial para o consumo.,Repor os estoques de água doce em regiões áridas.,Reduzir as taxas de precipitação e evaporação ...,Equalizar a distribuição de água doce nas dife...,A,"[A. Manter os estoques de água doce., B. Utili..."
11,22,Os linguistas têm notado a expansão do tratame...,"A escolha de ""você"" ou de ""tu"" está condiciona...","A possibilidade de se usar tanto ""tu"" quanto ""...","O pronome ""tu"" tem sido empregado em situações...","A ocorrência simultânea de ""tu"" e de ""você"" ev...","O emprego de ""você"" em documentos escritos dem...",B,"[A. A escolha de ""você"" ou de ""tu"" está condic..."
12,23,"O solo A morte do cisne, criado em 1905 pelo r...",A composição da coreografia foi influenciada p...,A criação artística é beneficiada pelo encontr...,A variação entre os modos de dançar uma mesma ...,A formação erudita à qual o dançarino não teve...,"A interpretação, por homens, de coreografias o...",B,[A. A composição da coreografia foi influencia...
13,24,Seus primeiros anos de detento foram difíceis;...,Buscam perpetuar visões do senso comum.,Trazem à tona atitudes de um estado de exceção.,Promovem a interlocução com grupos silenciados.,Inspiram o sentimento de justiça por meio da e...,Recorrem ao absurdo como forma de traduzir a r...,B,"[A. Buscam perpetuar visões do senso comum., B..."
14,25,– O senhor pensa que só porque o deixaram mora...,Ironizar atitudes e ideias xenofóbicas.,Conferir à narrativa um tom anedótico.,Dissimular o ponto de vista do narrador.,Acentuar a hostilidade das personagens.,Exaltar relações de poder estereotipadas.,E,"[A. Ironizar atitudes e ideias xenofóbicas., B..."
15,26,"Os velhos papéis, quando não são consumidos pe...","""Os velho papéis"" e ""É assim"".","""algo novo"" e ""sobre o qual.""","""um nome antiga"" e ""Por exemplo.""","""O gigante do Brasil"" e ""O Pedro mencionado.""","""o imperador Dom Pedro II"" e ""O bruxo do Cosme...",D,"[A. ""Os velho papéis"" e ""É assim""., B. ""algo n..."
16,29,Reaprender a ler notícias Não dá mais para ler...,Buscarem fontes de informação comprometidas co...,Privilegiarem notícias veiculadas em jornais d...,Adotarem uma postura crítica em relação às inf...,Questionarem a prática jornalística anterior a...,Valorizarem reportagem redigidas com imparcial...,C,[A. Buscarem fontes de informação comprometida...
17,30,"Não que Pelino fosse químico, longe disso; mas...",Contestar o ensino de regras em detrimento do ...,Resgatar valores patrióticos relacionados às t...,Adotar uma perspectiva complacente em relação ...,Invalidar os usos da língua pautados pelos pre...,Desconsiderar diferentes níveis de formalidade...,E,[A. Contestar o ensino de regras em detrimento...
18,31,O skate apareceu como forma de vivência no laz...,Contribuíram para a democratização do skate.,Evidenciaram as demandas comerciais dos skatis...,Definiram a carreira de skatista profissional.,Permitiram que a prática social do skate subst...,Indicaram a autonomia dos praticantes de skate.,A,[A. Contribuíram para a democratização do skat...
19,32,"Estojo escolar Rio de Janeiro – Noite dessas, ...","Mensagem, elevando-a à categoria de objeto est...","Código, transformando a linguagem utilizada no...","Contexto, fazendo das informações presentes no...","Enunciador, buscando expressar sua atitude em ...","Interlocutor, considerando-o responsável pelo ...",D,"[A. Mensagem, elevando-a à categoria de objeto..."
20,35,Singular ocorrência – Há ocorrências bem singu...,Encontra um modo de dignificar-se na prática d...,Preserva a aparência jovem conforme seu estilo...,Condiciona seu bem-estar à estabilidade do cas...,Tem sua identidade e seu lugar referendados pe...,Renuncia à sua participação no mercado de trab...,D,[A. Encontra um modo de dignificar-se na práti...
21,39,Falso moralista Você condena o que a moçada an...,"""falação"" e ""pros bailes"".","""você"" e ""teatro de revista"".","""perfeito"" e ""Carnaval"".","'bebe bem"" e ""oculista""","""curar e ""falso moralista"".",A,"[A. ""falação"" e ""pros bailes""., B. ""você"" e ""t..."
22,40,Introdução a Alda Dizem que ninguém mais a ama...,Irônica quanto aos efeitos do abandono familiar.,Resignada em face dos métodos terapêuticos em ...,Alimentada pela imersão lírica no espaço da se...,Inspirada pelo universo pouco conhecido da men...,Demarcada por uma linguagem alinhada à busca d...,C,[A. Irônica quanto aos efeitos do abandono fam...
23,41,"O pavão vermelho Ora, a alegria, este pavão ve...",Revela a intenção de isolar-se em seu espaço.,Simboliza a beleza e o esplendor da natureza.,Experimenta a fusão de percepções sensoriais.,Metaforiza a conquista de sua plena realização.,Expressa uma visão de mundo mística e espiritu...,D,[A. Revela a intenção de isolar-se em seu espa...
24,45,No ano em que o maior clarinetista que o Brasi...,Atribuir o desconhecimento da obra de Aberl Fe...,Reivindicar mais investimentos estatais para a...,Destacar a relevância histórica e a riqueza es...,Apresentar ao leitor dados biográficos pouco c...,Constatar a impopularidade do choro diante da ...,C,[A. Atribuir o desconhecimento da obra de Aber...

In [ ]:
itens2021 = carregar_itens(r'D:\ODG\ITENS_PROVA_2021.csv')

itens_filtrados2021 = filtrar_itens(
    itens2021,
    area='LC',
    cor='AZUL',
    co_prova=889 #1003
)

itens_final2021 = cruzar_itens_com_dataset(itens_filtrados2021, df2021)
itens_final2021 = itens_final2021.sort_values("CO_POSICAO")
itens_final2021

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
2619,6,LC,15069,B,1.0,0,NaN,1.77244,0.23114,0.00953,AZUL,889,NaN,NaN
2620,7,LC,120165,D,25.0,0,NaN,2.95920,0.57101,0.16401,AZUL,889,NaN,NaN
2621,8,LC,118073,C,24.0,0,NaN,1.68791,0.79504,0.13105,AZUL,889,NaN,NaN
2623,10,LC,97519,E,18.0,0,NaN,2.39514,-0.22063,0.05035,AZUL,889,NaN,NaN
2624,11,LC,68920,A,20.0,0,NaN,0.96148,-0.66104,0.01713,AZUL,889,NaN,NaN
2628,15,LC,120646,D,14.0,0,NaN,1.57672,1.15232,0.16243,AZUL,889,NaN,NaN
2629,16,LC,86515,B,24.0,0,NaN,2.19688,0.92018,0.10506,AZUL,889,NaN,NaN
2630,17,LC,120170,E,9.0,0,NaN,1.98660,1.65243,0.11374,AZUL,889,NaN,NaN
2632,19,LC,118218,D,9.0,0,NaN,2.68787,0.62089,0.26778,AZUL,889,NaN,NaN
2633,20,LC,120623,D,30.0,0,NaN,1.58074,1.24997,0.12025,AZUL,889,NaN,NaN
2634,21,LC,83331,A,22.0,0,NaN,2.89764,0.57674,0.16815,AZUL,889,NaN,NaN
2635,22,LC,86329,B,26.0,0,NaN,1.80201,0.20928,0.18024,AZUL,889,NaN,NaN
2636,23,LC,119763,B,14.0,0,NaN,3.83474,0.46630,0.21265,AZUL,889,NaN,NaN
2637,24,LC,118240,B,15.0,1,Não permitiu a convergência do algoritmo de es...,NaN,NaN,NaN,AZUL,889,NaN,NaN
2638,25,LC,118279,B,16.0,0,NaN,3.09031,2.70264,0.06863,AZUL,889,NaN,NaN
2639,26,LC,118269,D,18.0,0,NaN,0.88199,2.40855,0.20750,AZUL,889,NaN,NaN
2642,29,LC,96262,C,23.0,0,NaN,2.71876,0.24855,0.14770,AZUL,889,NaN,NaN
2643,30,LC,120154,E,27.0,0,NaN,2.51375,1.26329,0.13472,AZUL,889,NaN,NaN
2644,31,LC,118205,A,11.0,0,NaN,1.01454,0.06185,0.06182,AZUL,889,NaN,NaN
2645,32,LC,120375,D,19.0,0,NaN,2.39615,1.63316,0.20335,AZUL,889,NaN,NaN
2648,35,LC,39441,D,17.0,0,NaN,1.19989,0.74738,0.08770,AZUL,889,NaN,NaN
2652,39,LC,118231,A,25.0,0,NaN,1.42609,-0.65267,0.00765,AZUL,889,NaN,NaN
2653,40,LC,118250,C,17.0,0,NaN,1.91893,0.83254,0.08520,AZUL,889,NaN,NaN
2654,41,LC,37831,D,16.0,0,NaN,0.66145,1.56218,0.00747,AZUL,889,NaN,NaN
2658,45,LC,86594,C,23.0,0,NaN,2.27230,1.56986,0.20724,AZUL,889,NaN,NaN

In [ ]:
#itens_azul = itens2021.query("SG_AREA == 'LC' and TX_COR == 'AZUL'")
#itens_azul.query("CO_POSICAO == 6 and TX_GABARITO == 'B'")
#itens_azul.query("CO_POSICAO == 7 and TX_GABARITO == 'D'")
#itens_azul.query("CO_POSICAO == 8 and TX_GABARITO == 'C'")
#itens_azul

In [61]:
exportar_json(dataset_json2021, r"D:\ODG\outputs n8n\API Response\datasets\enem2021_lc.json")

In [ ]:
#itens_final2021.to_csv("itens_enem_2021_azul.csv", index=False, encoding="utf-8")

In [54]:
#itens_final2021.to_excel("itens_enem_2021_azul.xlsx",index=False)

#### ENEM 2020 - LC

In [9]:
caminho_2020 = r"D:\ODG\outputs n8n\API Response\questoes_enem_2020_lc.json"
df2020, dataset_json2020 = pipeline_enem(caminho_2020)
print(df2020.shape)
dataset_json2020

(29, 9)

[{'id': 6,
  'question': '_Vou-me embora p’ra Pasárgada_ foi o poema de mais longa gestação em toda a minha obra. Vi pela primeira vez esse nome Pasárgada quando tinha os meus dezesseis anos e foi num a autor grego. \\[…\\] Esse nome de Pasárgada, que significa “campo dos persas” ou “tesouro dos persas”, suscitou na minha imaginação uma paisagem fabulosa, um país de delícias, como o de _L’invitation au Voyage_, de Baudelaire. Mais de vinte anos depois, quando eu morava só na minha casa da Rua do Curvelo, num momento de fundo desânimo, da mais aguda sensação de tudo o que eu não tinha feito em minha vida por motivo da doença, saltou-me de súbito do subconsciente este grito estapafúrdio: “Vou-me embora p’ra Pasárgada!” Senti na redondilha a primeira célula de um poema, e tentei realizá-lo, mas fracassei. Alguns anos depois, em idênticas circunstâncias de desalento e tédio, me ocorreu o mesmo desabafo de evasão da “vida besta”. Desta vez o poema saiu sem esforço como se já estivesse pronto dentro de mim. Gosto desse poema porque vejo nele, em escorço, toda a minha vida; \\[…\\] Não sou arquiteto, como meu pai desejava, não fiz nenhuma casa, mas reconstruí e “não de uma forma imperfeita neste mundo de aparências”, uma cidade ilustre, que hoje não é mais a Pasárgada de Ciro, e sim a “minha” Pasárgada. BANDEIRA, M. Itinerário de Pasárgada. Rio de Janeiro: Nova Fronteira; Brasília: INL, 1984. Os processos de interação comunicativa preveem a presença ativa de múltiplos elementos da comunicação, entre os quais se destacam as funções da linguagem. Nesse fragmento, a função da linguagem predominante é a',
  'options': ['A. Emotiva, porque o poeta expõe os sentimentos de angústia que o levaram à criação poética.',
   'B. Referencial, porque o texto informa sobre a origem do nome empregado em um famoso poema de Bandeira.',
   'C. Metalinguística, porque o poeta tece comentários sobre a gênese e o processo de escrita de um de seus poemas.',
   'D. Poética, porque o texto aborda os elementos estéticos de um dos poemas mais conhecidos de Bandeira.',
   'E. Apelativa, porque o poeta tenta convencer os leitores sobre sua dificuldade de compor um poema.']},
 {'id': 8,
  'question': '_Slam_ do Corpo é um encontro pensado para surdos e ouvintes, existente desde 2014, em São Paulo. Uma iniciativa pioneira do grupo Corposinalizante, criado em 2008. (Antes de seguirmos, vale a explicação: o termo _slam_ vem do inglês e significa — numa nova acepção para o verbo geralmente utilizado para dizer “bater com força” — a “poesia falada nos ritmos das palavras e da cidade”). Nos saraus, o primeiro objetivo foi o de botar os poemas em Libras na roda, colocar os surdos para circular e entender esse encontro entre a poesia e a língua de sinais, compreender o encontro dessas duas línguas. Poemas de autoria própria, três minutos, um microfone. Sem figurino, nem adereços, nem acompanhamento musical. O que vale é modular a voz e o corpo, um trabalho artesanal de tornar a palavra “visível”, numa arena cujo objetivo maior é o de emocionar a plateia, tirar o público da passividade, seja pelo humor, horror, caos, doçura e outras tantas sensações. NOVELLI. O. Poesia incorporada. Revista Continente, n. 189. set. 2016 (adaptado). Na prática artística mencionada no texto, o corpo assume papel de destaque ao articular diferentes linguagens com o intuito de',
  'options': ['A. Imprimir ritmo e visibilidade à expressão poética.',
   'B. Redefinir o espaço de circulação da poesia urbana.',
   'C. Estimular produções autorais de usuários de Libras.',
   'D. Traduzir expressões verbais para a língua de sinais.',
   'E. Proporcionar performances estéticas de pessoas surdas.']},
 {'id': 9,
  'question': 'É possível afirmar que muitas expressões idiomáticas transmitidas pela cultura regional possuem autores anônimos, no entanto, algumas delas surgiram em consequência de contextos históricos bem curiosos. “Aquele é um cabra da peste” é um bom exemplo dessas construções. Para compreender essa expressão tão repetida no Nordeste brasileiro, faz-se necessário voltar o olhar para o século 16. “Cabra” remete à forma com que os navegadores portugueses chamavam os índios. Já “peste” estaria ligada à questão da superação e resistência, ou mesmo uma associação com o diabo. Assim, com o passar dos anos, passou-se a utilizar tal expressão para denominar qualquer indivíduo que se mostre corajoso, ou mesmo insolente, já que a expressão pode ter caráter positivo ou negativo. Aliás, quem já não ficou de “nhenhe-nhém” por aí? O termo, que normalmente tem significado de conversa interminável, monótona ou resmungo, tem origem no tupi-guarani e “nhém” significa “falar”. Disponível em: http: leiturasdahistoria.uol.com.br. Acesso em: 13 dez. 2017 A leitura do texto permite ao leitor entrar em contato com',
  'options': ['A. Registros do inventário do português brasileiro.',
   'B. Justificativas da variedade linguística do país.',
   'C. Influências da fala do nordestino no uso da língua.',
   'D. Explorações do falar de um grupo social específico.',
   'E. Representações da mudança linguística do português.']},
 {'id': 10,
  'question': 'O ouro do século 21 Cério, gadolínio, lutécio, promécio e érbio; sumário, térbio e disprósio; hólmio, túlio e itérbio. Essa lista de nomes esquisitos e pouco conhecidos pode parecer a escalação de um time de futebol, que ainda teria no banco de reservas lantânio, neodímio, praseodímio, európio, escândio e ítrio. Mas esses 17 metais, chamados de terras raras, fazem parte da vida de quase todos os humanos do planeta. Chamados por muitos de “ouro do século 21”, “elementos do futuro” ou “vitaminas da indústria”, eles estão nos materiais usados na fabricação de lâmpadas, telas de computadores, tablets e celulares, motores de carros elétricos, baterias e até turbinas eólicas. Apesar de tantas aplicações, o Brasil, dono da segunda maior reserva do mundo desses metais, parou de extraí-los e usá-los em 2002. Agora, volta a pensar em retomar sua exploração. SILVEIRA, E. Disponível em: www.revistaplaneta.com.br. Acesso em: 6 dez. 2017 (adaptado). As aspas sinalizam expressões metafóricas empregadas intencionalmente pelo autor do texto para',
  'options': ['A. Imprimir um tom irônico à reportagem.',
   'B. Incorporar citações de especialistas à reportagem.',
   'C. Atribuir maior valor aos metais, objeto da reportagem.',
   'D. Esclarecer termos científicos empregados na reportagem.',
   'E. Marcar a apropriação de termos de outra ciência pela reportagem.']},
 {'id': 11,
  'question': 'Na sua imaginação perturbada sentia a natureza toda agitando-se para sufocá-la. Aumentavam as sombras. No céu, nuvens colossais e túmidas rolavam para o abismo do horizonte… Na várzea, ao clarão indeciso do crepúsculo, os seres tomavam ares de monstros… As montanhas, subindo ameaçadoras da terra, perfilavam-se tenebrosas… Os caminhos, espreguiçando-se sobre os campos, animavam-se quais serpentes infinitas… As árvores soltas choravam ao vento, como carpideiras fantásticas da natureza morta… Os aflitivos pássaros noturnos gemiam agouros com pios fúnebres. Maria quis fugir, mas os membros cansados não acudiam aos ímpetos do medo e deixavam-na prostrada em uma angústia desesperada. ARANHA, J. P. G. Canaã. São Paulo: Ática, 1997. No trecho, o narrador mobiliza recursos de linguagem que geram uma expressividade centrada na percepção da',
  'options': ['A. Relação entre a natureza opressiva e o desejo de libertação da personagem.',
   'B. Confluência entre o estado emocional da personagem e a configuração da paisagem.',
   'C. Prevalência do mundo natural em relação à fragilidade humana.',
   'D. Depreciação do sentido da vida diante da consciência da morte iminente.',
   'E. Instabilidade psicológica da personagem face à realidade hostil.']},
 {'id': 12,
  'question': 'TEXTO I É pau, é pedra, é o fim do caminho É um resto de toco, é um pouco sozinho É um caco de vidro, é a vida, é o sol É a noite, é a morte, é o laço, é o anzol É peroba-do-campo, é o nó da madeira Caingá, candeia, é o matita-pereira TOM JOBIM. Águas de março. O Tom de Jobim e o tal de João Bosco (disco de bolso). Salvador: Zen Produtora, 1972 (fragmento). TEXTO II A inspiração súbita e certeira do compositor serve ainda de exemplo do lema antigo: nada vem do nada. Para ninguém, nem mesmo para Tom Jobim. Duas fontes são razoavelmente conhecidas. A primeira é o poema O caçador de esmeraldas, do mestre parnasiano Olavo Bilac: “Foi em março, ao findar da chuva, quase à entrada do outono, quando a terra em sede requeimada bebera longamente as águas da estação \\[…\\]”. E a outra é um ponto de macumba, gravado com sucesso por J. B. Carvalho, do Conjunto Tupi: “É pau, é pedra, é seixo miúdo, roda a baiana por cima de tudo”. Combinar Olavo Bilac e macumba já seria bom; mas o que se vê em Águas de março vai muito além: tudo se transforma numa outra coisa e numa outra música, que recompõem o mundo para nós. NESTROVSKI, A, O samba mais bonito do mundo. In: Três canções de Tom Jobim. São Paulo: Cosac Naify, 2004 Ao situar a composição no panorama cultural brasileiro, o Texto II destaca o(a)',
  'options': ['A. Diálogo que a letra da canção estabelece com diferentes tradições da cultura nacional.',
   'B. Singularidade com que o compositor converte referências eruditas em populares.',
   'C. Caráter inovador com que o compositor concebe o processo de criação artística.',
   'D. Relativização que a letra da canção promove na concepção tradicional de originalidade.',
   'E. O resgate que a letra da canção promove de obras pouco conhecidas pelo público no país.']},
 {'id': 13,
  'question': 'Deu vontade de jogar, mas não sabe como reunir os amigos… Muitas vezes é difícil encontrar grupos para bater uma bola. Em função disso, estão sendo disponibilizados aplicativos que reúnem times e reservam espaços para os adeptos da paixão nacional. Num exemplo dessas iniciativas, é possível organizar uma partida de futebol, se inscrever para participar de um jogo, alugar campos e quadras, convidar jogadores. O aplicativo tem dois tipos de usuários: um que o usa como ferramenta de gestão do grupo, convidando amigos para jogar, vendo quem confirmou e avaliando os jogos. Outro usuário é o que busca partidas perto de onde ele está, caso de pessoas que estão de passagem numa cidade. BENEDICTO. M.; MARLI, M. Bola na rede. Retratos: a revista do IBGE, n. 2, 2017 (adaptado). A inter-relação entre tecnologia e sociedade tem estimulado a criação de aplicativos. Nesse texto, isso é percebido pelo desenvolvimento de aplicativos para',
  'options': ['A. Organização de eventos de competições esportivas.',
   'B. Agendamento de viagens para eventos de esporte amador.',
   'C. Mapeamento dos interesses dos praticantes acerca dos esportes.',
   'D. Identificação da escassez de espaços para a vivência dos esportes.',
   'E. Formação de grupos em comunidades virtuais para a prática esportiva.']},
 {'id': 16,
  'question': 'Fomos falar com o tal encarregado, depois com um engenheiro, depois com um supervisor que mandou chamar um engenheiro da nossa companhia, Esses homens são da sua companhia, engenheiro, ele falou, estão pedindo a conta. A companhia está empenhada nessa ponte, gente, falou o engenheiro, vocês não podem sair assim sem mais nem menos. Tinha uma serra circular cortando uns caíbros ali perto, então só dava pra falar quando a serra parava, e aquilo foi dando nos nervos. Falei que a gente tinha o direito de sair quando a gente quisesse, e pronto. Nisso encostou em sujeito de paletó mas sem gravata, o engenheiro continuou falando e a serra cortando. Quando ele parou de falar, 50 Volts aproveitou uma parada da serra e falou que a gente não era bicho pra trabalhar daquele jeito; daí o supervisor falou que, se era falta de mulher, eles davam um jeito. O engenheiro falou que tinha mais de vinte companhias trabalhando na ponte, a maioria com prejuízo, porque era mais uma questão de honra, a gente tinha de acabar a ponte, a nossa companhia nunca ia esquecer nosso trabalho ali naquela ponte, um orgulho nacional. PELLEGRINI, D. A maior ponte do mundo. In: Melhores contos. São Paulo: Global, 2005. As reivindicações dos operários, quanto às condições aviltantes de trabalho a que são submetidos, recebem algumas tentativas de neutralização dos representantes do empregador, das quais a mais forte é o(a)',
  'options': ['A. Sequência da atribuição de responsabilidades e de poder decisório a terceiros.',
   'B. Solicitação em nome dos prejuízos e compromissos para entrega da obra.',
   'C. Intimidação pela discreta presença de um agente de segurança na cena.',
   'D. Promessa de imediato atendimento da carência sexual dos operários.',
   'E. Apelo pela identificação com a empresa extensiva ao amor patriótico.']},
 {'id': 17,
  'question': 'Uma das mais contundentes críticas ao discurso da aptidão física relacionada à saúde está no caráter eminentemente individual de suas propostas, o que serve para obscurecer outros determinantes da saúde. Ou seja, costuma-se apresentar o indivíduo como o problema e a mudança do estilo de vida como a solução. Argumenta-se ainda que o movimento da aptidão física relacionada à saúde considera a existência de uma cultura homogênea na qual todos seriam livres para escolher seus estilos de vida, o que não condiz com a realidade. O fato é que vivemos numa sociedade dividida em classes sociais, na qual nem todas as pessoas têm condições econômicas para adotar um estilo de vida ativo e saudável. Há desigualdades estruturais com raízes políticas, econômicas e sociais que dificultam a adoção desses estilos de vida. FERREIRA. M. S. Aptidão física e saúde na educação física escolar; ampliando o enfoque. RBCE, n. 2. jan. 2001 (adaptado). Com base no texto, a relação entre saúde e estilos de vida',
  'options': ['A. Constrói a ideia de que a mudança individual de hábitos promove a saúde.',
   'B. Considera a homogeneidade da escolha de hábitos saudáveis pelos indivíduos.',
   'C. Reforça a necessidade de solucionar os problemas de saúde da sociedade com a prática de exercícios.',
   'D. Problematiza a organização social e seu impacto na mudança de hábitos dos indivíduos.',
   'E. Reproduz a noção de que a melhoria da aptidão física pela prática de exercícios promove a saúde.']},
 {'id': 18,
  'question': 'Retrato de homem A paisagem estrita ao apuro do muro feito vértebra a vértebra e escuro. A geração dos pelos sobre a casca e os rostos em seus diques de sombra repostos. Os poços com seu lodo de ira e de tensão: entre cimento e fronte — um vão. As setas se atiram às margens de ninguém, ilesas a si mesmas retêm. Compassos de evasão entre falange e rua sondando a solitude nua. E na armadura de coisa salobra, um só segredo: a polpa toda é fruição de medo. ARAÚJO, L.C. Cantochão. Belo Horizonte: Imprensa Publicações — Governo do Estado de Minas Gerais, 1967. No poema, a descrição lírica do objeto representado é orientada por um olhar que',
  'options': ['A. Desvela sentimentos de vazio e angústia sob a aparente austeridade.',
   'B. Expressa desilusão ante a possibilidade de superação do sofrimento.',
   'C. Contrapõe a fragilidade emocional ao uso desmedido da força física.',
   'D. Associa a incomunicabilidade emocional às determinações culturais.',
   'E. Privilegia imagens relacionadas à exposição do dinamismo urbano.']},
 {'id': 19,
  'question': 'Senhor Juiz O instrumento do “crime” que se arrola Nesse processo de contravenção Não é faca, revólver ou pistola, Simplesmente, doutor, é um violão. Será crime, afinal, será pecado, Será delito de tão vis horrores, Perambular na rua um desgraçado Derramando nas praças suas dores? Mande, pois, libertá-lo da agonia (a consciência assim nos insinua) Não sufoque o cantar que vem da rua, Que vem da noite para saudar o dia. É o apelo que aqui lhe dirigimos, Na certeza do seu acolhimento Juntada desta aos autos nós pedimos E pedimos, enfim, deferimento Disponível em: www.migalhas.com.br. Acesso em: 23 set. 2020 (adaptado). Essa petição de habeas corpus, ao transgredir o rigor da linguagem jurídica,',
  'options': ['A. Permite que a narrativa seja objetiva e repleta de sentidos denotativos.',
   'B. Mostra que o cordel explora termos próprios da esfera do direito.',
   'C. Demonstra que o jogo de linguagem proposto atenua a gravidade do delito.',
   'D. Exemplifica como o texto em forma de cordel compromete a solicitação pretendida.',
   'E. Esclarece que os termos “crime” e “processo de contravenção” são sinônimos.']},
 {'id': 21,
  'question': 'Sou o coração do folclore nordestino Eu sou Mateus e Bastião do Boi-bumbá Sou o boneco de Mestre Vitalino Dançando uma ciranda em Itamaracá Eu sou um verso de Carlos Pena Filho Num frevo de Capiba Ao som da Orquestra Armorial Sou Capibaribe Num livro de João Cabral Sou mamulengo de São Bento do Una Vindo no baque solto de maracatu Eu sou um auto de Ariano Suassuna No meio da Feira de Caruaru Sou Frei Caneca do Pastoril do Faceta Levando a flor da lira Pra Nova Jerusalém Sou Luiz Gonzaga E sou do mangue também Eu sou mameluco, sou de Casa Forte Sou de Pernambuco, sou o Leão do Norte LENINE; PINHEIRO, P.C. Leão do Norte. In: LENINE; SUZANO, M. Olho de peixe. São Paulo: Vetas. 1993 (fragmento). O fragmento faz parte da canção brasileira contemporânea e celebra a cultura popular nordestina. Nele, o artista exalta as diferentes manifestações culturais pela',
  'options': ['A. Valorização do teatro, música, artesanato, literatura, dança, personagens históricos e artistas populares, compondo um tecido diversificado e enriquecedor da cultura popular como patrimônio regional e nacional.',
   'B. Identificação dos lugares pernambucanos, manifestações culturais, como o bumba meu boi, as cirandas, os bonecos mamulengos e heróis locais, fazendo com que essa canção se apresente como uma referência à cultura popular nordestina.',
   'C. Exaltação das raízes populares, como a poesia, a literatura de cordel e o frevo, misturadas ao erudito, como a Orquestra Armorial, compondo um rico tecido cultural, que transforma o popular em erudito.',
   'D. Caracterização das festas populares como identidade cultural localizada e como representantes de uma cultura que reflete valores históricos e sociais próprios da população local.',
   'E. Apresentação do Pastoril do Faceta, do maracatu, do bumba meu boi e dos autos como representação da musicalidade e do teatro popular religioso, bastante comum ao folclore brasileiro.']},
 {'id': 23,
  'question': 'Eu tenho empresas e sou digno do visto para ir a Nova York. O dinheiro que chove em Nova York é para pessoas com poder de compra. Pessoas que tenham um visto do consulado americano. O dinheiro que chove em Nova York também é para os nova-iorquinos. São milhares de dólares. \\[…\\] Estou indo para Nova York, onde está chovendo dinheiro. Sou um grande administrador. Sim, está chovendo dinheiro em Nova York. Deu no rádio. Vejo que há pedestres invadindo a via onde trafega o meu carro vermelho, importado da Alemanha. Vejo que há carros nacionais trafegando pela via onde trafega o meu carro vermelho, importado da Alemanha. Ao chegar em Nova York, tomarei providências. SANTANNA, A. O importado vermelho de Noé. In: MORICONI. I. (Org.). _Os cem melhores contos_. Rio de Janeiro: Objetiva. 2001. As repetições e as frases curtas constituem procedimentos linguísticos importantes para a compreensão da temática do texto, pois',
  'options': ['A. Expressam a futilidade do discurso de poder e de distinção do narrador.',
   'B. Disfarçam a falta de densidade das angústias existenciais narradas.',
   'C. Ironizam a valorização da cultura norte-americana pelos brasileiros.',
   'D. Explicitam a ganância financeira do capitalismo contemporâneo.',
   'E. Criticam os estereótipos sociais das visões de mundo elitistas.']},
 {'id': 24,

In [42]:
df2020

,id,question,A,B,C,D,E,correct,options
0,6,_Vou-me embora p’ra Pasárgada_ foi o poema de ...,"Emotiva, porque o poeta expõe os sentimentos d...","Referencial, porque o texto informa sobre a or...","Metalinguística, porque o poeta tece comentári...","Poética, porque o texto aborda os elementos es...","Apelativa, porque o poeta tenta convencer os l...",C,"[A. Emotiva, porque o poeta expõe os sentiment..."
1,8,_Slam_ do Corpo é um encontro pensado para sur...,Imprimir ritmo e visibilidade à expressão poét...,Redefinir o espaço de circulação da poesia urb...,Estimular produções autorais de usuários de Li...,Traduzir expressões verbais para a língua de s...,Proporcionar performances estéticas de pessoas...,A,[A. Imprimir ritmo e visibilidade à expressão ...
2,9,É possível afirmar que muitas expressões idiom...,Registros do inventário do português brasileiro.,Justificativas da variedade linguística do país.,Influências da fala do nordestino no uso da lí...,Explorações do falar de um grupo social especí...,Representações da mudança linguística do portu...,A,[A. Registros do inventário do português brasi...
3,10,"O ouro do século 21 Cério, gadolínio, lutécio,...",Imprimir um tom irônico à reportagem.,Incorporar citações de especialistas à reporta...,"Atribuir maior valor aos metais, objeto da rep...",Esclarecer termos científicos empregados na re...,Marcar a apropriação de termos de outra ciênci...,C,"[A. Imprimir um tom irônico à reportagem., B. ..."
4,11,Na sua imaginação perturbada sentia a natureza...,Relação entre a natureza opressiva e o desejo ...,Confluência entre o estado emocional da person...,Prevalência do mundo natural em relação à frag...,Depreciação do sentido da vida diante da consc...,Instabilidade psicológica da personagem face à...,B,[A. Relação entre a natureza opressiva e o des...
5,12,"TEXTO I É pau, é pedra, é o fim do caminho É u...",Diálogo que a letra da canção estabelece com d...,Singularidade com que o compositor converte re...,Caráter inovador com que o compositor concebe ...,Relativização que a letra da canção promove na...,O resgate que a letra da canção promove de obr...,A,[A. Diálogo que a letra da canção estabelece c...
6,13,"Deu vontade de jogar, mas não sabe como reunir...",Organização de eventos de competições esportivas.,Agendamento de viagens para eventos de esporte...,Mapeamento dos interesses dos praticantes acer...,Identificação da escassez de espaços para a vi...,Formação de grupos em comunidades virtuais par...,E,[A. Organização de eventos de competições espo...
7,16,"Fomos falar com o tal encarregado, depois com ...",Sequência da atribuição de responsabilidades e...,Solicitação em nome dos prejuízos e compromiss...,Intimidação pela discreta presença de um agent...,Promessa de imediato atendimento da carência s...,Apelo pela identificação com a empresa extensi...,E,[A. Sequência da atribuição de responsabilidad...
8,17,Uma das mais contundentes críticas ao discurso...,Constrói a ideia de que a mudança individual d...,Considera a homogeneidade da escolha de hábito...,Reforça a necessidade de solucionar os problem...,Problematiza a organização social e seu impact...,Reproduz a noção de que a melhoria da aptidão ...,D,[A. Constrói a ideia de que a mudança individu...
9,18,Retrato de homem A paisagem estrita ao apuro d...,Desvela sentimentos de vazio e angústia sob a ...,Expressa desilusão ante a possibilidade de sup...,Contrapõe a fragilidade emocional ao uso desme...,Associa a incomunicabilidade emocional às dete...,Privilegia imagens relacionadas à exposição do...,A,[A. Desvela sentimentos de vazio e angústia so...
10,19,Senhor Juiz O instrumento do “crime” que se ar...,Permite que a narrativa seja objetiva e replet...,Mostra que o cordel explora termos próprios da...,Demonstra que o jogo de linguagem proposto ate...,Exemplifica como o texto em forma de cordel co...,Esclarece que os termos “crime” e “processo de...,C,[A. Permite que a narrativa seja objetiva e re...
11,21,Sou o coração do folclore nordestino Eu sou Ma...,"Valorização do teatro, música, artesanato, lit...","Identificação dos lugares pernambucanos, manif...","Exaltação das raízes populares, como a poesia,...",Caracterização das festas populares como ident...,"Apresentação do Pastoril do Faceta, do maracat...",B,"[A. Valorização do teatro, música, artesanato,..."
12,23,Eu tenho empresas e sou digno do visto para ir...,Expressam a futilidade do discurso de poder e ...,Disfarçam a falta de densidade das angústias e...,Ironizam a valorização da cultura norte-americ...,Explicitam a ganância financeira do capitalism...,Criticam os estereótipos sociais das visões de...,A,[A. Expressam a futilidade do discurso de pode...
13,24,"DECRETO N. 28 314, DE 28 DE SETEMBRO DE 2007 D...",Conclusão de uma ação.,Realização de um evento.,Repetição de uma prática.,Continuidade de um processo.,Transferência de responsabilidade.,D,"[A. Conclusão de uma ação., B. Realização de u..."
14,27,"Caminhando contra o vento, Sem lenço e sem doc...","Descritivo e argumentativo, pois o enunciador ...","Dissertativo e argumentativo, pois o enunciado...","Expositivo e injuntivo, pois o enunciador fala...","Narrativo e descritivo, pois o enunciador cont...","Narrativo e injuntivo, pois o enunciador ensin...",D,"[A. Descritivo e argumentativo, pois o enuncia..."
15,28,"Leandro Aparecido Ferreira, o MC Fioti, compôs...",Influência permanente da cultura eurocêntrica ...,Homenagem aos referenciais estéticos que deram...,Necessidade de divulgar a música de concerto n...,Utilização desintencional de uma música excess...,Inter-relação de elementos culturais vindos de...,E,[A. Influência permanente da cultura eurocêntr...
16,29,Seu delegado Eu sou viúvo e tenho um filho hom...,Ironizar as relações familiares modernas.,Reforçar o humor da situação representada.,Expressar perplexidade em relação ao parente.,Atribuir à criança a causa da dúvida existencial.,Questionar os lugares predeterminados da família,B,"[A. Ironizar as relações familiares modernas.,..."
17,31,Mulher tem coração clinicamente partido após m...,"Conto, pois exibe a história de vida de Joanie...","Depoimento, pois expõe o sofrimento da dona do...","Reportagem, pois discute cientificamente a car...","Relato, pois narra um fato estressante vivido ...","Notícia, pois divulga fatos sobre a síndrome d...",E,"[A. Conto, pois exibe a história de vida de Jo..."
18,32,Chiquito tinha quase trinta quando conheceu Ma...,Criticar a natureza forte do filho.,Justificar o gênio difícil de Chiquito.,Legitimar o direito do filho à herança.,Conter o ânimo violento de Chico Lourenço.,Condenar a agressividade do marido contra o fi...,B,"[A. Criticar a natureza forte do filho., B. Ju..."
19,34,A vida às vezes é como um jogo brincado na rua...,Perspectiva infantil assumida pela voz narrativa.,Suspensão da linearidade temporal da narração.,Tentativa de materializar lembranças da infância.,Incidência da memória sobre as imagens narradas.,Alternância entre impressões subjetivas e rela...,A,[A. Perspectiva infantil assumida pela voz nar...
20,35,Em 2000 tivemos a primeira experiência do fute...,"Disseminarem uma modalidade, promovendo a igua...","Superarem jogos malsucedidos no mercado, lança...",Inovarem a modalidade com novas ofertas de jog...,"Explorarem nichos de mercado antes ignorados, ...",Reforçarem estereótipos de gênero masculino ou...,A,"[A. Disseminarem uma modalidade, promovendo a ..."
21,36,"LUTA: prática corporal imprevisível, caracteri...",Contato corporal intenso entre o aluno e seu o...,Contenda entre os alunos que se agridem fisica...,Confronto corporal em que os vencedores são pr...,Combate corporal intencional com ações regulam...,Conflito resolvido pelos alunos por meio de re...,D,[A. Contato corporal intenso entre o aluno e s...
22,38,"Relatos de viagem: nas curvas da Nacional 222,...","""Que linda a 'antiga, muy nobre, sempre leal e...","""'Encantei-me', diriam eles... pelas belas pai...","""Os tripeiros, sinônimo de portuenses, têm org...","""E valorizam tudo o que há de bom ali, como 'a...","""Pois na manhã do 25 de abril, dia da Revoluçã...",A,"[A. ""Que linda a 'antiga, muy nobre, sempre le..."
23,39,Hino à Bandeira Em teu seio formoso retratas E...,Remete a um momento futuro.,Promove a união dos cidadãos.,Valoriza os seus elementos.,Emprega termos religiosos.,Recorre à sua história.,C,"[A. Remete a um momento futuro., B. Promove a ..."
24,40,— O senhor pensa que eu tenho alguma fábrica d...,Sujeição moral amplificada pela pobreza.,Crise econômica em expansão nas cidades.,Salta de diálogo entre patrões e empregados.,Perspicácia marcada pela formação intelectual.,Tensão política gerada pelas ideologias vigentes.,A,"[A. Sujeição moral amplificada pela pobreza., ..."
25,41,"Policarpo Quaresma, cidadão brasileiro, funcio...",Situação social de enunciação representada.,Divergência teórica entre gramáticos e literatos.,Pouca representatividade das línguas indígenas.,Atitude irônica diante da língua dos colonizad...,Tentativa de solicitação do documento demandado.,A,[A. Situação social de enunciação representada...
26,42,Atualmente os jovens estão imersos numa socied...,"Exercitação física, promovendo a saúde.",Vivência de exercícios físicos sistemáticos.,Envolvimento com atividades físicas ao longo d...,Jogo por meio de comandos fornecidos pelo vide...,"Disputa entre jogadores, contribuindo para o i...",A,"[A. Exercitação física, promovendo a saúde., B..."
27,43,Quando quis agilizar o processo de seleção de ...,Agilidade dos softwares.,Passar dos anos.,Linguagem.,Preconceito.,Educação.,D,"[A. Agilidade dos softwares., B. Passar dos an..."
28,45,"Viajo Curitiba das conferências positivistas, ...","Destituido de afetividade, que ironiza os cost...","Marcado pela negatividade, que busca desconstr...","Carregado de melancolia, que constata a falta ...","Embevecido pela simplicidade do cenário, indif...","Distanciado dos elementos narrados, que recorr...",B,"[A. Destituido de afetividade, que ironiza os ..."

In [47]:
itens2020 = carregar_itens(r'D:\ODG\ITENS_PROVA_2020.csv')

itens_filtrados2020 = filtrar_itens(
    itens2020,
    area='LC',
    cor='AZUL',
    co_prova=577 #1003
)

itens_final2020 = cruzar_itens_com_dataset(itens_filtrados2020, df2020)
itens_final2020 = itens_final2020.sort_values("CO_POSICAO")
itens_final2020

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
1787,6,LC,63448,C,19,0,NaN,3.18825,1.25880,0.17432,AZUL,577,NaN,0,NaN
484,8,LC,21377,A,14,0,NaN,1.72932,1.85051,0.14869,AZUL,577,NaN,0,NaN
4358,9,LC,112138,A,20,0,NaN,1.52123,1.91811,0.18523,AZUL,577,NaN,0,NaN
4200,10,LC,112059,C,23,0,NaN,1.10742,1.64000,0.25509,AZUL,577,NaN,0,NaN
3326,11,LC,96433,B,16,0,NaN,1.93001,1.02406,0.14189,AZUL,577,NaN,0,NaN
4304,12,LC,112112,A,20,0,NaN,1.74167,1.51202,0.24386,AZUL,577,NaN,0,NaN
4275,13,LC,112089,E,28,0,NaN,1.60955,0.26979,0.20531,AZUL,577,NaN,0,NaN
3372,16,LC,96861,E,17,0,NaN,2.41993,1.10401,0.14865,AZUL,577,NaN,0,NaN
1634,17,LC,59955,D,10,0,NaN,1.68626,0.30607,0.14643,AZUL,577,NaN,0,NaN
361,18,LC,17055,A,16,0,NaN,1.35608,1.44454,0.23512,AZUL,577,NaN,0,NaN
3848,19,LC,111819,C,4,0,NaN,2.86286,1.44944,0.21361,AZUL,577,NaN,0,NaN
800,21,LC,30842,B,13,0,NaN,0.35878,5.45136,0.16296,AZUL,577,NaN,0,NaN
378,23,LC,17413,A,22,0,NaN,2.78735,1.75256,0.14970,AZUL,577,NaN,0,NaN
4389,24,LC,112151,D,27,0,NaN,3.32308,1.49208,0.18606,AZUL,577,NaN,0,NaN
1947,27,LC,76967,D,18,0,NaN,1.73723,-0.11868,0.05058,AZUL,577,NaN,0,NaN
142,28,LC,11437,E,14,0,NaN,1.16098,1.00730,0.21912,AZUL,577,NaN,0,NaN
151,29,LC,12204,B,23,0,NaN,1.62712,0.53489,0.10236,AZUL,577,NaN,0,NaN
3910,31,LC,111850,E,1,0,NaN,1.40709,0.81183,0.17507,AZUL,577,NaN,0,NaN
2423,32,LC,84295,B,23,0,NaN,1.28796,0.07454,0.01332,AZUL,577,NaN,0,NaN
357,34,LC,16501,A,16,0,NaN,2.14866,2.25510,0.25595,AZUL,577,NaN,0,NaN
1256,35,LC,44328,A,9,0,NaN,1.77440,0.02359,0.18710,AZUL,577,NaN,0,NaN
3361,36,LC,96814,D,11,0,NaN,1.70534,0.36247,0.17758,AZUL,577,NaN,0,NaN
4120,38,LC,111989,A,24,0,NaN,1.48285,1.91416,0.16479,AZUL,577,NaN,0,NaN
3999,39,LC,111903,C,3,0,NaN,2.20830,0.25910,0.17176,AZUL,577,NaN,0,NaN
145,40,LC,11966,A,18,0,NaN,1.22111,1.68280,0.21162,AZUL,577,NaN,0,NaN
430,41,LC,18128,A,26,0,NaN,2.46437,1.68698,0.11090,AZUL,577,NaN,0,NaN
4268,42,LC,112087,A,10,0,NaN,2.07488,0.54207,0.20064,AZUL,577,NaN,0,NaN
899,43,LC,33271,D,29,0,NaN,2.51134,-0.51510,0.04770,AZUL,577,NaN,0,NaN
479,45,LC,20652,B,15,0,NaN,2.46676,2.21741,0.13534,AZUL,577,NaN,0,NaN

In [ ]:
#itens_azul = itens2020.query("SG_AREA == 'LC' and TX_COR == 'AZUL'")
#itens_azul.query("CO_POSICAO == 6 and TX_GABARITO == 'C'") 577
#itens_azul.query("CO_POSICAO == 8 and TX_GABARITO == 'A'") 577
#itens_azul.query("CO_POSICAO == 18 and TX_GABARITO == 'A'") 577
#itens_azul

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO,TP_VERSAO_DIGITAL
361,18,LC,17055,A,16,0,NaN,1.35608,1.44454,0.23512,AZUL,577,NaN,0,NaN

In [60]:
exportar_json(dataset_json2020, r"D:\ODG\outputs n8n\API Response\datasets\enem2020_lc.json")

In [49]:
#itens_final2020.to_csv("itens_enem_2020_azul.csv", index=False, encoding="utf-8")

In [52]:
#itens_final2020.to_excel("itens_enem_2020_azul.xlsx",index=False)

#### Formatação Antiga

### Questões do ENEM 2023

In [64]:
caminho = r"D:\ODG\API Response.json"
with open(caminho, 'r', encoding='utf-8') as f:
    data = json.load(f)

print("Chaves principais:", data.keys())

if "questions" in data:
    df = pd.json_normalize(data["questions"])
else:
    df = pd.json_normalize(data)

print("\nColunas do DataFrame:")
print(df.columns.tolist())

df

Chaves principais: dict_keys(['metadata', 'questions'])

Colunas do DataFrame:
['title', 'index', 'discipline', 'language', 'year', 'context', 'files', 'correctAlternative', 'alternativesIntroduction', 'alternatives']

,title,index,discipline,language,year,context,files,correctAlternative,alternativesIntroduction,alternatives
0,Questão 1 - ENEM 2023,1,linguagens,espanhol,2023,**TEXTO I**\n\n¿QUÉ ME PASA?: \n¿PorQUE ME CU...,[],A,O filme Como estrellas en la tierra aborda o t...,"[{'letter': 'A', 'text': 'Olhar diferenciado p..."
1,Questão 2 - ENEM 2023,2,linguagens,espanhol,2023,None,[],A,"Me niego rotundamente\nA negar mi voz,\nMi san...","[{'letter': 'A', 'text': 'Advérbios como ""rotu..."
2,Questão 3 - ENEM 2023,3,linguagens,espanhol,2023,**“Caramelos” en sus suelos**\n\nLas tierras d...,[],E,"Nesse poema, o eu poético enaltece a","[{'letter': 'A', 'text': 'Característica amist..."
3,Questão 4 - ENEM 2023,4,linguagens,espanhol,2023,Manipular es sembrar en la conciencia y en la ...,[],B,"Nesse texto, a expressão “cortina de humo” rev...","[{'letter': 'A', 'text': 'Amadurece tardiament..."
4,Questão 5 - ENEM 2023,5,linguagens,espanhol,2023,**Que quede claro**\n\nCómo es posible que se ...,[],A,"A letra da canção Que quede claro, da banda cu...","[{'letter': 'A', 'text': 'Indignação diante do..."
5,Questão 6 - ENEM 2023,6,linguagens,None,2023,None,[],D,A sessão do Comitê Olímpico Internacional (COI...,"[{'letter': 'A', 'text': 'Unificação do lema a..."
6,Questão 7 - ENEM 2023,7,linguagens,None,2023,**Mais iluminada que outras**\n\nTenho dois se...,[],A,"Nesse texto, os recursos expressivos usados pe...","[{'letter': 'A', 'text': 'Revelam as marcas da..."
7,Questão 8 - ENEM 2023,8,linguagens,None,2023,**De quem é esta língua?**\n\nUma pequena edit...,[],C,O texto de Agualusa tematiza o preconceito em ...,"[{'letter': 'A', 'text': 'À dificuldade de con..."
8,Questão 9 - ENEM 2023,9,linguagens,None,2023,"Na Idade Média, as notícias se propagavam com ...",[],E,A propagação sistemática de informações é um f...,"[{'letter': 'A', 'text': 'Velocidade de circul..."
9,Questão 10 - ENEM 2023,10,linguagens,None,2023,Se a interferência de contas falsas em discuss...,[],E,"De acordo com o texto, a análise de caracterís...","[{'letter': 'A', 'text': 'Controle da atuação ..."
10,Questão 11 - ENEM 2023,11,linguagens,None,2023,"Maio foi colorido de amarelo, e o foi porque m...",[],D,Considerando os procedimentos argumentativos u...,"[{'letter': 'A', 'text': 'Enumerar as causas d..."
11,Questão 12 - ENEM 2023,12,linguagens,None,2023,Ainda daquela vez pude constatar a bizarrice d...,[],C,"Pela voz de uma empregada da casa, a descrição...","[{'letter': 'A', 'text': 'Opção por termos e e..."
12,Questão 13 - ENEM 2023,13,linguagens,None,2023,Girassol da madrugada \nTeu dedo curioso me s...,[],C,"Perante o outro, o eu lírico revela, na força ...","[{'letter': 'A', 'text': 'Vergonha das marcas ..."
13,Questão 14 - ENEM 2023,14,linguagens,None,2023,"**Dão Lalalão** \nDo povoado do Ão, ou dos sí...",[],D,"Nesse trecho do conto, o gosto dos moradores d...","[{'letter': 'A', 'text': 'Qualidade do som do ..."
14,Questão 15 - ENEM 2023,15,linguagens,None,2023,"As cinzas do Museu Nacional, no Rio de Janeiro...",[],B,A perda dos registros linguísticos no incêndio...,"[{'letter': 'A', 'text': 'Exige a retomada das..."
15,Questão 16 - ENEM 2023,16,linguagens,None,2023,None,[],A,"Mandioca, macaxeira, aipim e castelinha são no...","[{'letter': 'A', 'text': 'Passa por fenômenos ..."
16,Questão 17 - ENEM 2023,17,linguagens,None,2023,Como é bom reencontrar os leitores da _Revista...,[],D,O uso não padrão dos colchetes para nomear a r...,"[{'letter': 'A', 'text': 'Perfil de público-al..."
17,Questão 18 - ENEM 2023,18,linguagens,None,2023,"**TEXTO I**\n\n**Alegria, alegria** \nO sol n...",[],B,Embora oriundas de momentos históricos diferen...,"[{'letter': 'A', 'text': 'Referência às cores ..."
18,Questão 19 - ENEM 2023,19,linguagens,None,2023,None,[],D,“São tantas formas de matar um preto\nQue para...,"[{'letter': 'A', 'text': 'Ressaltar a importân..."
19,Questão 20 - ENEM 2023,20,linguagens,None,2023,None,[],E,No princípio era o verbo. A frase que abre o p...,"[{'letter': 'A', 'text': 'Revelar a origem rel..."
20,Questão 21 - ENEM 2023,21,linguagens,None,2023,None,[],D,Um grupo de pesquisadores da Universidade Fede...,"[{'letter': 'A', 'text': 'Apontaram erros moti..."
21,Questão 22 - ENEM 2023,22,linguagens,None,2023,"Alguém muito recentemente cortara o mato, que ...",[],C,A leitura do texto permite reconhecer a “canti...,"[{'letter': 'A', 'text': 'Representa a memória..."
22,Questão 23 - ENEM 2023,23,linguagens,None,2023,"TEXTO I \nZapeei os canais, como há dezenas d...",[],C,A representação da mulher apresentada no Texto...,"[{'letter': 'A', 'text': 'Censura a formas de ..."
23,Questão 24 - ENEM 2023,24,linguagens,None,2023,![](https://enem.dev/2023/questions/24/78918e1...,[https://enem.dev/2023/questions/24/78918e1a-0...,E,"Esse anúncio publicitário, veiculado durante o...","[{'letter': 'A', 'text': 'Divulgar o canal tel..."
24,Questão 25 - ENEM 2023,25,linguagens,None,2023,"Passado muito tempo, resolvi tentar falar, por...",[],B,"Com a perda de parte da língua na infância, a ...","[{'letter': 'A', 'text': 'Reflete o olhar do p..."
25,Questão 26 - ENEM 2023,26,linguagens,None,2023,**A escravidão**\n\nEsses meninos que aí andam...,[],C,"Publicado em 1902, o texto de Olavo Bilac enfa...","[{'letter': 'A', 'text': 'Descrever de modo im..."
26,Questão 27 - ENEM 2023,27,linguagens,None,2023,None,[],A,E assim as coisas continuaram acontecendo entr...,"[{'letter': 'A', 'text': 'Repetição do pronome..."
27,Questão 28 - ENEM 2023,28,linguagens,None,2023,None,[],C,A garganta é a gruta que guarda o som\nA garga...,"[{'letter': 'A', 'text': 'Revelar as desilusõe..."
28,Questão 29 - ENEM 2023,29,linguagens,None,2023,"Era um gato preto, como convinha a um cultor d...",[],E,"Descrevendo seu gato, o narrador remete ao con...","[{'letter': 'A', 'text': 'Desenho imaginativo ..."
29,Questão 30 - ENEM 2023,30,ciencias-humanas,None,2023,None,[],A,Enquanto estivemos entretidos com os urubus ou...,"[{'letter': 'A', 'text': 'Culto ao medo, infil..."
30,Questão 31 - ENEM 2023,31,linguagens,None,2023,**Migalhas**\n\nEntre a toalha branca e um bul...,[],C,"Nesse poema, a representação do sentimento amo...","[{'letter': 'A', 'text': 'Invocar o interlocut..."
31,Questão 32 - ENEM 2023,32,linguagens,None,2023,None,[],A,O sol começa a descer por trás da vegetação da...,"[{'letter': 'A', 'text': 'Inter-relação de ref..."
32,Questão 33 - ENEM 2023,33,linguagens,None,2023,**Texto I**\n\n![](https://enem.dev/2023/quest...,[https://enem.dev/2023/questions/33/d3f9dfc2-3...,A,Quase cinquenta obras de Lasar Segall foram co...,"[{'letter': 'A', 'text': 'Representar uma esté..."
33,Questão 35 - ENEM 2023,35,linguagens,None,2023,A indústria do esporte eletrônico é um mercado...,[],A,O contexto em que o esporte eletrônico é apres...,"[{'letter': 'A', 'text': 'Condição favorável à..."
34,Questão 36 - ENEM 2023,36,linguagens,None,2023,Marabaixo é uma expressão artistico-cultural f...,[],A,A manifestação do Marabaixo se constituiu em e...,"[{'letter': 'A', 'text': 'Ressignificar episód..."
35,Questão 37 - ENEM 2023,37,linguagens,None,2023,O uso das redes sociais como forma de ampliar ...,[],C,O artista goiano Wolney Fernandes busca expor ...,"[{'letter': 'A', 'text': 'Dar suporte à técnic..."
36,Questão 38 - ENEM 2023,38,linguagens,None,2023,None,[],A,"O mais antigo grupo de rap indígena do país, B...","[{'letter': 'A', 'text': 'Fusão de manifestaçõ..."
37,Questão 39 - ENEM 2023,39,linguagens,None,2023,A petição on-line criada por um cidadão paulis...,[],C,A notícia trata da mudança ocorrida em um dici...,"[{'letter': 'A', 'text': 'Inclusão de informaç..."
38,Questão 40 - ENEM 2023,40,linguagens,None,2023,A neozelandesa Laurel Hubbard fez história nos...,[],B,"No texto, os limites do potencial inclusivo do...","[{'letter': 'A', 'text': 'Dificuldade de conse..."
39,Questão 41 - ENEM 2023,41,linguagens,None,2023,"“Ganhei 25 medalhas em mundiais, sete em Jogos...",[],B,O fato relatado na notícia chama a atenção ace...,"[{'letter': 'A', 'text': 'O desempenho atlétic..."
40,Questão 42 - ENEM 2023,42,linguagens,None,2023,O acesso às Práticas Corporais/Atividades Físi...,[],E,O fator central que impacta a realização de pr...,"[{'letter': 'A', 'text': 'Diferença entre home..."
41,Questão 43 - ENEM 2023,43,linguagens,None,2023,None,[],A,"Mestre e companheiro, disse eu que nos íamos d...","[{'letter': 'A', 'text': 'Metáforas relacionad..."
42,Questão 44 - ENEM 2023,44,linguagens,None,2023,![](https://enem.dev/broken-image.svg),[],A,Essa campanha publicitária do Ministério da Sa...,"[{'letter': 'A', 'text': 'Divulgar um conjunto..."
43,Questão 45 - ENEM 2023,45,linguagens,None,2023,None,[],E,Carta aberta à população brasileira\nPrezados ...,"[{'letter': 'A', 'text': 'A sensibilizar o ido..."

In [65]:
questions = data["questions"]

print("Total de itens:", len(questions))

filtered = [
    item for item in questions
    if item.get("files", []) == [] and item.get("language") is None
]

print("Total após filtro:", len(filtered))

df_filtered = pd.json_normalize(filtered)

df_filtered = df_filtered[df_filtered["index"] != 44] #questão com imagem no contexto
df_filtered

Total de itens: 44
Total após filtro: 37

,title,index,discipline,language,year,context,files,correctAlternative,alternativesIntroduction,alternatives
0,Questão 6 - ENEM 2023,6,linguagens,None,2023,None,[],D,A sessão do Comitê Olímpico Internacional (COI...,"[{'letter': 'A', 'text': 'Unificação do lema a..."
1,Questão 7 - ENEM 2023,7,linguagens,None,2023,**Mais iluminada que outras**\n\nTenho dois se...,[],A,"Nesse texto, os recursos expressivos usados pe...","[{'letter': 'A', 'text': 'Revelam as marcas da..."
2,Questão 8 - ENEM 2023,8,linguagens,None,2023,**De quem é esta língua?**\n\nUma pequena edit...,[],C,O texto de Agualusa tematiza o preconceito em ...,"[{'letter': 'A', 'text': 'À dificuldade de con..."
3,Questão 9 - ENEM 2023,9,linguagens,None,2023,"Na Idade Média, as notícias se propagavam com ...",[],E,A propagação sistemática de informações é um f...,"[{'letter': 'A', 'text': 'Velocidade de circul..."
4,Questão 10 - ENEM 2023,10,linguagens,None,2023,Se a interferência de contas falsas em discuss...,[],E,"De acordo com o texto, a análise de caracterís...","[{'letter': 'A', 'text': 'Controle da atuação ..."
5,Questão 11 - ENEM 2023,11,linguagens,None,2023,"Maio foi colorido de amarelo, e o foi porque m...",[],D,Considerando os procedimentos argumentativos u...,"[{'letter': 'A', 'text': 'Enumerar as causas d..."
6,Questão 12 - ENEM 2023,12,linguagens,None,2023,Ainda daquela vez pude constatar a bizarrice d...,[],C,"Pela voz de uma empregada da casa, a descrição...","[{'letter': 'A', 'text': 'Opção por termos e e..."
7,Questão 13 - ENEM 2023,13,linguagens,None,2023,Girassol da madrugada \nTeu dedo curioso me s...,[],C,"Perante o outro, o eu lírico revela, na força ...","[{'letter': 'A', 'text': 'Vergonha das marcas ..."
8,Questão 14 - ENEM 2023,14,linguagens,None,2023,"**Dão Lalalão** \nDo povoado do Ão, ou dos sí...",[],D,"Nesse trecho do conto, o gosto dos moradores d...","[{'letter': 'A', 'text': 'Qualidade do som do ..."
9,Questão 15 - ENEM 2023,15,linguagens,None,2023,"As cinzas do Museu Nacional, no Rio de Janeiro...",[],B,A perda dos registros linguísticos no incêndio...,"[{'letter': 'A', 'text': 'Exige a retomada das..."
10,Questão 16 - ENEM 2023,16,linguagens,None,2023,None,[],A,"Mandioca, macaxeira, aipim e castelinha são no...","[{'letter': 'A', 'text': 'Passa por fenômenos ..."
11,Questão 17 - ENEM 2023,17,linguagens,None,2023,Como é bom reencontrar os leitores da _Revista...,[],D,O uso não padrão dos colchetes para nomear a r...,"[{'letter': 'A', 'text': 'Perfil de público-al..."
12,Questão 18 - ENEM 2023,18,linguagens,None,2023,"**TEXTO I**\n\n**Alegria, alegria** \nO sol n...",[],B,Embora oriundas de momentos históricos diferen...,"[{'letter': 'A', 'text': 'Referência às cores ..."
13,Questão 19 - ENEM 2023,19,linguagens,None,2023,None,[],D,“São tantas formas de matar um preto\nQue para...,"[{'letter': 'A', 'text': 'Ressaltar a importân..."
14,Questão 20 - ENEM 2023,20,linguagens,None,2023,None,[],E,No princípio era o verbo. A frase que abre o p...,"[{'letter': 'A', 'text': 'Revelar a origem rel..."
15,Questão 21 - ENEM 2023,21,linguagens,None,2023,None,[],D,Um grupo de pesquisadores da Universidade Fede...,"[{'letter': 'A', 'text': 'Apontaram erros moti..."
16,Questão 22 - ENEM 2023,22,linguagens,None,2023,"Alguém muito recentemente cortara o mato, que ...",[],C,A leitura do texto permite reconhecer a “canti...,"[{'letter': 'A', 'text': 'Representa a memória..."
17,Questão 23 - ENEM 2023,23,linguagens,None,2023,"TEXTO I \nZapeei os canais, como há dezenas d...",[],C,A representação da mulher apresentada no Texto...,"[{'letter': 'A', 'text': 'Censura a formas de ..."
18,Questão 25 - ENEM 2023,25,linguagens,None,2023,"Passado muito tempo, resolvi tentar falar, por...",[],B,"Com a perda de parte da língua na infância, a ...","[{'letter': 'A', 'text': 'Reflete o olhar do p..."
19,Questão 26 - ENEM 2023,26,linguagens,None,2023,**A escravidão**\n\nEsses meninos que aí andam...,[],C,"Publicado em 1902, o texto de Olavo Bilac enfa...","[{'letter': 'A', 'text': 'Descrever de modo im..."
20,Questão 27 - ENEM 2023,27,linguagens,None,2023,None,[],A,E assim as coisas continuaram acontecendo entr...,"[{'letter': 'A', 'text': 'Repetição do pronome..."
21,Questão 28 - ENEM 2023,28,linguagens,None,2023,None,[],C,A garganta é a gruta que guarda o som\nA garga...,"[{'letter': 'A', 'text': 'Revelar as desilusõe..."
22,Questão 29 - ENEM 2023,29,linguagens,None,2023,"Era um gato preto, como convinha a um cultor d...",[],E,"Descrevendo seu gato, o narrador remete ao con...","[{'letter': 'A', 'text': 'Desenho imaginativo ..."
23,Questão 30 - ENEM 2023,30,ciencias-humanas,None,2023,None,[],A,Enquanto estivemos entretidos com os urubus ou...,"[{'letter': 'A', 'text': 'Culto ao medo, infil..."
24,Questão 31 - ENEM 2023,31,linguagens,None,2023,**Migalhas**\n\nEntre a toalha branca e um bul...,[],C,"Nesse poema, a representação do sentimento amo...","[{'letter': 'A', 'text': 'Invocar o interlocut..."
25,Questão 32 - ENEM 2023,32,linguagens,None,2023,None,[],A,O sol começa a descer por trás da vegetação da...,"[{'letter': 'A', 'text': 'Inter-relação de ref..."
26,Questão 35 - ENEM 2023,35,linguagens,None,2023,A indústria do esporte eletrônico é um mercado...,[],A,O contexto em que o esporte eletrônico é apres...,"[{'letter': 'A', 'text': 'Condição favorável à..."
27,Questão 36 - ENEM 2023,36,linguagens,None,2023,Marabaixo é uma expressão artistico-cultural f...,[],A,A manifestação do Marabaixo se constituiu em e...,"[{'letter': 'A', 'text': 'Ressignificar episód..."
28,Questão 37 - ENEM 2023,37,linguagens,None,2023,O uso das redes sociais como forma de ampliar ...,[],C,O artista goiano Wolney Fernandes busca expor ...,"[{'letter': 'A', 'text': 'Dar suporte à técnic..."
29,Questão 38 - ENEM 2023,38,linguagens,None,2023,None,[],A,"O mais antigo grupo de rap indígena do país, B...","[{'letter': 'A', 'text': 'Fusão de manifestaçõ..."
30,Questão 39 - ENEM 2023,39,linguagens,None,2023,A petição on-line criada por um cidadão paulis...,[],C,A notícia trata da mudança ocorrida em um dici...,"[{'letter': 'A', 'text': 'Inclusão de informaç..."
31,Questão 40 - ENEM 2023,40,linguagens,None,2023,A neozelandesa Laurel Hubbard fez história nos...,[],B,"No texto, os limites do potencial inclusivo do...","[{'letter': 'A', 'text': 'Dificuldade de conse..."
32,Questão 41 - ENEM 2023,41,linguagens,None,2023,"“Ganhei 25 medalhas em mundiais, sete em Jogos...",[],B,O fato relatado na notícia chama a atenção ace...,"[{'letter': 'A', 'text': 'O desempenho atlétic..."
33,Questão 42 - ENEM 2023,42,linguagens,None,2023,O acesso às Práticas Corporais/Atividades Físi...,[],E,O fator central que impacta a realização de pr...,"[{'letter': 'A', 'text': 'Diferença entre home..."
34,Questão 43 - ENEM 2023,43,linguagens,None,2023,None,[],A,"Mestre e companheiro, disse eu que nos íamos d...","[{'letter': 'A', 'text': 'Metáforas relacionad..."
36,Questão 45 - ENEM 2023,45,linguagens,None,2023,None,[],E,Carta aberta à população brasileira\nPrezados ...,"[{'letter': 'A', 'text': 'A sensibilizar o ido..."

In [66]:
def limpar_texto(texto):
    if pd.isna(texto):
        return ""
    texto = str(texto)
    # remover markdown ** **
    texto = re.sub(r"\*\*", "", texto)
    # remover non-breaking space
    texto = texto.replace("\xa0", " ")
    # remover barras
    texto = texto.replace("/", " ")
    # remover quebras de linha
    texto = texto.replace("\n", " ")
    # normalizar espaços
    texto = re.sub(r"\s+", " ", texto)
    return texto.strip()


# --- dataframe base ---
df_new = df_filtered.copy()

# limpar textos principais
df_new["context"] = df_new["context"].apply(limpar_texto)
df_new["alternativesIntroduction"] = df_new["alternativesIntroduction"].apply(limpar_texto)

# --- juntar contexto + pergunta ---
df_new["question"] = (
    df_new["context"].fillna("") + " " + df_new["alternativesIntroduction"].fillna("")
)

df_new["question"] = df_new["question"].apply(limpar_texto)


# --- extrair alternativas ---
def extrair_alternativas(lista):

    resultado = {"A": None, "B": None, "C": None, "D": None, "E": None}

    if isinstance(lista, list):
        for alt in lista:
            letra = alt.get("letter")
            texto = limpar_texto(alt.get("text"))
            if letra in resultado:
                resultado[letra] = texto

    return pd.Series(resultado)


alts = df_new["alternatives"].apply(extrair_alternativas)

df_final = pd.concat([df_new, alts], axis=1)


# --- montar dataset final ---
df_final = df_final[[
    "index",
    "question",
    "A",
    "B",
    "C",
    "D",
    "E",
    "correctAlternative"
]]

df_final = df_final.rename(columns={
    "index": "id",
    "correctAlternative": "correct"
})


# reset index
df_final = df_final.reset_index(drop=True)

df_final

,id,question,A,B,C,D,E,correct
0,6,A sessão do Comitê Olímpico Internacional (COI...,Unificação do lema anterior ao atual.,Aproximação entre o lema olímpico e o COI.,Junção do lema olímpico com os princípios espo...,Associação entre o lema olímpico e a cooperati...,Vinculação entre o lema olímpico e os eventos ...,D
1,7,"Mais iluminada que outras Tenho dois seios, es...",Revelam as marcas da violência de raça e de gê...,Questionam o pioneirismo do estado do Ceará no...,Reproduzem padrões estéticos em busca da valor...,Sugerem uma atmosfera onírica alinhada ao dese...,"Mimetizam, na paisagem, os corpos transformado...",A
2,8,De quem é esta língua? Uma pequena editora bra...,À dificuldade de consolidação da literatura br...,Aos diferentes graus de instrução formal entre...,À existência de uma língua ideal que alguns fa...,Ao intercâmbio cultural que ocorre entre os po...,À distância territorial entre os falantes do p...,C
3,9,"Na Idade Média, as notícias se propagavam com ...",Velocidade de circulação das notícias.,Nível de letramento da população marginalizada.,Poder de censura por parte dos serviços públicos.,Legitimidade da voz dos representantes da nobr...,Diversidade dos meios disponíveis em uma época...,E
4,10,Se a interferência de contas falsas em discuss...,Controle da atuação dos profissionais de TI.,"Desenvolvimento de tecnologias como os ""trolls"".",Flexibilização dos turnos de trabalho dos cont...,Necessidade de regulamentação do funcionamento...,Identificação de padrões de disseminação de in...,E
5,11,"Maio foi colorido de amarelo, e o foi porque m...",Enumerar as causas determinantes da violência ...,Contextualizar a campanha de advertência no ce...,Divulgar dados numéricos alarmantes sobre acid...,Sensibilizar o público para a importância de u...,Restringir os problemas da violência no trânsi...,D
6,12,Ainda daquela vez pude constatar a bizarrice d...,Opção por termos e expressões de sentido ambíguo.,Crítica social inspirada pelo convívio com os ...,Descrição impressionista do fetiche do persona...,Presença de um foco narrativo de caráter impre...,Ambiência de mistério das relações entre famil...,C
7,13,Girassol da madrugada Teu dedo curioso me segu...,Vergonha das marcas provocadas pela passagem d...,Indecisão em face das possibilidades afetivas ...,Serenidade sedimentada pela entrega pacifica a...,Frustração causada pela vontade de retorno ao ...,Disponibilidade para a exploração do prazer ef...,C
8,14,"Dão Lalalão Do povoado do Ão, ou dos sítios pe...",Qualidade do som do rádio.,Estabilidade do enredo contado.,Ineditismo do capítulo da novela.,Jeito singular de falar aos ouvintes.,Dificuldade de compreensão da história.,D
9,15,"As cinzas do Museu Nacional, no Rio de Janeiro...",Exige a retomada das pesquisas por especialist...,Representa danos irreparáveis à memória e à id...,Impossibilita o surgimento de novas pesquisas ...,Resulta na extinção da cultura de povos origin...,Inviabiliza o estudo da língua do povo Tikuna.,B
10,16,"Mandioca, macaxeira, aipim e castelinha são no...",Passa por fenômenos de variação linguística co...,"Apresenta variações regionais, assumindo novo ...",Sofre mudança estrutural motivada pelo uso de ...,"Diferencia-se em todo o Brasil, desenvolvendo ...",É ininteligível para parte dos usuários em raz...,A
11,17,Como é bom reencontrar os leitores da _Revista...,"Perfil de público-alvo, constituído por leitor...","Propósito do editor, chamando a atenção para o...","Exclusividade na seleção temática, direcionada...","Identidade da revista, voltada para a recepção...","Padrão editorial dos artigos, organizados em t...",D
12,18,"TEXTO I Alegria, alegria O sol nas bancas de r...",Referência às cores como elemento de crítica a...,Percepção da profusão de informações gerada pe...,Contraposição entre os vícios e as virtudes da...,Busca constante pela liberdade de expressão in...,Crítica à finalidade comercial das notícias.,B
13,19,“São tantas formas de matar um preto Que para ...,Ressaltar a importância da poesia para denunci...,Destacar o crescimento exponencial da temática...,Demonstrar o incremento no quantitativo de exp...,Evidenciar argumentos que reforçam a ideia de ...,Salientar o aumento da participação de jovens ...,D
14,20,No princípio era o verbo. A frase que abre o p...,Revelar a origem religiosa da linguagem.,Questionar o temor sobre o futuro da linguagem.,Descrever a relação entre sociedade e linguagem.,Apresentar as consequências do esfacelamento d...,Criticar o obstáculo promovido pelos usos espe...,E
15,21,Um grupo de pesquisadores da Universidade Fede...,Apontaram erros motivados pelo desconhecimento...,Explicaram problemas provocados pela incapacid...,Descobriram novos sintomas de doenças existent...,Propiciaram melhor compreensão dos sintomas do...,Divulgaram um novo rol de doenças característi...,D
16,22,"Alguém muito recentemente cortara o mato, que ...",Representa a memória de uma língua africana ex...,Exalta a rotina executada por jovens afrodesce...,Preserva a ancestralidade africana por meio da...,Resgata a musicalidade africana por meio de pa...,Remonta à tristeza dos negros mais velhos com ...,C
17,23,"TEXTO I Zapeei os canais, como há dezenas de a...",Censura a formas de expressão femininas.,Ausência da figura feminina na vida pública.,Construções imaginárias cristalizadas na socie...,Limitações inerentes às figuras femininas e ma...,Dificuldade na atribuição de papéis masculinos...,C
18,25,"Passado muito tempo, resolvi tentar falar, por...",Reflete o olhar do pai sobre as etapas do plan...,Metaforiza a linguagem como ferramenta de lavo...,"Explicita, na busca pela palavra, o medo da so...",Confirma a frustração da narradora com relação...,"Sugere, na ausência da linguagem, a estagnação...",B
19,26,A escravidão Esses meninos que aí andam jogand...,Descrever de modo impessoal as consequências d...,Contrapor a infância privilegiada das crianças...,Antecipar o futuro apagamento das marcas da es...,Criticar a atenuação da violência contra os po...,Imaginar a reação de indiferença de seus conte...,C
20,27,E assim as coisas continuaram acontecendo entr...,"Repetição do pronome indefinido ""todos"".",Utilização do travessão na marcação do oposto.,"Retomada do antecedente pelo pronome ""isso"".",Contraposição de ideias marcada pela conjunção...,Substantivação de expressões pela anteposição ...,A
21,28,A garganta é a gruta que guarda o som A gargan...,Revelar as desilusões amorosas.,Refletir sobre a censura à sua voz,Expressar a dificuldade de comunicação.,Ressaltar a existência de pressões externas.,Manifestar as dores do processo de criação.,C
22,29,"Era um gato preto, como convinha a um cultor d...",Desenho imaginativo do casario colonial de Our...,Efeito de apagamento de limites entre ficção e...,Vínculo estabelecido entre animais urbanos e l...,Questionamento sutil quanto à sanidade dos inc...,Contraste entre austeridade pomposa e imagem r...,E
23,30,Enquanto estivemos entretidos com os urubus ou...,"Culto ao medo, infiltrado em situações do coti...",Sentimento de dúvida quanto à veracidade das i...,"Ambiente de sonho, delineado por imagens pertu...",Incentivo ao desenvolvimento econômico com a i...,Espaço urbano marcado por uma política de isol...,A
24,31,Migalhas Entre a toalha branca e um bule de ca...,Invocar o interlocutor para uma tomada de posi...,Questionar a validade do envolvimento romântico.,Diluir em banalidade a comoção de um amor frus...,Transformar em paz as emoções conflituosas do ...,Condicionar a existência da paixão a espaços i...,C
25,32,O sol começa a descer por trás da vegetação da...,Inter-relação de referenciais estéticos aparen...,Valorização de músicas que revelam mensagens d...,Consagração do repertório erudito como cultura...,Iniciativa de estímulo à vocação turística da ...,Divisão hierárquica entre gêneros e estilos mu...,A
26,35,A indústria do esporte eletrônico é um mercado...,Condição favorável à expansão dessa modalidade.,Promoção dessa prática por jogadores profissio...,Impulsionamento de um processo de marketing.,Favorecimento de fabricantes dos jogos.,Modificação da audiência televisiva.,A
27,36,Marabaixo é uma expressão artistico-cultural f...,Ressignificar episódios dramáticos em novas pr...,Adaptar coreografias como imitação dos movimen...,Lembrar dos mortos no passado escravista como ...,Perpetuar uma narrativa de apagamento dos fato...,Ritualizar a passagem de atos fúnebres nas pro...,A
28,37,O uso das redes sociais como forma de ampliar ...,Dar suporte à técnica de colagem em Artes Visu...,Aproximar-se da estética visual própria da edi...,Oferecer uma vitrine internacional para sua pr...,Enfatizar o caráter original e inovador de sua...,Trazer um sentido tecnológico às suas colagens...,C
29,38,"O mais antigo grupo de rap indígena do país, B...",Fusão de manifestações artísticas urbanas cont...,Contraposição das temáticas socioambientais in...,Rejeição da indústria radiofônica às músicas i...,Distanciamento da realidade social indígena.,E estímulo ao estudo da poesia indígena.,A
30,39,A petição on-line criada por um cidadão paulis...,Inclusão de informações no verbete.,Relevância social da instituição casamento.,Utilização pública da petição pelos cidadãos.,Rapidez na disseminação digital do verbete.,Divulgação de plataformas para a criação de pe...,C
31,40,A neozelandesa Laurel Hubbard fez história nos...,Dificuldade de conseguir bons resultados espor...,Dependência de características biológicas padr...,Inexistência de uma categoria para pessoas tra...,Necessidade de afastamento temporário das comp...,Impossibilidade de uso controlado de substâncias,B
32,41,"“Ganhei 25 medalhas em mundiais, sete em Jogos...",O desempenho atlético internacional.,A dimensão emocional dos atletas.,Os comitês olímpicos nacionais.,As instituições de inteligência.,As federações esportivas.,B
33,42,O acesso às Práticas Corporais Atividades Físi...,Diferença entre homens e mulheres.,Inexistência de políticas públicas.,Diversidade de faixa etária.,Variação de condição étnica.,Desigualdade entre classes sociais.,E
34,43,"Mestre e companheiro, disse eu que nos íamos d...",Metáforas relacionadas à trajetória pessoal e ...,Recursos fonológicos empregados para a valoriz...,Frases curtas e diretas no relato de vida e da...,Contraposição de ideias presentes na obra do h...,Seleção vocabular representativa do sentimento...,A
35,45,Carta aberta à população brasileira Prezados C...,A sensibilizar o idoso a respeito dos cuidados...,Alertar os governantes sobre os cuidados reque...,Divulgar o trabalho da Sociedade Brasileira de...,Informar o setor público sobre o retrocesso da...,Chamar a atenção da população sobre a qualidad...,E

In [77]:
def montar_opcoes(row):
    return [
        f"A. {row['A']}",
        f"B. {row['B']}",
        f"C. {row['C']}",
        f"D. {row['D']}",
        f"E. {row['E']}",
    ]

df_final["options"] = df_final.apply(montar_opcoes, axis=1)

dataset_json2023 = []

for _, row in df_final.iterrows():
    dataset_json2023.append({
        "id": int(row["id"]),
        "question": row["question"],
        "options": row["options"]
        #"correct": row["correct"]
    })

In [78]:
dataset_json2023

[{'id': 6,
  'question': 'A sessão do Comitê Olímpico Internacional (COI) aprovou uma mudança histórica e inédita no lema olímpico, criado em 1894 pelo Barão Pierre de Coubertin para expressar os valores e a excelência do esporte. Mais de 120 anos depois, o lema tem sua primeira alteração para ressaltar a solidariedade e incluir a palavra “juntos” mais rápido, mais alto, mais forte – juntos. A mudança foi aprovada por unanimidade pelos membros do COI e celebrada pelo presidente da entidade. Disponível em: https: ge.globo.com Acesso em: 10 nov. 2021 (adaptado) De acordo com o texto, a alteração do lema olímpico teve como objetivo a',
  'options': ['A. Unificação do lema anterior ao atual.',
   'B. Aproximação entre o lema olímpico e o COI.',
   'C. Junção do lema olímpico com os princípios esportivos.',
   'D. Associação entre o lema olímpico e a cooperatividade.',
   'E. Vinculação entre o lema olímpico e os eventos atléticos.']},
 {'id': 7,
  'question': 'Mais iluminada que outras Tenho dois seios, estas duas coxas, duas mãos que me são muito úteis, olhos escuros, estas duas sobrancelhas que preencho com maquiagem comprada por dezenove e noventa e orelhas que não aceitam bijuterias. Este corpo é um corpo faminto, dentado, cruel, capaz e violento. Movo os braços e multidões correm desesperadas. Caminho no escuro com o rosto para baixo, pois cada parte isolada de mim tem sua própria vida e não quero domá-las. Animal da caatinga. Forte demais. Engolidora de espadas e espinhos. Dizem e eu ouvi, mas depois também li, que o estado do Ceará aboliu a escravidão quatro anos antes do restante do país. Todos aqueles corpos que eram trazidos com seus dedos contados, seus calcanhares prontos e seus umbigos em fogo, todos eles foram interrompidos no porto. Um homem – dizem e eu ouvi e depois também li — liderou o levante. E todos esses corpos foram buscar outros incômodos. Foram ser incomodados. ARRAES. J. Redemoinho em dia quente. São Paulo: Alfaguara, 2019. Nesse texto, os recursos expressivos usados pela narradora',
  'options': ['A. Revelam as marcas da violência de raça e de gênero na construção da identidade.',
   'B. Questionam o pioneirismo do estado do Ceará no enfrentamento à escravidão.',
   'C. Reproduzem padrões estéticos em busca da valorização da autoestima feminina.',
   'D. Sugerem uma atmosfera onírica alinhada ao desejo de resgate da espiritualidade.',
   'E. Mimetizam, na paisagem, os corpos transformados pela violência da escravidão.']},
 {'id': 8,
  'question': 'De quem é esta língua? Uma pequena editora brasileira, a Urutau, acaba de lançar em Lisboa uma “antologia antirracista de poetas estrangeiros em Portugal”, com o título Volta para a tua terra. O livro denuncia as diversas formas de racismo a que os imigrantes estão sujeitos. Alguns dos poetas brasileiros antologiados queixam-se do desdém com que um grande número de portugueses acolhe o português brasileiro. É uma queixa frequente. “Aqui em Portugal eles dizem — eles dizem – que nosso português é errado, que nós não falamos português”, escreve a poetisa paulista Maria Giulia Pinheiro, para concluir: “Se a sua linguagem, a lusitana, ainda conserva a palavra da opressão ela não é a mais bonita do mundo. Ela é uma das mais violentas”. AGUALUSA, J. E. Disponível em: https.iloglobo.globo.com Acesso em: 22 nov. 2021 (adaptado). O texto de Agualusa tematiza o preconceito em relação ao português brasileiro. Com base no trecho citado pelo autor, infere-se que esse preconceito se deve',
  'options': ['A. À dificuldade de consolidação da literatura brasileira em outros países.',
   'B. Aos diferentes graus de instrução formal entre os falantes de língua portuguesa.',
   'C. À existência de uma língua ideal que alguns falantes lusitanos creem ser a falada em Portugal.',
   'D. Ao intercâmbio cultural que ocorre entre os povos dos diferentes países de língua portuguesa.',
   'E. À distância territorial entre os falantes do português que vivem em Portugal e no Brasil.']},
 {'id': 9,
  'question': 'Na Idade Média, as notícias se propagavam com surpreendente eficácia. Segundo uma emérita professora de Sorbonne, um cavalo era capaz de percorrer 30 quilômetros por dia, mas o tempo podia se acelerar dependendo do interesse da notícia. As ordens mendicantes tinham um papel importante na disseminação de informações, assim como os jograis, os peregrinos e os vagabundos, porque todos eles percorriam grandes distâncias. As cidades também tinham correios organizados e selos para lacrar mensagens e tentar certificar a veracidade das correspondências. Graças a tudo isso, a circulação de boatos era intensa e politicamente relevante. Um exemplo clássico de _fake news_ da era medieval é a história do rei que desaparece na batalha e reaparece muito depois, idoso e transformado. Disponível em: www.elpais.com.br. Acesso em: 18 jun. 2018 (adaptado) A propagação sistemática de informações é um fenômeno recorrente na história e no desenvolvimento das sociedades. No texto, a eficácia dessa propagação está diretamente relacionada ao (à)',
  'options': ['A. Velocidade de circulação das notícias.',
   'B. Nível de letramento da população marginalizada.',
   'C. Poder de censura por parte dos serviços públicos.',
   'D. Legitimidade da voz dos representantes da nobreza.',
   'E. Diversidade dos meios disponíveis em uma época histórica.']},
 {'id': 10,
  'question': 'Se a interferência de contas falsas em discussões políticas nas redes sociais já representava um perigo para os sistemas democráticos, sua sofisticação e maior semelhança com pessoas reais têm agravado o problema pelo mundo. O perigo cresceu porque a tecnologia e os métodos evoluíram dos robôs, os “bots” — softwares com tarefas on-line automatizadas —, para os “ciborgues” ou “trolls”, contas controladas diretamente por humanos com ajuda de um pouco de automação. Mas pesquisadores começam agora a observar outros padrões de comportamento: quando mensagens não são programadas, sua publicação se concentra só em horários de trabalho, já que é controlada por pessoas cuja profissão é exatamente essa, administrar um perfil falso durante o dia. Outra pista: a pobreza vocabular das mensagens publicadas por esses perfis. Um funcionário de uma empresa que supostamente produzia e vendia perfis falsos explica que às vezes “faltava criatividade” para criar mensagens distintas controlando tantos perfis falsos ao mesmo tempo. GRAGNANI, J. Disponível em: www.bbc.com. Acesso em: 16 dez. 2017. De acordo com o texto, a análise de características da linguagem empregada por perfis automatizados contribui para o(a)',
  'options': ['A. Controle da atuação dos profissionais de TI.',
   'B. Desenvolvimento de tecnologias como os "trolls".',
   'C. Flexibilização dos turnos de trabalho dos controladores.',
   'D. Necessidade de regulamentação do funcionamento dos "bots"',
   'E. Identificação de padrões de disseminação de informações inverídicas.']},
 {'id': 11,
  'question': 'Maio foi colorido de amarelo, e o foi porque mundialmente amarelo é a cor convencionada para as advertências. No trânsito, essas advertências têm sido fatais. A estimativa, caso nada seja feito, é a de que se atinjam assustadoras 2,4 milhões de mortes no trânsito em 2030 em todo o mundo. A pressa constante, o sentimento de invencibilidade, a certeza de invulnerabilidade, a necessidade de poder, a falta de civilidade, a certeza de impunidade, a ausência de solidariedade, a inexistência de compaixão e o desrespeito por si próprio são circunstâncias reais que, não raro, concorrem para o comportamento violento no trânsito. O Maio Amarelo, que preconiza a atenção pela vida, é uma das iniciativas nesse sentido. E é precisamente a atenção pela vida que está esquecida. Essa atenção, por certo, requer menos pressa, mais civilidade, limites assegurados, consciência de vulnerabilidade, solidariedade, compaixão e respeito por si e pelo outro. Reafirmar e praticar esses princípios e valores talvez seja um caminho mais seguro e menos violento, que garanta a vida e não celebre a morte. Disponível em: http: portaldotransito.com.br. Acesso em: 11 dez. 2018 (adaptado). Considerando os procedimentos argumentativos utilizados, infere-se que o objetivo desse texto é',
  'options': ['A. Enumerar as causas determinantes da violência no trânsito.',
   'B. Contextualizar a campanha de advertência no cenário mundial.',
   'C. Divulgar dados numéricos alarmantes sobre acidentes de trânsito.',
   'D. Sensibilizar o público para a importância de uma direção responsável.',
   'E. Restringir os problemas da violência no trânsito a aspectos emocionais.']},
 {'id': 12,
  'question': 'Ainda daquela vez pude constatar a bizarrice dos costumes que constituíam as leis mais ou menos constantes do seu mundo: ao me aproximar, verifiquei que o Sr. Timóteo, gordo e suado, trajava um vestido de franjas e lantejoulas que pertencera a sua mãe. O corpete descia-lhe excessivamente justo na cintura, e aqui e ali rebentava através da costura um pouco da carne aprisionada, esgarçando a fazenda e tornando o prazer de vestir-se daquele modo uma autêntica espécie de suplício. Movia-se ele com lentidão, meneando todas as suas franjas e abanando-se vigorosamente com um desses leques de madeira de sândalo, o que o envolvia numa enjoativa onda de perfume. Não sei direito o que colocara sobre a cabeça, assemelhava-se mais a um turbante ou a um chapéu sem abas de onde saiam vigorosas mechas de cabelos alourados. Como era costume seu também, trazia o rosto pintado — e para isto, bem como para suas vestimentas, apoderara-se de todo o guarda-roupa deixado por sua mãe, também em sua época famosa pela extravagância com que se vestia — o que sem dúvida fazia sobressair-lhe o nariz enorme, tão característico da família Meneses. CARDOSO, L. Crónica da casa assassinada. São Paulo: Circulo do Livro, s.d. Pela voz de uma empregada da casa, a descrição de um dos membros da família exemplifica a renovação da ficção urbana nos anos 1950, aqui observada na',
  'options': ['A. Opção por termos e expressões de sentido ambíguo.',
   'B. Crítica social inspirada pelo convívio com os patrões.',
   'C. Descrição impressionista do fetiche do personagem.',
   'D. Presença de um foco narrativo de caráter impreciso.',
   'E. Ambiência de mistério das relações entre familiares.']},
 {'id': 13,
  'question': 'Girassol da madrugada Teu dedo curioso me segue lento no rosto Os sulcos, as sombras machucadas por onde a \\[vida passou. Que silêncio, prenda minha… Que desvio triunfal \\[da verdade, Que círculos vagarosos na lagoa em que uma asa \\[gratuita roçou.. Tive quatro amores eternos… O primeiro era moça donzela, O segundo… eclipse, boi que fala, cataclisma, O terceiro era a rica senhora, O quarto és tu… E eu afinal me repousei dos \\[meus cuidados ANDRADE, M. Poesias completas. Rio de Janeiro: Nova Fronteira, 2013 (fragmento). Perante o outro, o eu lírico revela, na força das memórias evocadas, a',
  'options': ['A. Vergonha das marcas provocadas pela passagem do tempo.',
   'B. Indecisão em face das possibilidades afetivas do presente.',
   'C. Serenidade sedimentada pela entrega pacifica ao desejo.',
   'D. Frustração causada pela vontade de retorno ao passado.',
   'E. Disponibilidade para a exploração do prazer efêmero.']},
 {'id': 14,
  'question': 'Dão Lalalão Do povoado do Ão, ou dos sítios perto, alguém precisava urgente de querer vir por escutar a novela do rádio. Ouvia-a, aprendia-a, guardava na ideia, e, retornado ao Ão, no dia seguinte, a repetia a outros. Assim estavam jantando, vinham os do povoado receber a nova parte da novela do rádio. Ouvir já tinham ouvido tudo, de uma vez, fugia da regra: falhara ali no Ão, na véspera, o caminhão de um comprador de galinhas e ovos, seo Abrãozinho Buristém, que carregava um rádio pequeno, de pilhas, armara um fio no arame da cerca… Mas queriam escutar outra vez, por confirmação. — “A estória é estável de boa, mal que acompridada: taca e não rende…” — explicava o Zuz ao Dalberto. Soropita começou a recontar o capitulo da novela. Sem trabalho, se recordava das palavras, até com clareza — disso se admirava. Contava com prazer de demorar, encher a sala com o poder de outros altos personagens. Tomar a atenção de todos, pudesse contar aquilo noite adiante. Era preciso trazer luz, nem uns enxergavam mais os outros; quando alguém ria, ria de muito longe. O capitulo da novela estava terminando. ROSA, J. G. Noites do sertão (Corpo de baile). São Paulo: Global, 2021. Nesse trecho do conto, o gosto dos moradores do povoado por ouvir a novela de rádio recontada por Soropita deve-se ao(à)',
  'options': ['A. Qualidade do som do rádio.',
   'B. Estabilidade do enredo contado.',
   'C. Ineditismo do capítulo da novela.',
   'D. Jeito singular de falar aos ouvintes.',
   'E. Dificuldade de compreensão da história.']},
 {'id': 15,
  'question': 'As cinzas do Museu Nacional, no Rio de Janeiro, consumido pelas chamas no mês de setembro de 2018, são mais do que restos de fósseis, cerâmicas e espécimes raros. O museu abrigava, entre mais de 20 milhões de peças, os esqueletos com as respostas para perguntas que ainda não haviam sido respondidas — ou sequer feitas — por pesquisadores brasileiros. E o incêndio pode ter calado para sempre palavras e cantos indígenas ancestrais, de línguas que não existem mais no mundo. O acervo do local continha gravações de conversas, cantos e rituais de dezenas de sociedades indígenas, muitas feitas durante a década de 1960 com antigos gravadores de rolo e que ainda não haviam sido digitalizadas. Alguns dos registros abordavam línguas já extintas, sem falantes originais ainda vivos. “A esperança é que outras instituições tenham registros dessas línguas”, diz a linguista Marilia Facó Soares. A pesquisadora, que trabalha com os índios Tikuna, o maior grupo da Amazônia brasileira, crê ter perdido parte de seu material. “Terei que fazer novas viagens de campo para recompor meus arquivos. Mas obviamente não dá para recuperar a fala de nativos já falecidos, geralmente os mais idosos”, lamenta. Disponível em: https: brasil.elpais.com. Acesso em: 10 dez. 2018 (adaptado). A perda dos registros linguísticos no incêndio do Museu Nacional tem impacto potencializado, uma vez que',
  'options': ['A. Exige a retomada das pesquisas por especialistas de diferentes áreas.',
   'B. Representa danos irreparáveis à memória e à identidade nacionais.',
   'C. Impossibilita o surgimento de novas pesquisas na área.',
   'D. Resulta na extinção da cultura de povos originários.',
   'E. Inviabiliza o estudo da língua do povo Tikuna.']},
 {'id': 16,
  'question': 'Mandioca, macaxeira, aipim e castelinha são nomes diferentes da mesma planta. Semáforo, sinaleiro e farol também significam a mesma coisa. O que muda é só o hábito cultural de cada região. A mesma coisa acontece com a Língua Brasileira de Sinais (Libras). Embora ela seja a comunicação oficial da comunidade surda no Brasil, existem sinais que variam em relação à região, à idade e até ao gênero de quem se comunica. A cor verde, por exemplo, possui sinais diferentes no Rio de Janeiro, Paraná e São Paulo. São os regionalismos na língua de sinais. Essas variações são um dos temas da disciplina Linguística na língua de sinais, oferecida pela Universidade Estadual Paulista (Unesp) ao longo do segundo semestre. “Muitas pessoas pensam que a língua de sinais é universal, o que não é verdade”, explica a professora e chefe do Departamento de Linguística, Literatura e Letras Clássicas da Unesp. “Mesmo dentro de um mesmo país, ela sofre variação em relação à localização geográfica, à faixa etária e até ao gênero dos usuários” completa a especialista. Os surdos podem criar sinais diferentes para identificar lugares, objetos e conceitos. Em São Paulo, o sinal de “cerveja” é feito com um giro do punho como uma meia- volta. Em Minas, a bebida é citada quando os dedos in- dicador e médio batem no lado do rosto. Também ocorrem mudanças históricas. Um sinal pode sofrer alterações decorrentes dos costumes da geração que o utiliza. Disponível em: www.educacao.sp.gov.br. Acesso em 1 nov. 2021 (adaptado) Nesse texto, a Língua Brasileira de Sinais (Libras)',
  'options': ['A. Passa por fenômenos de variação linguística como qualquer outra língua.',
   'B. Apresenta variações regionais, assumindo novo sentido para algumas palavras.',
   'C. Sofre mudança estrutural motivada pelo uso de sinais diferentes para algumas palavras.',
   'D. Diferencia-se em todo o Brasil, desenvolvendo cada região a sua própria língua de sinais.',
   'E. É ininteligível para parte dos usuários em razão das mudanças de sinais motivadas geograficamente.']},
 {'id': 17,
  'question': 'Como é bom reencontrar os leitores da _Revista da Cultura_ por meio de uma publicação com outro visual, conteúdo de qualidade e interesses ampliados! _\\]cultura\\[_, este nome simples, e eu diria mesmo familiar, nasce entre dois colchetes voltados para fora. E não é por acaso: são sinais abertos, receptivos, propícios à circulação de ideias. O DNA da publicação se mantém o mesmo, afinal, por longos anos montamos nossas edições com assuntos saídos das estantes de uma grande livraria — e assim continuará sendo. Literatura, sociologia, filosofia, artes… nunca será difícil montar a pauta da revista porque os livros nos ensinam que monotonia é só para quem não lê. HERZ, P. J _\\]cultura\\[_, n. 1, jun. 2018 (adaptado). O uso não padrão dos colchetes para nomear a revista atribui-lhes uma nova função e está correlacionado ao(à)',
  'options': ['A. Perfil de público-alvo, constituído por leitores exigentes e especializados em leitura acadêmica.',
   'B. Propósito do editor, chamando a atenção para o rigor normativo nos textos da revista.',
   'C. Exclusividade na seleção temática, direcionada para a área das ciências humanas.',
   'D. Identidade da revista, voltada para a recepção e a promoção de ideias circulantes em livros.',
   'E. Padrão editorial dos artigos, organizados em torno de uma proposta de design inovador.']},
 {'id': 18,
  'question': 'TEXTO I Alegria, alegria O sol nas bancas de revista Me enche de alegria e preguiça Quem lê tanta noticia Eu vou Por entre fotos e nomes Os olhos cheios de cores O peito cheio de amores vãos Eu vou Por que não, por que não? VELOSO, C. Alegria, alegria. Rio de Janeiro: Polygram, 1990 (fragmento) ТЕХТО II Anjos tronchos Uns anjos tronchos do Vale do Silício Desses que vivem no escuro em plena luz Disseram vai ser virtuoso no vício Das telas dos azuis mais do que azuis Agora a minha história é um denso algoritmo Que vende venda a vendedores reais Neurônios meus ganharam novo outro ritmo E mais, e mais, e mais, e mais, e mais VELOSO, C. Meu coco. Rio de Janeiro: Sony, 2021 (fragmento) Embora oriundas de momentos históricos diferentes essas letras de canção têm em comum a',
  'options': ['A. Referência às cores como elemento de crítica a hábitos contemporâneos.',
   'B. Percepção da profusão de informações gerada pela tecnologia.',
   'C. Contraposição entre os vícios e as virtudes da vida moderna.',
   'D. Busca constante pela liberdade de expressão individual.',
   'E. Crítica à finalidade comercial das notícias.']},
 {'id': 19,

#### Download do Dump

In [69]:
#with open("enem2023_lc.json", "w", encoding="utf-8") as f:
#    json.dump(dataset_json, f, ensure_ascii=False, indent=2)

### Itens e Cadernos do ENEM 2023

In [70]:
itens = pd.read_csv(r'D:\ODG\ITENS_PROVA_2023.csv', sep=';', encoding='latin1')
itens = itens.sort_values('CO_POSICAO')
itens.shape
itens

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
1237,1,LC,140652,E,5,0,NaN,1.55494,0.70223,0.21103,LARANJA,1288,1.0,1
2842,1,LC,140652,E,5,0,NaN,1.55494,0.70223,0.21103,LEITOR TELA,1290,1.0,0
3992,1,LC,140765,A,6,0,NaN,3.17668,0.44857,0.18727,AZUL,1201,1.0,0
2903,1,LC,140595,B,5,0,NaN,2.11783,1.27877,0.12469,VERDE,1314,0.0,0
699,1,LC,140649,B,5,0,NaN,2.23798,0.86091,0.18548,VERDE,1314,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3649,180,MT,96099,B,1,0,NaN,2.10364,1.58069,0.19261,LARANJA,1298,NaN,1
4445,180,MT,96099,B,1,0,NaN,2.10364,1.58069,0.19261,AMARELA,1296,NaN,0
349,180,MT,125933,B,10,0,NaN,2.60187,2.11188,0.26394,VERDE,1219,NaN,0
4870,180,MT,85504,B,21,0,NaN,2.21375,1.82985,0.15414,AMARELA,1212,NaN,0
5086,180,MT,37441,D,22,0,NaN,3.01304,2.67185,0.08455,CINZA,1214,NaN,0

In [71]:
itens.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5550 entries, 1237 to 5086
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CO_POSICAO        5550 non-null   int64
 1   SG_AREA           5550 non-null   object
 2   CO_ITEM           5550 non-null   int64
 3   TX_GABARITO       5550 non-null   object
 4   CO_HABILIDADE     5550 non-null   int64
 5   IN_ITEM_ABAN      5550 non-null   int64
 6   TX_MOTIVO_ABAN    24 non-null     object
 7   NU_PARAM_A        5526 non-null   float64
 8   NU_PARAM_B        5526 non-null   float64
 9   NU_PARAM_C        5526 non-null   float64
 10  TX_COR            5550 non-null   object
 11  CO_PROVA          5550 non-null   int64
 12  TP_LINGUA         300 non-null    float64
 13  IN_ITEM_ADAPTADO  5550 non-null   int64
dtypes: float64(4), int64(6), object(4)
memory usage: 650.4+ KB

In [72]:
itens_azul = itens.query("SG_AREA == 'LC' and TX_COR == 'AZUL'")
itens_azul

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
3992,1,LC,140765,A,6,0,NaN,3.17668,0.44857,0.18727,AZUL,1201,1.0,0
2994,1,LC,140718,E,8,0,NaN,2.73373,0.00161,0.19391,AZUL,1281,1.0,0
1138,1,LC,140730,D,7,0,NaN,2.77283,0.35669,0.17995,AZUL,1241,0.0,0
3844,1,LC,140743,B,6,0,NaN,2.79003,0.21669,0.49995,AZUL,1201,0.0,0
5063,1,LC,140730,D,7,0,NaN,2.77283,0.35669,0.17995,AZUL,1281,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3692,44,LC,140835,B,20,0,NaN,3.62150,-0.18111,0.18705,AZUL,1281,NaN,0
1835,44,LC,140835,B,20,0,NaN,3.62150,-0.18111,0.18705,AZUL,1241,NaN,0
2542,45,LC,140806,D,16,0,NaN,2.24767,0.37674,0.18584,AZUL,1241,NaN,0
1062,45,LC,140920,E,3,0,NaN,1.41999,0.67926,0.21271,AZUL,1201,NaN,0
3974,45,LC,140806,D,16,0,NaN,2.24767,0.37674,0.18584,AZUL,1281,NaN,0

In [73]:
itens_azul.query("CO_POSICAO == 6 and TX_GABARITO == 'D'")
#itens_azul.query("CO_POSICAO == 7 and TX_GABARITO == 'A'")

#peguei duas questões e o gabarito delas pra ver qual é o co_prova que a API utiliza
# CO_PROVA é 1201

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
480,6,LC,141233,D,9,0,NaN,1.74151,0.50452,0.15417,AZUL,1201,NaN,0

In [74]:
ids = df_final["id"].tolist() #questões de LC

itens_azul = itens.query("CO_PROVA == 1201")
itens_azul = itens_azul[itens_azul["CO_POSICAO"].isin(df_final["id"])]
itens_azul

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
480,6,LC,141233,D,9,0,NaN,1.74151,0.50452,0.15417,AZUL,1201,NaN,0
3991,7,LC,140884,A,17,0,NaN,1.35926,1.14954,0.23381,AZUL,1201,NaN,0
5341,8,LC,141443,C,27,0,NaN,2.20477,0.52119,0.13930,AZUL,1201,NaN,0
3312,9,LC,88031,E,30,0,NaN,1.73107,1.60103,0.19199,AZUL,1201,NaN,0
1206,10,LC,111887,E,29,0,NaN,3.04416,0.33951,0.18330,AZUL,1201,NaN,0
479,11,LC,118301,D,23,0,NaN,0.95292,-0.47764,0.00564,AZUL,1201,NaN,0
3990,12,LC,141776,C,15,0,NaN,1.22341,0.82185,0.06897,AZUL,1201,NaN,0
3311,13,LC,140949,C,16,0,NaN,1.43175,0.80537,0.12273,AZUL,1201,NaN,0
1205,14,LC,140899,D,29,0,NaN,1.22127,1.21426,0.22043,AZUL,1201,NaN,0
478,15,LC,118195,B,30,0,NaN,1.67063,-0.06011,0.08734,AZUL,1201,NaN,0
86,16,LC,140918,A,26,0,NaN,2.96562,0.57507,0.16642,AZUL,1201,NaN,0
4953,17,LC,120115,D,27,0,NaN,3.23823,0.59679,0.20038,AZUL,1201,NaN,0
5476,18,LC,140905,B,28,0,NaN,2.28551,2.41311,0.22100,AZUL,1201,NaN,0
4952,19,LC,141474,D,23,0,NaN,1.63551,0.00891,0.20480,AZUL,1201,NaN,0
5475,20,LC,140869,E,24,0,NaN,1.15309,1.88931,0.22049,AZUL,1201,NaN,0
4689,21,LC,140942,D,25,0,NaN,2.53674,0.28060,0.18430,AZUL,1201,NaN,0
85,22,LC,140847,C,20,0,NaN,3.15133,0.25141,0.17380,AZUL,1201,NaN,0
4688,23,LC,140987,C,22,0,NaN,1.84344,1.65132,0.12303,AZUL,1201,NaN,0
4015,25,LC,140880,B,16,0,NaN,2.11251,0.83411,0.21824,AZUL,1201,NaN,0
3571,26,LC,140959,C,17,0,NaN,3.54204,2.45238,0.11597,AZUL,1201,NaN,0
4533,27,LC,141814,A,18,0,NaN,1.22374,0.19619,0.20612,AZUL,1201,NaN,0
4532,28,LC,141448,C,19,0,NaN,0.99432,-0.13224,0.02226,AZUL,1201,NaN,0
1063,29,LC,140944,E,15,0,NaN,1.74817,1.91976,0.19926,AZUL,1201,NaN,0
2473,30,LC,140885,A,15,0,NaN,3.32492,0.41630,0.18782,AZUL,1201,NaN,0
3851,31,LC,140858,C,16,0,NaN,2.59213,1.19798,0.23009,AZUL,1201,NaN,0
346,32,LC,141229,A,14,0,NaN,2.69040,1.08302,0.17386,AZUL,1201,NaN,0
775,35,LC,141243,A,11,0,NaN,2.00614,-0.27647,0.09754,AZUL,1201,NaN,0
2202,36,LC,141260,A,12,0,NaN,1.74835,0.77042,0.16206,AZUL,1201,NaN,0
2472,37,LC,141201,C,12,0,NaN,1.33139,1.23174,0.22153,AZUL,1201,NaN,0
2471,38,LC,141214,A,13,0,NaN,2.36405,0.00914,0.19662,AZUL,1201,NaN,0
1490,39,LC,97007,C,4,0,NaN,1.95920,0.91289,0.16231,AZUL,1201,NaN,0
3850,40,LC,141212,B,11,0,NaN,1.89020,0.53683,0.20416,AZUL,1201,NaN,0
3849,41,LC,141204,B,10,0,NaN,1.81453,-0.08926,0.19896,AZUL,1201,NaN,0
345,42,LC,141802,E,10,0,NaN,2.59779,-0.03089,0.21017,AZUL,1201,NaN,0
5221,43,LC,16384,A,1,0,NaN,1.35809,0.90650,0.15984,AZUL,1201,NaN,0
1062,45,LC,140920,E,3,0,NaN,1.41999,0.67926,0.21271,AZUL,1201,NaN,0

In [75]:
#itens_azul.to_csv("itens_enem_2023_azul.csv", index=False, encoding="utf-8")

In [76]:
itens_ordenados = itens_azul.sort_values(by="NU_PARAM_B")
itens_ordenados

,CO_POSICAO,SG_AREA,CO_ITEM,TX_GABARITO,CO_HABILIDADE,IN_ITEM_ABAN,TX_MOTIVO_ABAN,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,TX_COR,CO_PROVA,TP_LINGUA,IN_ITEM_ADAPTADO
479,11,LC,118301,D,23,0,NaN,0.95292,-0.47764,0.00564,AZUL,1201,NaN,0
775,35,LC,141243,A,11,0,NaN,2.00614,-0.27647,0.09754,AZUL,1201,NaN,0
4532,28,LC,141448,C,19,0,NaN,0.99432,-0.13224,0.02226,AZUL,1201,NaN,0
3849,41,LC,141204,B,10,0,NaN,1.81453,-0.08926,0.19896,AZUL,1201,NaN,0
478,15,LC,118195,B,30,0,NaN,1.67063,-0.06011,0.08734,AZUL,1201,NaN,0
345,42,LC,141802,E,10,0,NaN,2.59779,-0.03089,0.21017,AZUL,1201,NaN,0
4952,19,LC,141474,D,23,0,NaN,1.63551,0.00891,0.20480,AZUL,1201,NaN,0
2471,38,LC,141214,A,13,0,NaN,2.36405,0.00914,0.19662,AZUL,1201,NaN,0
4533,27,LC,141814,A,18,0,NaN,1.22374,0.19619,0.20612,AZUL,1201,NaN,0
85,22,LC,140847,C,20,0,NaN,3.15133,0.25141,0.17380,AZUL,1201,NaN,0
4689,21,LC,140942,D,25,0,NaN,2.53674,0.28060,0.18430,AZUL,1201,NaN,0
1206,10,LC,111887,E,29,0,NaN,3.04416,0.33951,0.18330,AZUL,1201,NaN,0
2473,30,LC,140885,A,15,0,NaN,3.32492,0.41630,0.18782,AZUL,1201,NaN,0
480,6,LC,141233,D,9,0,NaN,1.74151,0.50452,0.15417,AZUL,1201,NaN,0
5341,8,LC,141443,C,27,0,NaN,2.20477,0.52119,0.13930,AZUL,1201,NaN,0
3850,40,LC,141212,B,11,0,NaN,1.89020,0.53683,0.20416,AZUL,1201,NaN,0
86,16,LC,140918,A,26,0,NaN,2.96562,0.57507,0.16642,AZUL,1201,NaN,0
4953,17,LC,120115,D,27,0,NaN,3.23823,0.59679,0.20038,AZUL,1201,NaN,0
1062,45,LC,140920,E,3,0,NaN,1.41999,0.67926,0.21271,AZUL,1201,NaN,0
2202,36,LC,141260,A,12,0,NaN,1.74835,0.77042,0.16206,AZUL,1201,NaN,0
3311,13,LC,140949,C,16,0,NaN,1.43175,0.80537,0.12273,AZUL,1201,NaN,0
3990,12,LC,141776,C,15,0,NaN,1.22341,0.82185,0.06897,AZUL,1201,NaN,0
4015,25,LC,140880,B,16,0,NaN,2.11251,0.83411,0.21824,AZUL,1201,NaN,0
5221,43,LC,16384,A,1,0,NaN,1.35809,0.90650,0.15984,AZUL,1201,NaN,0
1490,39,LC,97007,C,4,0,NaN,1.95920,0.91289,0.16231,AZUL,1201,NaN,0
346,32,LC,141229,A,14,0,NaN,2.69040,1.08302,0.17386,AZUL,1201,NaN,0
3991,7,LC,140884,A,17,0,NaN,1.35926,1.14954,0.23381,AZUL,1201,NaN,0
3851,31,LC,140858,C,16,0,NaN,2.59213,1.19798,0.23009,AZUL,1201,NaN,0
1205,14,LC,140899,D,29,0,NaN,1.22127,1.21426,0.22043,AZUL,1201,NaN,0
2472,37,LC,141201,C,12,0,NaN,1.33139,1.23174,0.22153,AZUL,1201,NaN,0
3312,9,LC,88031,E,30,0,NaN,1.73107,1.60103,0.19199,AZUL,1201,NaN,0
4688,23,LC,140987,C,22,0,NaN,1.84344,1.65132,0.12303,AZUL,1201,NaN,0
5475,20,LC,140869,E,24,0,NaN,1.15309,1.88931,0.22049,AZUL,1201,NaN,0
1063,29,LC,140944,E,15,0,NaN,1.74817,1.91976,0.19926,AZUL,1201,NaN,0
5476,18,LC,140905,B,28,0,NaN,2.28551,2.41311,0.22100,AZUL,1201,NaN,0
3571,26,LC,140959,C,17,0,NaN,3.54204,2.45238,0.11597,AZUL,1201,NaN,0

### Filtrar questões

In [88]:
#def filtrar_questoes_por_id(dataset, ids):
#    return [item for item in dataset if item["id"] in ids]
def filtrar_com_ano(dataset, ids, ano):
    return [
        {**item, "ano": ano}
        for item in dataset
        if item["id"] in ids
    ]

In [89]:
q2023 = filtrar_com_ano(dataset_json2023, [9, 38], 2023)
q2022 = filtrar_com_ano(dataset_json2022, [26, 34, 31, 8], 2022)
q2021 = filtrar_com_ano(dataset_json2021, [11, 22, 17], 2021)
q2020 = filtrar_com_ano(dataset_json2020, [43, 36, 6], 2020)

dataset_final = q2023 + q2022 + q2021 + q2020

In [90]:
dataset_final

[{'id': 9,
  'question': 'Na Idade Média, as notícias se propagavam com surpreendente eficácia. Segundo uma emérita professora de Sorbonne, um cavalo era capaz de percorrer 30 quilômetros por dia, mas o tempo podia se acelerar dependendo do interesse da notícia. As ordens mendicantes tinham um papel importante na disseminação de informações, assim como os jograis, os peregrinos e os vagabundos, porque todos eles percorriam grandes distâncias. As cidades também tinham correios organizados e selos para lacrar mensagens e tentar certificar a veracidade das correspondências. Graças a tudo isso, a circulação de boatos era intensa e politicamente relevante. Um exemplo clássico de _fake news_ da era medieval é a história do rei que desaparece na batalha e reaparece muito depois, idoso e transformado. Disponível em: www.elpais.com.br. Acesso em: 18 jun. 2018 (adaptado) A propagação sistemática de informações é um fenômeno recorrente na história e no desenvolvimento das sociedades. No texto, a eficácia dessa propagação está diretamente relacionada ao (à)',
  'options': ['A. Velocidade de circulação das notícias.',
   'B. Nível de letramento da população marginalizada.',
   'C. Poder de censura por parte dos serviços públicos.',
   'D. Legitimidade da voz dos representantes da nobreza.',
   'E. Diversidade dos meios disponíveis em uma época histórica.'],
  'ano': 2023},
 {'id': 38,
  'question': 'O mais antigo grupo de rap indígena do país, Brô MCs, surgiu em 2009, na aldeia Jaguapiru, em Dourados, Mato Grosso do Sul. Os integrantes conheceram o rap pelo rádio, ouvindo um programa que apresentava cantores e grupos brasileiros desse gênero musical. O Brô MCs conseguiu influenciar outros a fazerem rap e a lutarem pelas causas indígenas. Um dos nomes do movimento, Kunumi MC, é um jovem de 16 anos, da aldeia Krukutu, em São Paulo. O adolescente enxerga o rap como uma cultura da defesa e começou a fazer rimas quando percebeu que a poesia, pela qual sempre se interessou, podia virar música. Nas letras que cria, inspiradas tanto pelo rap quanto pelos ritmos indígenas, tenta incluir sempre assuntos aos quais acha importante dar voz, principalmente, a questão da demarcação de terras. Disponível em: www.correiobraziliense.com.br. Acesso em: 13 nov. 2021 (adaptado). O movimento rap dos povos originários do Brasil revela o(a)',
  'options': ['A. Fusão de manifestações artísticas urbanas contemporâneas com a cultura indígena.',
   'B. Contraposição das temáticas socioambientais indigenas as questões urbanas.',
   'C. Rejeição da indústria radiofônica às músicas indígenas.',
   'D. Distanciamento da realidade social indígena.',
   'E. E estímulo ao estudo da poesia indígena.'],
  'ano': 2023},
 {'id': 8,
  'question': 'É ruivo? Tem olhos azuis? É homem ou mulher? Usa chapéu? Quem jogou Cara a Cara na infância sabe de cor o roteiro de perguntas para adivinhar quem é o personagem misterioso do seu oponente. Agora, o jogo está prestes a ganhar uma nova versão. A designer polonesa Zuzia Kozerska-Girard está desenvolvendo uma variação do _Guess Who?_ (nome do Cara a Cara em inglês), em que as personalidades do tabuleiro são, na verdade, mulheres notáveis da história e da atualidade, como a artista Frida Kahlo, a ativista Malala Yousafzai, a astronauta Valentina Tereshkova e a aviadora Amelia Earhart. O _Who’s She?_ (“Quem é ela?”, em português) traz, no total, 28 mulheres que representam diversas profissões, nacionalidades e idades. A ideia é que, em vez de perguntar sobre a aparência das personagens, as questões sejam direcionadas aos feitos delas: ganhou algum Nobel, fez alguma descoberta? Para cada personagem há um cartão com fatos divertidos e interessantes sobre sua vida. Uma campanha entrou no ar com o objetivo de arrecadar dinheiro para desenvolver o _Who’s She?_. A meta inicial era reunir 17 mil dólares. Oito dias antes de a campanha acabar, o projeto já angariou quase 350 mil dólares. A chegada do jogo à casa do comprador varia de acordo com a quantia doada — quanto mais você doou, mais rápido vai poder jogar. Disponível em: www.super.abril.com.br. Acesso em: 4 dez. 2018 (adaptado). Ao divulgar a adaptação do jogo para questões relativas a ações e habilidades de mulheres notáveis, o texto busca',
  'options': ['A. Contribuir para a formação cidadã dos jogadores.',
   'B. Refutar modelos estereotipados de beleza e elegância.',
   'C. Estimular a competitividade entre potenciais compradores.',
   'D. Exemplificar estratégias de arrecadação financeira pela internet.',
   'E. Desenvolver conhecimentos lúdicos específicos dos tempos atuais.'],
  'ano': 2022},
 {'id': 26,
  'question': 'Assentamento Assentamento Zanza daqui Zanza pra acolá Fim de feira, periferia afora A cidade não mora mais em mim Francisco, Serafim Vamos embora Ver o capim Ver o baobá Vamos ver a campina quando flora A piracema, rios contravim Binho, Bel, Bia, Quim Vamos embora Quando eu morrer Cansado de guerra Morro de bem Com a minha terra: Cana, caqui Inhame, abóbora Onde só vento se semeava outrora Amplidão, nação, sertão sem fim Ó Manuel, Miguilim Vamos embora BUARQUE, C. As cidades. Rio de Janeiro: RCA, 1998 (fragmento). Nesse texto, predomina a função poética da linguagem. Entretanto, a função emotiva pode ser identificada no verso:',
  'options': ['A. “Zanza pra acolá”.',
   'B. “Fim de feira, periferia afora”.',
   'C. “A cidade não mora mais em mim”.',
   'D. "Onde só vento se semeava outrora”.',
   'E. “Ó Manuel, Miguilim”.'],
  'ano': 2022},
 {'id': 31,
  'question': 'Era o êxodo da seca de 1898. Uma ressurreição de cemitérios antigos — esqueletos redivivos, com o aspecto terroso e o fedor das covas podres. Os fantasmas estropiados como que iam dançando, de tão trôpegos e trêmulos, num passo arrastado de quem leva as pernas, em vez de ser levado por elas. Andavam devagar, olhando para trás, como quem quer voltar. Não tinham pressa em chegar, porque não sabiam aonde iam. Expulsos de seu paraíso por espadas de fogo, iam, ao acaso, em descaminhos, no arrastão dos maus fados. Fugiam do sol e o sol guiava-os nesse forçado nomadismo. Adelgaçados na magreira cômica, cresciam, como se o vento os levantasse. E os braços afinados desciam-lhes aos joelhos, de mãos abanando. Vinham escoteiros. Menos os hidrópicos — de ascite consecutiva à alimentação tóxica — com os fardos das barrigas alarmantes. Não tinham sexo, nem idade, nem condição nenhuma. Eram os retirantes. Nada mais. ALMEIDA, J. A. A bagaceira. Rio de Janeiro: J. Olympio, 1978. Os recursos composicionais que inserem a obra no chamado “Romance de 30” da literatura brasileira manifestam-se aqui no(a)',
  'options': ['A. Desenho cru da realidade dramática dos retirantes.',
   'B. Indefinição dos espaços para efeito de generalização.',
   'C. Análise psicológica da reação dos personagens à seca.',
   'D. Engajamento político do narrador ante as desigualdades.',
   'E. Contemplação lírica da paisagem transformada em alegoria.'],
  'ano': 2022},
 {'id': 34,
  'question': 'Criado há cerca de 20 anos na Califórnia, o mountainboard é um esporte de aventura que utiliza uma espécie de skate off-road para realizar manobras similares às das modalidades de snowboard, surf e do próprio skate. A atividade chegou ao Brasil em 1997 e hoje possui centenas de praticantes, um circuito nacional respeitável e mais de uma dezena de pistas espalhadas pelo país. Segundo consta na história oficial, o mountainboard foi criado por praticantes de snowboard que sentiam falta de praticar o esporte nos períodos sem neve. Para isso, eles desenvolveram um equipamento bem simples: uma prancha semelhante ao modelo utilizado na neve (menor e um pouco menos flexível), com dois eixos bem resistentes, alças para encaixar os pés e quatro pneus com câmaras de ar para regular a velocidade que pode ser alcançada em diferentes condições. Com essa configuração, o esporte se mostrou possível em diversos tipos de terreno: grama, terra, pedras, asfalto e areia. Além desses pisos, também é possível procurar pelas próprias trilhas para treinar as manobras. Disponível em: www.webventure.com.br. Acesso em: 19 jun. 2019. A história da prática do mountainboard representa uma das principais marcas das atividades de aventura, caracterizada pela',
  'options': ['A. Competitividade entre seus praticantes.',
   'B. Atividade com padrões técnicos definidos.',
   'C. Modalidade com regras predeterminadas.',
   'D. Criatividade para adaptações a novos espaços.',
   'E. Necessidade de espaços definidos para a sua realização.'],
  'ano': 2022},
 {'id': 11,
  'question': 'Sinhá Se a dona se banhou Eu não estava lá Por Deus Nosso Senhor Eu não olhei Sinhá Estava lá na roça Sou de olhar ninguém Não tenho mais cobiça Nem enxergo bem Para que me pôr no tronco Para que me aleijar Eu juro a vosmecê Que nunca vi Sinhá \\[…\\] Por que talhar meu corpo Eu não olhei Sinhá Para que que vosmincê Meus olhos vai furar Eu choro em iorubá Mas oro por Jesus Para que que vassuncê Me tira a luz. CHICO BUARQUE; JOÃO BOSCO. Chico. Rio de Janeiro: Biscoito Fino, 2011 (fragmento). No fragmento da letra da canção, o vocabulário empregado e a situação retratada são relevantes para o patrimônio linguístico e identitário do país, na medida em que',
  'options': ['A. Remetem à violência física e simbólica contra os povos escravizados.',
   'B. Valorizam as influências da cultura africana sobre a música nacional.',
   'C. Relativizam o sincretismo constitutivo das práticas religiosas brasileiras.',
   'D. Narram os infortúnios da relação amorosa entre membros de classes sociais diferentes.',
   'E. Problematizam as diferentes visões de mundo na sociedade durante o período colonial.'],
  'ano': 2021},
 {'id': 17,
  'question': 'A história do futebol brasileiro contém, ao longo de um século, registros de episódios racistas. Eis o paradoxo: se, de um lado, a atividade futebolística era depreciada aos olhos da “boa sociedade” como profissão destinada aos pobres, negros e marginais, de outro, achava-se investida do poder de representar e projetar a nação em escala mundial. A Copa do Mundo no Brasil, em 1950, viria a se constituir, nesse sentido, em uma rara oportunidade. Contudo, na decisão contra o Uruguai sobreveio o inesperado revés. As crônicas esportivas elegiam o goleiro Barbosa e o defensor Bigode como bodes expiatórios, “descarregando nas costas” dos jogadores os “prejuízos” da derrota. Uma chibata moral, eis a a sentença proferida no tribunal do brancos. Nos anos 1970, por não atender às expectativas normativas suscitadas pelo estereótipo do “bom negro”, Paulo César Lima foi classificado como “jogador – problema”. Ele esboçava a revolta da chibata no futebol brasileiro. Enquanto Barbosa e Bigode, sem alternativa suportaram o linchamento moral na derrota 1950, Paulo César contra-atacava os que pretendiam condená-lo pelo insucesso de 1974. O jogador assumia as cores e as causas defendidas pela esquadra dos pretos em todas as esferas da vida social. “Sinto na pele esse racismo subjacente” revelou a imprensa francesa: “Isto é, ninguém ousa pronunciar a palavra ‘racismo’. Mas posso garantir que ele existe, mesmo na seleção Brasileira”. Sua ousadia constituiu em pronunciar a palavra interdita no espaço simbólico do discurso oficial para reafirmar o mito da democracia racial. Disponível em: https: observatorioracialfutebol.com.br. Acesso em: 22 jun. 2019 (adaptado) O texto atribui o enfraquecimento do mito da democracia racial no futebol à',
  'options': ['A. Responsabilização dos jogadores negros pela derrota na final da Copa de 1950.',
   'B. Projeção mundial da nação por um esporte antes destinados aos pobres.',
   'C. Depreciação de um esporte associado a marginalidade.',
   'D. Interdição da palavra "racismo" no contexto esportivo.',
   'E. Atitude contestadora de um "jogador-problema".'],
  'ano': 2021},
 {'id': 22,
  'question': 'Os linguistas têm notado a expansão do tratamento informal. “Tenho 78 anos e devia ser tratado por _senhor_, mas meus alunos mais jovens me tratam por _você_“, diz o professor Ataliba Castilho, aparentemente sem se incomodar com a informalidade, inconcebível em seus tempos de estudante. O você, porém, não reinará sozinho. O _tu_ predomina em Porto Alegre e convive com o você no Rio de Janeiro e em Recife, enquanto você é o tratamento predominante em São Paulo, Curitiba, Belo Horizonte e Salvador. O _tu_ já era mais próximo e menos formal que _você_ nas quase 500 cartas do acervo on-line de uma instituição universitária, quase todas de poetas, políticos e outras personalidades do final do século XIX e início do XX. Disponível em: http: revistapesquisa.fapesp.br. Acesso em: 21 abr. 2015 (adaptado). No texto, constata-se que os usos de pronomes variaram ao longo do tempo e que atualmente têm empregos diversos pelas regiões do Brasil. Esse processo revela que',
  'options': ['A. A escolha de "você" ou de "tu" está condicionada à idade da pessoa que usa o pronome.',
   'B. A possibilidade de se usar tanto "tu" quanto "você" caracteriza a diversidade da língua.',
   'C. O pronome "tu" tem sido empregado em situações informais por todo o país.',
   'D. A ocorrência simultânea de "tu" e de "você" evidencia a inexistência da distinção entre níveis de formalidade.',
   'E. O emprego de "você" em documentos escritos demonstra que a língua tende a se manter inalterada.'],
  'ano': 2021},
 {'id': 6,
  'question': '_Vou-me embora p’ra Pasárgada_ foi o poema de mais longa gestação em toda a minha obra. Vi pela primeira vez esse nome Pasárgada quando tinha os meus dezesseis anos e foi num a autor grego. \\[…\\] Esse nome de Pasárgada, que significa “campo dos persas” ou “tesouro dos persas”, suscitou na minha imaginação uma paisagem fabulosa, um país de delícias, como o de _L’invitation au Voyage_, de Baudelaire. Mais de vinte anos depois, quando eu morava só na minha casa da Rua do Curvelo, num momento de fundo desânimo, da mais aguda sensação de tudo o que eu não tinha feito em minha vida por motivo da doença, saltou-me de súbito do subconsciente este grito estapafúrdio: “Vou-me embora p’ra Pasárgada!” Senti na redondilha a primeira célula de um poema, e tentei realizá-lo, mas fracassei. Alguns anos depois, em idênticas circunstâncias de desalento e tédio, me ocorreu o mesmo desabafo de evasão da “vida besta”. Desta vez o poema saiu sem esforço como se já estivesse pronto dentro de mim. Gosto desse poema porque vejo nele, em escorço, toda a minha vida; \\[…\\] Não sou arquiteto, como meu pai desejava, não fiz nenhuma casa, mas reconstruí e “não de uma forma imperfeita neste mundo de aparências”, uma cidade ilustre, que hoje não é mais a Pasárgada de Ciro, e sim a “minha” Pasárgada. BANDEIRA, M. Itinerário de Pasárgada. Rio de Janeiro: Nova Fronteira; Brasília: INL, 1984. Os processos de interação comunicativa preveem a presença ativa de múltiplos elementos da comunicação, entre os quais se destacam as funções da linguagem. Nesse fragmento, a função da linguagem predominante é a',
  'options': ['A. Emotiva, porque o poeta expõe os sentimentos de angústia que o levaram à criação poética.',
   'B. Referencial, porque o texto informa sobre a origem do nome empregado em um famoso poema de Bandeira.',
   'C. Metalinguística, porque o poeta tece comentários sobre a gênese e o processo de escrita de um de seus poemas.',
   'D. Poética, porque o texto aborda os elementos estéticos de um dos poemas mais conhecidos de Bandeira.',
   'E. Apelativa, porque o poeta tenta convencer os leitores sobre sua dificuldade de compor um poema.'],
  'ano': 2020},
 {'id': 36,
  'question': 'LUTA: prática corporal imprevisível, caracterizada por determinado estado de contato proposital, que possibilita a duas ou mais pessoas se enfrentarem numa constante troca de ações ofensivas e ou defensivas, regidas por regras, com o objetivo mútuo sobre um alvo móvel personificado no oponente. GOMES, M. S. P. _et al_. Ensino das lutas: dos princípios condicionais aos grupos situacionais. Movimento, n. 2, abr.-jun. 2010 (adaptado). De acordo com o texto, podemos identificar uma abordagem das lutas nas aulas de educação física quando o professor realiza uma proposta envolvendo',
  'options': ['A. Contato corporal intenso entre o aluno e seu oponente.',
   'B. Contenda entre os alunos que se agridem fisicamente.',
   'C. Confronto corporal em que os vencedores são previamente identificados.',
   'D. Combate corporal intencional com ações regulamentadas entre os oponentes.',
   'E. Conflito resolvido pelos alunos por meio de regras previamente estabelecidas.'],
  'ano': 2020},
 {'id': 43,
  'question': 'Quando quis agilizar o processo de seleção de novos alunos, a tradicional faculdade britânica de medicina St. George usou um software para definir quem deveria ser entrevistado. Ao reproduzir a forma como os funcionários faziam essa escolha, o programa eliminou, de cara, 60 de 2.000 candidatos. Só por causa do sexo ou da origem racial, numa dedução baseada em sobrenome e local de nascimento. Um estudo sobre o caso foi publicado em 1988, mas, 25 anos depois, outra pesquisa apontou que esse tipo de discriminação segue firme. O exemplo recente envolve o buscador do Google: ao digitar nomes comuns entre negros dos EUA, a chance de os anúncios automáticos oferecerem checagem de antecedentes criminais pode aumentar 25%. E pode piorar com a pergunta “detido?” logo após a palavra procurada. Disponível em: https: tab.uol.com.br. _Acesso em: 11 ago. 2017 (adaptado)._ O texto permite o desnudamento da sociedade ao relacionar as tecnologias de informação e comunicação com o(a)',
  'options': ['A. Agilidade dos softwares.',
   'B. Passar dos anos.',
   'C. Linguagem.',
   'D. Preconceito.',
   'E. Educação.'],
  'ano': 2020}]

In [ ]:
#q2023 = filtrar_questoes_por_id(dataset_json2023, [9, 38])
#q2022 = filtrar_questoes_por_id(dataset_json2022, [26, 34, 31, 8])
#q2021 = filtrar_questoes_por_id(dataset_json2021, [11, 22, 17])
#q2020 = filtrar_questoes_por_id(dataset_json2020, [43, 36, 6])
#dataset_final = q2023 + q2022 + q2021 + q2020

In [82]:
dataset_final

[{'id': 9,
  'question': 'Na Idade Média, as notícias se propagavam com surpreendente eficácia. Segundo uma emérita professora de Sorbonne, um cavalo era capaz de percorrer 30 quilômetros por dia, mas o tempo podia se acelerar dependendo do interesse da notícia. As ordens mendicantes tinham um papel importante na disseminação de informações, assim como os jograis, os peregrinos e os vagabundos, porque todos eles percorriam grandes distâncias. As cidades também tinham correios organizados e selos para lacrar mensagens e tentar certificar a veracidade das correspondências. Graças a tudo isso, a circulação de boatos era intensa e politicamente relevante. Um exemplo clássico de _fake news_ da era medieval é a história do rei que desaparece na batalha e reaparece muito depois, idoso e transformado. Disponível em: www.elpais.com.br. Acesso em: 18 jun. 2018 (adaptado) A propagação sistemática de informações é um fenômeno recorrente na história e no desenvolvimento das sociedades. No texto, a eficácia dessa propagação está diretamente relacionada ao (à)',
  'options': ['A. Velocidade de circulação das notícias.',
   'B. Nível de letramento da população marginalizada.',
   'C. Poder de censura por parte dos serviços públicos.',
   'D. Legitimidade da voz dos representantes da nobreza.',
   'E. Diversidade dos meios disponíveis em uma época histórica.']},
 {'id': 38,
  'question': 'O mais antigo grupo de rap indígena do país, Brô MCs, surgiu em 2009, na aldeia Jaguapiru, em Dourados, Mato Grosso do Sul. Os integrantes conheceram o rap pelo rádio, ouvindo um programa que apresentava cantores e grupos brasileiros desse gênero musical. O Brô MCs conseguiu influenciar outros a fazerem rap e a lutarem pelas causas indígenas. Um dos nomes do movimento, Kunumi MC, é um jovem de 16 anos, da aldeia Krukutu, em São Paulo. O adolescente enxerga o rap como uma cultura da defesa e começou a fazer rimas quando percebeu que a poesia, pela qual sempre se interessou, podia virar música. Nas letras que cria, inspiradas tanto pelo rap quanto pelos ritmos indígenas, tenta incluir sempre assuntos aos quais acha importante dar voz, principalmente, a questão da demarcação de terras. Disponível em: www.correiobraziliense.com.br. Acesso em: 13 nov. 2021 (adaptado). O movimento rap dos povos originários do Brasil revela o(a)',
  'options': ['A. Fusão de manifestações artísticas urbanas contemporâneas com a cultura indígena.',
   'B. Contraposição das temáticas socioambientais indigenas as questões urbanas.',
   'C. Rejeição da indústria radiofônica às músicas indígenas.',
   'D. Distanciamento da realidade social indígena.',
   'E. E estímulo ao estudo da poesia indígena.']},
 {'id': 8,
  'question': 'É ruivo? Tem olhos azuis? É homem ou mulher? Usa chapéu? Quem jogou Cara a Cara na infância sabe de cor o roteiro de perguntas para adivinhar quem é o personagem misterioso do seu oponente. Agora, o jogo está prestes a ganhar uma nova versão. A designer polonesa Zuzia Kozerska-Girard está desenvolvendo uma variação do _Guess Who?_ (nome do Cara a Cara em inglês), em que as personalidades do tabuleiro são, na verdade, mulheres notáveis da história e da atualidade, como a artista Frida Kahlo, a ativista Malala Yousafzai, a astronauta Valentina Tereshkova e a aviadora Amelia Earhart. O _Who’s She?_ (“Quem é ela?”, em português) traz, no total, 28 mulheres que representam diversas profissões, nacionalidades e idades. A ideia é que, em vez de perguntar sobre a aparência das personagens, as questões sejam direcionadas aos feitos delas: ganhou algum Nobel, fez alguma descoberta? Para cada personagem há um cartão com fatos divertidos e interessantes sobre sua vida. Uma campanha entrou no ar com o objetivo de arrecadar dinheiro para desenvolver o _Who’s She?_. A meta inicial era reunir 17 mil dólares. Oito dias antes de a campanha acabar, o projeto já angariou quase 350 mil dólares. A chegada do jogo à casa do comprador varia de acordo com a quantia doada — quanto mais você doou, mais rápido vai poder jogar. Disponível em: www.super.abril.com.br. Acesso em: 4 dez. 2018 (adaptado). Ao divulgar a adaptação do jogo para questões relativas a ações e habilidades de mulheres notáveis, o texto busca',
  'options': ['A. Contribuir para a formação cidadã dos jogadores.',
   'B. Refutar modelos estereotipados de beleza e elegância.',
   'C. Estimular a competitividade entre potenciais compradores.',
   'D. Exemplificar estratégias de arrecadação financeira pela internet.',
   'E. Desenvolver conhecimentos lúdicos específicos dos tempos atuais.']},
 {'id': 26,
  'question': 'Assentamento Assentamento Zanza daqui Zanza pra acolá Fim de feira, periferia afora A cidade não mora mais em mim Francisco, Serafim Vamos embora Ver o capim Ver o baobá Vamos ver a campina quando flora A piracema, rios contravim Binho, Bel, Bia, Quim Vamos embora Quando eu morrer Cansado de guerra Morro de bem Com a minha terra: Cana, caqui Inhame, abóbora Onde só vento se semeava outrora Amplidão, nação, sertão sem fim Ó Manuel, Miguilim Vamos embora BUARQUE, C. As cidades. Rio de Janeiro: RCA, 1998 (fragmento). Nesse texto, predomina a função poética da linguagem. Entretanto, a função emotiva pode ser identificada no verso:',
  'options': ['A. “Zanza pra acolá”.',
   'B. “Fim de feira, periferia afora”.',
   'C. “A cidade não mora mais em mim”.',
   'D. "Onde só vento se semeava outrora”.',
   'E. “Ó Manuel, Miguilim”.']},
 {'id': 31,
  'question': 'Era o êxodo da seca de 1898. Uma ressurreição de cemitérios antigos — esqueletos redivivos, com o aspecto terroso e o fedor das covas podres. Os fantasmas estropiados como que iam dançando, de tão trôpegos e trêmulos, num passo arrastado de quem leva as pernas, em vez de ser levado por elas. Andavam devagar, olhando para trás, como quem quer voltar. Não tinham pressa em chegar, porque não sabiam aonde iam. Expulsos de seu paraíso por espadas de fogo, iam, ao acaso, em descaminhos, no arrastão dos maus fados. Fugiam do sol e o sol guiava-os nesse forçado nomadismo. Adelgaçados na magreira cômica, cresciam, como se o vento os levantasse. E os braços afinados desciam-lhes aos joelhos, de mãos abanando. Vinham escoteiros. Menos os hidrópicos — de ascite consecutiva à alimentação tóxica — com os fardos das barrigas alarmantes. Não tinham sexo, nem idade, nem condição nenhuma. Eram os retirantes. Nada mais. ALMEIDA, J. A. A bagaceira. Rio de Janeiro: J. Olympio, 1978. Os recursos composicionais que inserem a obra no chamado “Romance de 30” da literatura brasileira manifestam-se aqui no(a)',
  'options': ['A. Desenho cru da realidade dramática dos retirantes.',
   'B. Indefinição dos espaços para efeito de generalização.',
   'C. Análise psicológica da reação dos personagens à seca.',
   'D. Engajamento político do narrador ante as desigualdades.',
   'E. Contemplação lírica da paisagem transformada em alegoria.']},
 {'id': 34,
  'question': 'Criado há cerca de 20 anos na Califórnia, o mountainboard é um esporte de aventura que utiliza uma espécie de skate off-road para realizar manobras similares às das modalidades de snowboard, surf e do próprio skate. A atividade chegou ao Brasil em 1997 e hoje possui centenas de praticantes, um circuito nacional respeitável e mais de uma dezena de pistas espalhadas pelo país. Segundo consta na história oficial, o mountainboard foi criado por praticantes de snowboard que sentiam falta de praticar o esporte nos períodos sem neve. Para isso, eles desenvolveram um equipamento bem simples: uma prancha semelhante ao modelo utilizado na neve (menor e um pouco menos flexível), com dois eixos bem resistentes, alças para encaixar os pés e quatro pneus com câmaras de ar para regular a velocidade que pode ser alcançada em diferentes condições. Com essa configuração, o esporte se mostrou possível em diversos tipos de terreno: grama, terra, pedras, asfalto e areia. Além desses pisos, também é possível procurar pelas próprias trilhas para treinar as manobras. Disponível em: www.webventure.com.br. Acesso em: 19 jun. 2019. A história da prática do mountainboard representa uma das principais marcas das atividades de aventura, caracterizada pela',
  'options': ['A. Competitividade entre seus praticantes.',
   'B. Atividade com padrões técnicos definidos.',
   'C. Modalidade com regras predeterminadas.',
   'D. Criatividade para adaptações a novos espaços.',
   'E. Necessidade de espaços definidos para a sua realização.']},
 {'id': 11,
  'question': 'Sinhá Se a dona se banhou Eu não estava lá Por Deus Nosso Senhor Eu não olhei Sinhá Estava lá na roça Sou de olhar ninguém Não tenho mais cobiça Nem enxergo bem Para que me pôr no tronco Para que me aleijar Eu juro a vosmecê Que nunca vi Sinhá \\[…\\] Por que talhar meu corpo Eu não olhei Sinhá Para que que vosmincê Meus olhos vai furar Eu choro em iorubá Mas oro por Jesus Para que que vassuncê Me tira a luz. CHICO BUARQUE; JOÃO BOSCO. Chico. Rio de Janeiro: Biscoito Fino, 2011 (fragmento). No fragmento da letra da canção, o vocabulário empregado e a situação retratada são relevantes para o patrimônio linguístico e identitário do país, na medida em que',
  'options': ['A. Remetem à violência física e simbólica contra os povos escravizados.',
   'B. Valorizam as influências da cultura africana sobre a música nacional.',
   'C. Relativizam o sincretismo constitutivo das práticas religiosas brasileiras.',
   'D. Narram os infortúnios da relação amorosa entre membros de classes sociais diferentes.',
   'E. Problematizam as diferentes visões de mundo na sociedade durante o período colonial.']},
 {'id': 17,
  'question': 'A história do futebol brasileiro contém, ao longo de um século, registros de episódios racistas. Eis o paradoxo: se, de um lado, a atividade futebolística era depreciada aos olhos da “boa sociedade” como profissão destinada aos pobres, negros e marginais, de outro, achava-se investida do poder de representar e projetar a nação em escala mundial. A Copa do Mundo no Brasil, em 1950, viria a se constituir, nesse sentido, em uma rara oportunidade. Contudo, na decisão contra o Uruguai sobreveio o inesperado revés. As crônicas esportivas elegiam o goleiro Barbosa e o defensor Bigode como bodes expiatórios, “descarregando nas costas” dos jogadores os “prejuízos” da derrota. Uma chibata moral, eis a a sentença proferida no tribunal do brancos. Nos anos 1970, por não atender às expectativas normativas suscitadas pelo estereótipo do “bom negro”, Paulo César Lima foi classificado como “jogador – problema”. Ele esboçava a revolta da chibata no futebol brasileiro. Enquanto Barbosa e Bigode, sem alternativa suportaram o linchamento moral na derrota 1950, Paulo César contra-atacava os que pretendiam condená-lo pelo insucesso de 1974. O jogador assumia as cores e as causas defendidas pela esquadra dos pretos em todas as esferas da vida social. “Sinto na pele esse racismo subjacente” revelou a imprensa francesa: “Isto é, ninguém ousa pronunciar a palavra ‘racismo’. Mas posso garantir que ele existe, mesmo na seleção Brasileira”. Sua ousadia constituiu em pronunciar a palavra interdita no espaço simbólico do discurso oficial para reafirmar o mito da democracia racial. Disponível em: https: observatorioracialfutebol.com.br. Acesso em: 22 jun. 2019 (adaptado) O texto atribui o enfraquecimento do mito da democracia racial no futebol à',
  'options': ['A. Responsabilização dos jogadores negros pela derrota na final da Copa de 1950.',
   'B. Projeção mundial da nação por um esporte antes destinados aos pobres.',
   'C. Depreciação de um esporte associado a marginalidade.',
   'D. Interdição da palavra "racismo" no contexto esportivo.',
   'E. Atitude contestadora de um "jogador-problema".']},
 {'id': 22,
  'question': 'Os linguistas têm notado a expansão do tratamento informal. “Tenho 78 anos e devia ser tratado por _senhor_, mas meus alunos mais jovens me tratam por _você_“, diz o professor Ataliba Castilho, aparentemente sem se incomodar com a informalidade, inconcebível em seus tempos de estudante. O você, porém, não reinará sozinho. O _tu_ predomina em Porto Alegre e convive com o você no Rio de Janeiro e em Recife, enquanto você é o tratamento predominante em São Paulo, Curitiba, Belo Horizonte e Salvador. O _tu_ já era mais próximo e menos formal que _você_ nas quase 500 cartas do acervo on-line de uma instituição universitária, quase todas de poetas, políticos e outras personalidades do final do século XIX e início do XX. Disponível em: http: revistapesquisa.fapesp.br. Acesso em: 21 abr. 2015 (adaptado). No texto, constata-se que os usos de pronomes variaram ao longo do tempo e que atualmente têm empregos diversos pelas regiões do Brasil. Esse processo revela que',
  'options': ['A. A escolha de "você" ou de "tu" está condicionada à idade da pessoa que usa o pronome.',
   'B. A possibilidade de se usar tanto "tu" quanto "você" caracteriza a diversidade da língua.',
   'C. O pronome "tu" tem sido empregado em situações informais por todo o país.',
   'D. A ocorrência simultânea de "tu" e de "você" evidencia a inexistência da distinção entre níveis de formalidade.',
   'E. O emprego de "você" em documentos escritos demonstra que a língua tende a se manter inalterada.']},
 {'id': 6,
  'question': '_Vou-me embora p’ra Pasárgada_ foi o poema de mais longa gestação em toda a minha obra. Vi pela primeira vez esse nome Pasárgada quando tinha os meus dezesseis anos e foi num a autor grego. \\[…\\] Esse nome de Pasárgada, que significa “campo dos persas” ou “tesouro dos persas”, suscitou na minha imaginação uma paisagem fabulosa, um país de delícias, como o de _L’invitation au Voyage_, de Baudelaire. Mais de vinte anos depois, quando eu morava só na minha casa da Rua do Curvelo, num momento de fundo desânimo, da mais aguda sensação de tudo o que eu não tinha feito em minha vida por motivo da doença, saltou-me de súbito do subconsciente este grito estapafúrdio: “Vou-me embora p’ra Pasárgada!” Senti na redondilha a primeira célula de um poema, e tentei realizá-lo, mas fracassei. Alguns anos depois, em idênticas circunstâncias de desalento e tédio, me ocorreu o mesmo desabafo de evasão da “vida besta”. Desta vez o poema saiu sem esforço como se já estivesse pronto dentro de mim. Gosto desse poema porque vejo nele, em escorço, toda a minha vida; \\[…\\] Não sou arquiteto, como meu pai desejava, não fiz nenhuma casa, mas reconstruí e “não de uma forma imperfeita neste mundo de aparências”, uma cidade ilustre, que hoje não é mais a Pasárgada de Ciro, e sim a “minha” Pasárgada. BANDEIRA, M. Itinerário de Pasárgada. Rio de Janeiro: Nova Fronteira; Brasília: INL, 1984. Os processos de interação comunicativa preveem a presença ativa de múltiplos elementos da comunicação, entre os quais se destacam as funções da linguagem. Nesse fragmento, a função da linguagem predominante é a',
  'options': ['A. Emotiva, porque o poeta expõe os sentimentos de angústia que o levaram à criação poética.',
   'B. Referencial, porque o texto informa sobre a origem do nome empregado em um famoso poema de Bandeira.',
   'C. Metalinguística, porque o poeta tece comentários sobre a gênese e o processo de escrita de um de seus poemas.',
   'D. Poética, porque o texto aborda os elementos estéticos de um dos poemas mais conhecidos de Bandeira.',
   'E. Apelativa, porque o poeta tenta convencer os leitores sobre sua dificuldade de compor um poema.']},
 {'id': 36,
  'question': 'LUTA: prática corporal imprevisível, caracterizada por determinado estado de contato proposital, que possibilita a duas ou mais pessoas se enfrentarem numa constante troca de ações ofensivas e ou defensivas, regidas por regras, com o objetivo mútuo sobre um alvo móvel personificado no oponente. GOMES, M. S. P. _et al_. Ensino das lutas: dos princípios condicionais aos grupos situacionais. Movimento, n. 2, abr.-jun. 2010 (adaptado). De acordo com o texto, podemos identificar uma abordagem das lutas nas aulas de educação física quando o professor realiza uma proposta envolvendo',
  'options': ['A. Contato corporal intenso entre o aluno e seu oponente.',
   'B. Contenda entre os alunos que se agridem fisicamente.',
   'C. Confronto corporal em que os vencedores são previamente identificados.',
   'D. Combate corporal intencional com ações regulamentadas entre os oponentes.',
   'E. Conflito resolvido pelos alunos por meio de regras previamente estabelecidas.']},
 {'id': 43,
  'question': 'Quando quis agilizar o processo de seleção de novos alunos, a tradicional faculdade britânica de medicina St. George usou um software para definir quem deveria ser entrevistado. Ao reproduzir a forma como os funcionários faziam essa escolha, o programa eliminou, de cara, 60 de 2.000 candidatos. Só por causa do sexo ou da origem racial, numa dedução baseada em sobrenome e local de nascimento. Um estudo sobre o caso foi publicado em 1988, mas, 25 anos depois, outra pesquisa apontou que esse tipo de discriminação segue firme. O exemplo recente envolve o buscador do Google: ao digitar nomes comuns entre negros dos EUA, a chance de os anúncios automáticos oferecerem checagem de antecedentes criminais pode aumentar 25%. E pode piorar com a pergunta “detido?” logo após a palavra procurada. Disponível em: https: tab.uol.com.br. _Acesso em: 11 ago. 2017 (adaptado)._ O texto permite o desnudamento da sociedade ao relacionar as tecnologias de informação e comunicação com o(a)',
  'options': ['A. Agilidade dos softwares.',
   'B. Passar dos anos.',
   'C. Linguagem.',
   'D. Preconceito.',
   'E. Educação.']}]

In [91]:
print(len(dataset_final))  # deve dar 12

12

In [92]:
exportar_json(dataset_final, r"D:\ODG\outputs n8n\API Response\datasets\questoes_teste.json")