In [2]:
import json
import pandas as pd

In [3]:
def classificar_theta(theta, limiar):
    if theta <= -limiar:
        return "baixa"
    elif -limiar < theta <= limiar:
        return "media"
    else:
        return "alta"

limiares = [0.5, 1, 1.5]

resultados = {}

Prompt 2 -  Heurístico comportamental com saída binária

In [4]:
path = r"D:\ODG\outputs n8n\Prompt 2 (Green)\Prompt 2 em Lotes + ID.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

### Prompt Green

In [5]:
df = pd.json_normalize(data)
df

,output.id_questao,output.id_lote,output.param_b,output.students
0,38,1,-0.5,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,38,2,0.5,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,38,3,-0.5,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,38,4,-0.5,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
4,38,5,0.2,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,38,6,-0.5,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,38,7,-0.5,"[{'theta': -0.3731, 'score': 1}, {'theta': -0...."
7,38,8,0.2,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,38,9,0.2,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
9,38,10,-0.5,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
10,38,11,0.5,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,38,12,-0.5,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,38,13,-0.5,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,38,14,0.2,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,38,15,-0.5,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
15,38,16,0.2,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,38,17,-0.5,"[{'theta': -0.7277, 'score': 1}, {'theta': 0.8..."
17,38,18,0.2,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,38,19,0.3,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
19,38,20,-0.5,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."

In [6]:
df_students = df.explode("output.students")

df_students["theta"] = df_students["output.students"].apply(lambda x: x["theta"])
df_students["score"] = df_students["output.students"].apply(lambda x: x["score"])
df_students

,output.id_questao,output.id_lote,output.param_b,output.students,theta,score
0,38,1,-0.5,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,38,1,-0.5,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,38,1,-0.5,"{'theta': 1.13, 'score': 1}",1.1300,1
0,38,1,-0.5,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,38,1,-0.5,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...
19,38,20,-0.5,"{'theta': -1.2313, 'score': 0}",-1.2313,0
19,38,20,-0.5,"{'theta': 0.5584, 'score': 1}",0.5584,1
19,38,20,-0.5,"{'theta': -1.0786, 'score': 0}",-1.0786,0
19,38,20,-0.5,"{'theta': -0.8033, 'score': 0}",-0.8033,0
19,38,20,-0.5,"{'theta': 0.0752, 'score': 1}",0.0752,1

In [ ]:
for limiar in limiares:
    
    df_temp = df_students.copy()
    
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))
    
    resumo = (
        df_temp
        .groupby(["output.id_questao", "grupo"])["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
    )
    
    resultados[limiar] = resumo

In [8]:
for limiar, tabela in resultados.items():
    print(f"\n===== LIMIAR: {limiar} =====")
    print(tabela)

===== LIMIAR: 0.5 =====
   output.id_questao  grupo  count  taxa_acerto
0                 38   alta    311     1.000000
1                 38  baixa    295     0.033898
2                 38  media    394     0.690355

===== LIMIAR: 1 =====
   output.id_questao  grupo  count  taxa_acerto
0                 38   alta    137      1.00000
1                 38  baixa    171      0.00000
2                 38  media    692      0.65896

===== LIMIAR: 1.5 =====
   output.id_questao  grupo  count  taxa_acerto
0                 38   alta     56     1.000000
1                 38  baixa     64     0.000000
2                 38  media    880     0.610227

### 3 questões com os limiares

In [5]:
path = r"D:\ODG\outputs n8n\Prompt 2 (Green)\Prompt 2 - Questões 9 35 38.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

In [6]:
questoes = pd.json_normalize(data)
questoes

,output.id_questao,output.id_lote,output.param_b,output.students
0,9,1,-0.5,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,9,2,0.5,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,9,3,-0.5,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,9,4,-0.5,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
4,9,5,0.2,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,9,6,0.2,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,9,7,0.5,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
7,9,8,-0.5,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,9,9,0.2,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
9,9,10,-0.5,"[{'theta': -0.8777, 'score': 1}, {'theta': 0.8..."
10,9,11,-0.5,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,9,12,-0.5,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,9,13,-0.5,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,9,14,0.3,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,9,15,-0.5,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
15,9,16,0.8,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,9,17,0.5,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
17,9,18,0.3,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,9,19,-0.5,"[{'theta': -0.6442, 'score': 1}, {'theta': 1.8..."
19,9,20,0.5,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."
20,35,1,0.2,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
21,35,2,0.5,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
22,35,3,0.2,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
23,35,4,0.2,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
24,35,5,0.5,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
25,35,6,-0.5,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
26,35,7,-0.5,"[{'theta': -0.3731, 'score': 1}, {'theta': -0...."
27,35,8,-0.5,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
28,35,9,0.5,"[{'theta': 0.4345, 'score': 0}, {'theta': 0.85..."
29,35,10,-0.5,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
30,35,11,0.2,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
31,35,12,0.5,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
32,35,13,0.3,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
33,35,14,-0.5,"[{'theta': -0.2913, 'score': 1}, {'theta': -1...."
34,35,15,-0.5,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
35,35,16,0.5,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
36,35,17,0.2,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
37,35,18,-0.5,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
38,35,19,-0.5,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
39,35,20,-0.5,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."
40,38,1,-0.5,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
41,38,2,0.2,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
42,38,3,-0.5,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
43,38,4,0.5,"[{'theta': 0.2254, 'score': 0}, {'theta': -1.2..."
44,38,5,-0.5,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
45,38,6,-0.5,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
46,38,7,-0.5,"[{'theta': -0.3731, 'score': 1}, {'theta': -0...."
47,38,8,0.5,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
48,38,9,0.5,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
49,38,10,-0.5,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
50,38,11,0.3,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
51,38,12,-0.5,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
52,38,13,-0.5,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
53,38,14,0.2,"[{'theta': -0.2913, 'score': 1}, {'theta': -1...."
54,38,15,-0.5,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
55,38,16,0.5,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
56,38,17,-0.5,"[{'theta': -0.7277, 'score': 1}, {'theta': 0.8..."
57,38,18,-0.5,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
58,38,19,-0.5,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
59,38,20,-0.5,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."

In [7]:
questoes_3 = questoes.explode("output.students")

questoes_3["theta"] = questoes_3["output.students"].apply(lambda x: x["theta"])
questoes_3["score"] = questoes_3["output.students"].apply(lambda x: x["score"])

#df_students = df_students.drop(columns=["students"])
questoes_3

,output.id_questao,output.id_lote,output.param_b,output.students,theta,score
0,9,1,-0.5,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,9,1,-0.5,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,9,1,-0.5,"{'theta': 1.13, 'score': 1}",1.1300,1
0,9,1,-0.5,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,9,1,-0.5,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...
59,38,20,-0.5,"{'theta': -1.2313, 'score': 0}",-1.2313,0
59,38,20,-0.5,"{'theta': 0.5584, 'score': 1}",0.5584,1
59,38,20,-0.5,"{'theta': -1.0786, 'score': 0}",-1.0786,0
59,38,20,-0.5,"{'theta': -0.8033, 'score': 0}",-0.8033,0
59,38,20,-0.5,"{'theta': 0.0752, 'score': 1}",0.0752,1

In [ ]:
def classificar_theta(theta, limiar):
    if theta <= -limiar:
        return "baixa"
    elif -limiar < theta <= limiar:
        return "media"
    else:
        return "alta"


limiares = [0.5, 1, 1.5]

ordem_grupos = ["baixa", "media", "alta"]
ordem_questoes = ["fácil", "média", "difícil"]

# 🔥 MAPEAMENTO DAS QUESTÕES (AJUSTE CONFORME NECESSÁRIO)
mapa_questoes = {
    35: "fácil",
    38: "média",
    9: "difícil"
}

resultados = {}

for limiar in limiares:

    df_temp = questoes_3.copy()
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))

    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )

    df_temp["nivel_questao"] = df_temp["output.id_questao"].map(mapa_questoes)

    df_temp["nivel_questao"] = pd.Categorical(
        df_temp["nivel_questao"],
        categories=ordem_questoes,
        ordered=True
    )

    resumo = (
        df_temp
        .groupby(["nivel_questao", "output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["nivel_questao", "output.id_questao", "grupo"])
    )

    resultados[limiar] = resumo

In [ ]:
for limiar, tabela in resultados.items():

    print(f"\n ===== PIVOT LIMIAR {limiar} =====")

    pivot = tabela.pivot(
        index="grupo",
        columns=["nivel_questao", "output.id_questao"],
        values="taxa_acerto"
    )

    print(pivot)
    
#esse foi legalzinho

 ===== PIVOT LIMIAR 0.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.003390  0.054237  0.054237
media              0.581218  0.675127  0.601523
alta               0.996785  1.000000  0.993569

 ===== PIVOT LIMIAR 1 =====
nivel_questao        fácil    média   difícil
output.id_questao       35       38        9
grupo
baixa              0.00000  0.00000  0.000000
media              0.58237  0.65896  0.614162
alta               1.00000  1.00000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
nivel_questao     fácil     média difícil
output.id_questao    35        38      9
grupo
baixa              0.00  0.000000   0.000
media              0.55  0.610227   0.575
alta               1.00  1.000000   1.000

questão 35 = fácil (-0.27647)

questão 38 = média (0.00914)


questão 9 = difícil (1.60103)

#### Green Reasoner

In [12]:
green_reasoner = r"D:\ODG\outputs n8n\Prompt 2 (Green)\Prompt 2 - Reasoner.json"
with open(green_reasoner, "r", encoding="utf-8") as f:
    data_green_reasoner = json.load(f)
    
green_df = pd.json_normalize(data_green_reasoner)
#green_df
green_reasoner_students = green_df.explode("output.students")

green_reasoner_students["theta"] = green_reasoner_students["output.students"].apply(lambda x: x["theta"])
green_reasoner_students["score"] = green_reasoner_students["output.students"].apply(lambda x: x["score"])
green_reasoner_students

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students,theta,score
0,9,1,0.3,compreender,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,9,1,0.3,compreender,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,9,1,0.3,compreender,"{'theta': 1.13, 'score': 1}",1.1300,1
0,9,1,0.3,compreender,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,9,1,0.3,compreender,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...,...
59,38,20,0.0,compreender,"{'theta': -1.2313, 'score': 0}",-1.2313,0
59,38,20,0.0,compreender,"{'theta': 0.5584, 'score': 1}",0.5584,1
59,38,20,0.0,compreender,"{'theta': -1.0786, 'score': 1}",-1.0786,1
59,38,20,0.0,compreender,"{'theta': -0.8033, 'score': 0}",-0.8033,0
59,38,20,0.0,compreender,"{'theta': 0.0752, 'score': 1}",0.0752,1

In [10]:
for limiar in limiares:
    
    df_temp = green_reasoner_students.copy()
    
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))
    
    # DEFINE COMO CATEGORIA ORDENADA
    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )
    
    resumo = (
        df_temp
        .groupby(["output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["output.id_questao", "grupo"]) 
    )
    
    resultados[limiar] = resumo
    
for limiar, tabela in resultados.items():
    
    print(f"\n==============================")
    print(f"LIMIAR: {limiar}")
    print(f"==============================")
    
    for questao in tabela["output.id_questao"].unique():
        
        print(f"\nQuestão {questao}")
        
        temp = tabela[tabela["output.id_questao"] == questao]
        print(temp)

==============================
LIMIAR: 0.5
==============================

Questão 9
   output.id_questao  grupo  count  taxa_acerto
0                  9  baixa    295     0.206780
1                  9  media    394     0.715736
2                  9   alta    311     0.842444

Questão 35
   output.id_questao  grupo  count  taxa_acerto
3                 35  baixa    295     0.223729
4                 35  media    394     0.763959
5                 35   alta    311     0.842444

Questão 38
   output.id_questao  grupo  count  taxa_acerto
6                 38  baixa    295     0.193220
7                 38  media    394     0.672589
8                 38   alta    311     0.884244

==============================
LIMIAR: 1
==============================

Questão 9
   output.id_questao  grupo  count  taxa_acerto
0                  9  baixa    171     0.192982
1                  9  media    692     0.637283
2                  9   alta    137     0.956204

Questão 35
   output.id_questao  grupo  count  taxa_acerto
3                 35  baixa    171     0.245614
4                 35  media    692     0.656069
5                 35   alta    137     0.970803

Questão 38
   output.id_questao  grupo  count  taxa_acerto
6                 38  baixa    171     0.216374
7                 38  media    692     0.619942
8                 38   alta    137     0.956204

==============================
LIMIAR: 1.5
==============================

Questão 9
   output.id_questao  grupo  count  taxa_acerto
0                  9  baixa     64     0.125000
1                  9  media    880     0.618182
2                  9   alta     56     0.946429

Questão 35
   output.id_questao  grupo  count  taxa_acerto
3                 35  baixa     64     0.156250
4                 35  media    880     0.642045
5                 35   alta     56     0.964286

Questão 38
   output.id_questao  grupo  count  taxa_acerto
6                 38  baixa     64     0.125000
7                 38  media    880     0.606818
8                 38   alta     56     0.982143

In [11]:
for limiar, tabela in resultados.items():
    
    print(f"\n ===== PIVOT LIMIAR {limiar} =====")
    
    pivot = tabela.pivot(
        index="grupo",
        columns="output.id_questao",
        values="taxa_acerto"
    )
    
    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
output.id_questao        9         35        38
grupo
baixa              0.206780  0.223729  0.193220
media              0.715736  0.763959  0.672589
alta               0.842444  0.842444  0.884244

 ===== PIVOT LIMIAR 1 =====
output.id_questao        9         35        38
grupo
baixa              0.192982  0.245614  0.216374
media              0.637283  0.656069  0.619942
alta               0.956204  0.970803  0.956204

 ===== PIVOT LIMIAR 1.5 =====
output.id_questao        9         35        38
grupo
baixa              0.125000  0.156250  0.125000
media              0.618182  0.642045  0.606818
alta               0.946429  0.964286  0.982143

### Prompt Yellow

In [13]:
yellow_patch = r"D:\ODG\outputs n8n\Prompt 3 (Yellow)\Prompt Yellow - rodada 3 (com theta).json"

with open(yellow_patch, "r", encoding="utf-8") as f:
    data_yellow = json.load(f)
    
df_yellow = pd.json_normalize(data_yellow)
df_yellow

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students
0,9,1,-0.30,compreender,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,9,2,0.40,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,9,3,-0.50,compreender,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,9,4,-0.45,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
4,9,5,0.35,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,9,6,-0.50,compreender,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,9,7,-0.50,compreender,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
7,9,8,0.40,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,9,9,0.40,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
9,9,10,-0.50,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
10,9,11,-0.50,compreender,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,9,12,-0.50,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,9,13,-0.50,compreender,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,9,14,0.20,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,9,15,0.15,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
15,9,16,0.40,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,9,17,0.25,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
17,9,18,-0.50,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,9,19,-0.50,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
19,9,20,-0.50,compreender,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."
20,35,1,-0.50,compreender,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
21,35,2,0.40,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
22,35,3,-0.50,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
23,35,4,0.25,analisar,"[{'theta': 0.2254, 'score': 0}, {'theta': -1.2..."
24,35,5,-0.20,compreender,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
25,35,6,-0.30,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
26,35,7,-0.50,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
27,35,8,0.20,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
28,35,9,0.40,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
29,35,10,0.15,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
30,35,11,-0.50,compreender,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
31,35,12,-0.50,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
32,35,13,0.30,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
33,35,14,-0.50,compreender,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
34,35,15,-0.50,analisar,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
35,35,16,0.40,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
36,35,17,-0.50,compreender,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
37,35,18,-0.50,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
38,35,19,-0.30,compreender,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
39,35,20,-0.50,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."
40,38,1,-0.40,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
41,38,2,-0.80,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
42,38,3,-0.50,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
43,38,4,-0.50,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
44,38,5,-0.50,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
45,38,6,-0.50,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
46,38,7,-0.50,analisar,"[{'theta': -0.3731, 'score': 1}, {'theta': -0...."
47,38,8,-0.50,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
48,38,9,-0.80,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
49,38,10,-0.50,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
50,38,11,-0.50,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
51,38,12,-0.50,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
52,38,13,0.20,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
53,38,14,0.20,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
54,38,15,0.40,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
55,38,16,0.50,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
56,38,17,-0.50,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
57,38,18,-0.50,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
58,38,19,-0.20,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
59,38,20,-0.50,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."

In [14]:
yellow_students = df_yellow.explode("output.students")

yellow_students["theta"] = yellow_students["output.students"].apply(lambda x: x["theta"])
yellow_students["score"] = yellow_students["output.students"].apply(lambda x: x["score"])
yellow_students

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students,theta,score
0,9,1,-0.3,compreender,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,9,1,-0.3,compreender,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,9,1,-0.3,compreender,"{'theta': 1.13, 'score': 1}",1.1300,1
0,9,1,-0.3,compreender,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,9,1,-0.3,compreender,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...,...
59,38,20,-0.5,analisar,"{'theta': -1.2313, 'score': 0}",-1.2313,0
59,38,20,-0.5,analisar,"{'theta': 0.5584, 'score': 1}",0.5584,1
59,38,20,-0.5,analisar,"{'theta': -1.0786, 'score': 0}",-1.0786,0
59,38,20,-0.5,analisar,"{'theta': -0.8033, 'score': 0}",-0.8033,0
59,38,20,-0.5,analisar,"{'theta': 0.0752, 'score': 0}",0.0752,0

In [ ]:
def classificar_theta(theta, limiar):
    if theta <= -limiar:
        return "baixa"
    elif -limiar < theta <= limiar:
        return "media"
    else:
        return "alta"

limiares = [0.5, 1, 1.5]

ordem_grupos = ["baixa", "media", "alta"]

resultados = {}

for limiar in limiares:

    df_temp = yellow_students.copy()
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))

    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )
    df_temp["nivel_questao"] = df_temp["output.id_questao"].map(mapa_questoes)

    df_temp["nivel_questao"] = pd.Categorical(
        df_temp["nivel_questao"],
        categories=ordem_questoes,
        ordered=True
    )
    resumo = (
        df_temp
        .groupby(["nivel_questao", "output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["nivel_questao", "output.id_questao", "grupo"])
    )

    resultados[limiar] = resumo

In [ ]:
for limiar, tabela in resultados.items():

    print(f"\n ===== PIVOT LIMIAR {limiar} =====")

    pivot = tabela.pivot(
        index="grupo",
        columns=["nivel_questao", "output.id_questao"],
        values="taxa_acerto"
    )

    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.030508  0.027119  0.027119
media              0.540609  0.700508  0.626904
alta               1.000000  1.000000  1.000000

 ===== PIVOT LIMIAR 1 =====
nivel_questao         fácil    média   difícil
output.id_questao        35       38        9
grupo
baixa              0.000000  0.00000  0.000000
media              0.572254  0.66185  0.619942
alta               1.000000  1.00000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
nivel_questao         fácil   média   difícil
output.id_questao        35      38        9
grupo
baixa              0.000000  0.0000  0.000000
media              0.542045  0.6125  0.579545
alta               1.000000  1.0000  1.000000

In [10]:
#questão 35 = fácil (-0.27647)
#questão 38 = média (0.00914)
#questão 9 = difícil (1.60103)

### Prompt Blue

In [19]:
blue_path = r"D:\ODG\outputs n8n\Prompt 4 (Blue)\Prompt Blue.json"

with open(blue_path, "r", encoding="utf-8") as f:
    data_blue = json.load(f)
    
df_blue = pd.json_normalize(data_blue)
df_blue

,output.id_questao,output.id_lote,output.param_a,output.param_b,output.bloom,output.students
0,9,1,1,-0.2,compreender,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,9,2,1,-0.5,compreender,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,9,3,1,-0.5,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,9,4,1,-0.2,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
4,9,5,1,-0.2,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,9,6,1,-0.5,compreender,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,9,7,1,-0.2,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
7,9,8,1,-0.5,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,9,9,1,0.5,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
9,9,10,1,-0.2,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
10,9,11,1,-0.5,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,9,12,1,-0.5,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,9,13,1,-0.5,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,9,14,1,-0.5,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,9,15,1,-0.5,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
15,9,16,1,0.2,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,9,17,1,-0.5,compreender,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
17,9,18,1,-0.5,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,9,19,1,-0.5,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
19,9,20,1,-0.2,analisar,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."
20,35,1,1,-0.5,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
21,35,2,1,0.5,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
22,35,3,1,-0.5,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
23,35,4,1,0.2,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
24,35,5,1,-0.3,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
25,35,6,1,-0.5,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
26,35,7,1,-0.5,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
27,35,8,1,-0.5,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
28,35,9,1,0.5,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
29,35,10,1,-0.5,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
30,35,11,1,0.3,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
31,35,12,1,-0.5,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
32,35,13,1,-0.5,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
33,35,14,1,-0.5,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
34,35,15,1,-0.5,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
35,35,16,1,-0.5,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
36,35,17,1,-0.2,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
37,35,18,1,-0.5,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
38,35,19,1,-0.5,compreender,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
39,35,20,1,-0.2,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."
40,38,1,1,-0.5,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
41,38,2,1,-0.2,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
42,38,3,1,-0.5,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
43,38,4,1,-0.5,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
44,38,5,1,-0.2,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
45,38,6,1,-0.5,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
46,38,7,1,-0.3,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
47,38,8,1,-0.5,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
48,38,9,1,-0.5,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
49,38,10,1,-0.3,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
50,38,11,1,-0.5,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
51,38,12,1,-0.5,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
52,38,13,1,-0.5,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
53,38,14,1,-0.5,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
54,38,15,1,0.5,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
55,38,16,1,0.5,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
56,38,17,1,0.2,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
57,38,18,1,-0.5,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
58,38,19,1,-0.5,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
59,38,20,1,-0.3,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."

In [15]:
df_blue["output.param_b"].value_counts()

output.param_b
-0.5    37
-0.2    10
 0.5     5
-0.3     4
 0.2     3
 0.3     1
Name: count, dtype: int64

In [14]:
df_blue["output.param_b"].describe()

count    60.000000
mean     -0.305000
std       0.315919
min      -0.500000
25%      -0.500000
50%      -0.500000
75%      -0.200000
max       0.500000
Name: output.param_b, dtype: float64

In [20]:
blue_students = df_blue.explode("output.students")
blue_students["theta"] = blue_students["output.students"].apply(lambda x: x["theta"])
blue_students["score"] = blue_students["output.students"].apply(lambda x: x["score"])
blue_students

,output.id_questao,output.id_lote,output.param_a,output.param_b,output.bloom,output.students,theta,score
0,9,1,1,-0.2,compreender,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,9,1,1,-0.2,compreender,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,9,1,1,-0.2,compreender,"{'theta': 1.13, 'score': 1}",1.1300,1
0,9,1,1,-0.2,compreender,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,9,1,1,-0.2,compreender,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...,...,...
59,38,20,1,-0.3,analisar,"{'theta': -1.2313, 'score': 0}",-1.2313,0
59,38,20,1,-0.3,analisar,"{'theta': 0.5584, 'score': 1}",0.5584,1
59,38,20,1,-0.3,analisar,"{'theta': -1.0786, 'score': 0}",-1.0786,0
59,38,20,1,-0.3,analisar,"{'theta': -0.8033, 'score': 0}",-0.8033,0
59,38,20,1,-0.3,analisar,"{'theta': 0.0752, 'score': 0}",0.0752,0

In [21]:
for limiar in limiares:

    df_temp = blue_students.copy()

    # ---------------------------
    # CLASSIFICAÇÃO DOS ALUNOS
    # ---------------------------
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))

    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )

    # ---------------------------
    # CLASSIFICAÇÃO DAS QUESTÕES
    # ---------------------------
    df_temp["nivel_questao"] = df_temp["output.id_questao"].map(mapa_questoes)

    df_temp["nivel_questao"] = pd.Categorical(
        df_temp["nivel_questao"],
        categories=ordem_questoes,
        ordered=True
    )

    # ---------------------------
    # AGRUPAMENTO
    # ---------------------------
    resumo = (
        df_temp
        .groupby(["nivel_questao", "output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["nivel_questao", "output.id_questao", "grupo"])
    )

    resultados[limiar] = resumo

In [22]:
for limiar, tabela in resultados.items():

    print(f"\n ===== PIVOT LIMIAR {limiar} =====")

    pivot = tabela.pivot(
        index="grupo",
        columns=["nivel_questao", "output.id_questao"],
        values="taxa_acerto"
    )

    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.016949  0.020339  0.044068
media              0.578680  0.611675  0.517766
alta               1.000000  0.996785  0.996785

 ===== PIVOT LIMIAR 1 =====
nivel_questao        fácil     média   difícil
output.id_questao       35        38        9
grupo
baixa              0.00000  0.000000  0.000000
media              0.58815  0.606936  0.563584
alta               1.00000  1.000000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.000000  0.000000  0.000000
media              0.554545  0.569318  0.535227
alta               1.000000  1.000000  1.000000

### Prompt GPT

In [48]:
english_path = r"D:\ODG\outputs n8n\Prompt Blue - English.json"

with open(english_path, "r", encoding="utf-8") as f:
    data_eng = json.load(f)
    
df_eng = pd.json_normalize(data_eng)
df_eng

eng_students = df_eng.explode("output.students")
eng_students["theta"] = eng_students["output.students"].apply(lambda x: x["theta"])
eng_students["score"] = eng_students["output.students"].apply(lambda x: x["score"])
eng_students

for limiar in limiares:
    
    df_temp = eng_students.copy()
    
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))
    
    # DEFINE COMO CATEGORIA ORDENADA
    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )
    
    resumo = (
        df_temp
        .groupby(["output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["output.id_questao", "grupo"]) 
    )
    
    resultados[limiar] = resumo

In [51]:
df_eng

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students
0,26,1,0.8,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,26,2,0.4,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,26,3,0.4,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,26,4,1.2,analisar,"[{'theta': 0.2254, 'score': 0}, {'theta': -1.2..."
4,26,5,0.8,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,26,6,0.8,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,26,7,0.8,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
7,26,8,0.8,avaliar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,26,9,0.8,analisar,"[{'theta': 0.4345, 'score': 0}, {'theta': 0.85..."
9,26,10,0.8,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
10,26,11,0.8,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,26,12,0.8,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,26,13,0.4,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,26,14,0.4,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,26,15,0.8,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
15,26,16,0.8,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,26,17,0.8,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
17,26,18,0.8,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,26,19,0.8,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
19,26,20,0.4,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."
20,35,1,0.4,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
21,35,2,0.4,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
22,35,3,0.2,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
23,35,4,0.4,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
24,35,5,0.4,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
25,35,6,0.4,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
26,35,7,0.4,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
27,35,8,-0.3,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
28,35,9,0.4,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
29,35,10,0.2,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
30,35,11,0.3,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
31,35,12,-0.5,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
32,35,13,0.2,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
33,35,14,0.4,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
34,35,15,0.4,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
35,35,16,0.3,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
36,35,17,0.4,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
37,35,18,-0.3,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
38,35,19,0.2,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
39,35,20,0.2,analisar,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."
40,38,1,0.4,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
41,38,2,0.4,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
42,38,3,0.2,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
43,38,4,0.4,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
44,38,5,0.3,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
45,38,6,0.2,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
46,38,7,0.2,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
47,38,8,0.2,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
48,38,9,0.3,analisar,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
49,38,10,0.4,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
50,38,11,0.4,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
51,38,12,0.3,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
52,38,13,0.2,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
53,38,14,0.4,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
54,38,15,0.2,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
55,38,16,0.4,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
56,38,17,0.2,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
57,38,18,0.3,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
58,38,19,0.2,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
59,38,20,0.4,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."

In [50]:
for limiar, tabela in resultados.items():
    
    print(f"\n ===== PIVOT LIMIAR {limiar} =====")
    
    pivot = tabela.pivot(
        index="grupo",
        columns="output.id_questao",
        values="taxa_acerto"
    )
    
    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.000000
media              0.025381  0.230964  0.213198
alta               0.922830  0.996785  1.000000

 ===== PIVOT LIMIAR 1 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.000000
media              0.231214  0.381503  0.372832
alta               1.000000  1.000000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.000000
media              0.273864  0.392045  0.385227
alta               1.000000  1.000000  1.000000

### Prompt Gemini

In [23]:
red_path = r"D:\ODG\outputs n8n\Prompt 0 1.json"

with open(red_path, "r", encoding="utf-8") as f:
    data_red = json.load(f)
    
df_red = pd.json_normalize(data_red)
df_red

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students
0,26,1,0.8,analisar,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
1,26,2,0.8,analisar,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
2,26,3,0.8,analisar,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
3,26,4,0.8,analisar,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
4,26,5,0.8,analisar,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
5,26,6,0.8,analisar,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
6,26,7,0.8,analisar,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
7,26,8,0.8,analisar,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
8,26,9,0.8,analisar,"[{'theta': 0.4345, 'score': 0}, {'theta': 0.85..."
9,26,10,0.8,analisar,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
10,26,11,0.8,analisar,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
11,26,12,0.8,analisar,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
12,26,13,0.8,analisar,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
13,26,14,0.8,analisar,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
14,26,15,0.8,analisar,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
15,26,16,0.8,analisar,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
16,26,17,0.8,analisar,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
17,26,18,0.8,analisar,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
18,26,19,0.8,analisar,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
19,26,20,0.8,analisar,"[{'theta': 0.0322, 'score': 0}, {'theta': -1.6..."
20,35,1,-0.5,compreender,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
21,35,2,0.2,compreender,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
22,35,3,0.2,compreender,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
23,35,4,0.5,compreender,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
24,35,5,0.2,compreender,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
25,35,6,0.3,compreender,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
26,35,7,0.2,compreender,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
27,35,8,0.5,compreender,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
28,35,9,0.7,compreender,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
29,35,10,0.2,compreender,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
30,35,11,0.2,compreender,"[{'theta': -0.8666, 'score': 0}, {'theta': 0.7..."
31,35,12,0.5,compreender,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
32,35,13,0.2,compreender,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
33,35,14,0.5,compreender,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
34,35,15,0.3,compreender,"[{'theta': -0.2137, 'score': 1}, {'theta': -0...."
35,35,16,0.8,compreender,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
36,35,17,0.2,compreender,"[{'theta': -0.7277, 'score': 0}, {'theta': 0.8..."
37,35,18,0.2,compreender,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
38,35,19,0.2,compreender,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
39,35,20,0.4,compreender,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."
40,38,1,0.2,compreender,"[{'theta': 1.0236, 'score': 1}, {'theta': 1.58..."
41,38,2,0.5,compreender,"[{'theta': 0.7678, 'score': 1}, {'theta': 0.56..."
42,38,3,-0.5,compreender,"[{'theta': 1.2135, 'score': 1}, {'theta': -1.6..."
43,38,4,-0.5,compreender,"[{'theta': 0.2254, 'score': 1}, {'theta': -1.2..."
44,38,5,0.2,compreender,"[{'theta': 1.2388, 'score': 1}, {'theta': -0.9..."
45,38,6,-0.5,compreender,"[{'theta': 0.6724, 'score': 1}, {'theta': -0.3..."
46,38,7,0.2,compreender,"[{'theta': -0.3731, 'score': 0}, {'theta': -0...."
47,38,8,0.2,compreender,"[{'theta': 0.7969, 'score': 1}, {'theta': 0.10..."
48,38,9,0.7,compreender,"[{'theta': 0.4345, 'score': 1}, {'theta': 0.85..."
49,38,10,0.2,compreender,"[{'theta': -0.8777, 'score': 0}, {'theta': 0.8..."
50,38,11,-0.5,compreender,"[{'theta': -0.8666, 'score': 1}, {'theta': 0.7..."
51,38,12,-0.5,compreender,"[{'theta': -1.6416, 'score': 0}, {'theta': 1.6..."
52,38,13,0.2,compreender,"[{'theta': -1.116, 'score': 0}, {'theta': 0.93..."
53,38,14,0.2,compreender,"[{'theta': -0.2913, 'score': 0}, {'theta': -1...."
54,38,15,0.2,compreender,"[{'theta': -0.2137, 'score': 0}, {'theta': -0...."
55,38,16,0.8,compreender,"[{'theta': 1.2254, 'score': 1}, {'theta': 1.32..."
56,38,17,-0.5,compreender,"[{'theta': -0.7277, 'score': 1}, {'theta': 0.8..."
57,38,18,-0.5,compreender,"[{'theta': -1.6366, 'score': 0}, {'theta': -0...."
58,38,19,0.2,compreender,"[{'theta': -0.6442, 'score': 0}, {'theta': 1.8..."
59,38,20,-0.5,compreender,"[{'theta': 0.0322, 'score': 1}, {'theta': -1.6..."

In [24]:
red_students = df_red.explode("output.students")
red_students["theta"] = red_students["output.students"].apply(lambda x: x["theta"])
red_students["score"] = red_students["output.students"].apply(lambda x: x["score"])
red_students

,output.id_questao,output.id_lote,output.param_b,output.bloom,output.students,theta,score
0,26,1,0.8,analisar,"{'theta': 1.0236, 'score': 1}",1.0236,1
0,26,1,0.8,analisar,"{'theta': 1.5824, 'score': 1}",1.5824,1
0,26,1,0.8,analisar,"{'theta': 1.13, 'score': 1}",1.1300,1
0,26,1,0.8,analisar,"{'theta': -1.6523, 'score': 0}",-1.6523,0
0,26,1,0.8,analisar,"{'theta': -0.8765, 'score': 0}",-0.8765,0
...,...,...,...,...,...,...,...
59,38,20,-0.5,compreender,"{'theta': -1.2313, 'score': 0}",-1.2313,0
59,38,20,-0.5,compreender,"{'theta': 0.5584, 'score': 1}",0.5584,1
59,38,20,-0.5,compreender,"{'theta': -1.0786, 'score': 0}",-1.0786,0
59,38,20,-0.5,compreender,"{'theta': -0.8033, 'score': 0}",-0.8033,0
59,38,20,-0.5,compreender,"{'theta': 0.0752, 'score': 1}",0.0752,1

In [25]:
for limiar in limiares:
    
    df_temp = red_students.copy()
    
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))
    
    # DEFINE COMO CATEGORIA ORDENADA
    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )
    
    resumo = (
        df_temp
        .groupby(["output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["output.id_questao", "grupo"]) 
    )
    
    resultados[limiar] = resumo

for limiar, tabela in resultados.items():
    
    print(f"\n ===== PIVOT LIMIAR {limiar} =====")
    
    pivot = tabela.pivot(
        index="grupo",
        columns="output.id_questao",
        values="taxa_acerto"
    )
    
    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.135593
media              0.055838  0.291878  0.538071
alta               0.964630  0.990354  0.996785

 ===== PIVOT LIMIAR 1 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.093567
media              0.267341  0.413295  0.591040
alta               1.000000  1.000000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
output.id_questao        26        35        38
grupo
baixa              0.000000  0.000000  0.015625
media              0.302273  0.417045  0.573864
alta               1.000000  1.000000  1.000000

### Teste Score-Based

In [31]:
#score_path = r"D:\ODG\outputs n8n\Prompt Score-Based.json"
score_path = r"D:\ODG\outputs n8n\Prompt Novo teste1.json"

with open(score_path, "r", encoding="utf-8") as f:
    data_score = json.load(f)
    
df_score = pd.json_normalize(data_score)

score_students = df_score.explode("output.students")
score_students["theta"] = score_students["output.students"].apply(lambda x: x["theta"])
score_students["score"] = score_students["output.students"].apply(lambda x: x["score"])
score_students

for limiar in limiares:

    df_temp = blue_students.copy()

    # ---------------------------
    # CLASSIFICAÇÃO DOS ALUNOS
    # ---------------------------
    df_temp["grupo"] = df_temp["theta"].apply(lambda x: classificar_theta(x, limiar))

    df_temp["grupo"] = pd.Categorical(
        df_temp["grupo"],
        categories=ordem_grupos,
        ordered=True
    )

    # ---------------------------
    # CLASSIFICAÇÃO DAS QUESTÕES
    # ---------------------------
    df_temp["nivel_questao"] = df_temp["output.id_questao"].map(mapa_questoes)

    df_temp["nivel_questao"] = pd.Categorical(
        df_temp["nivel_questao"],
        categories=ordem_questoes,
        ordered=True
    )

    # ---------------------------
    # AGRUPAMENTO
    # ---------------------------
    resumo = (
        df_temp
        .groupby(["nivel_questao", "output.id_questao", "grupo"], observed=True)["score"]
        .agg(["count", "mean"])
        .rename(columns={"mean": "taxa_acerto"})
        .reset_index()
        .sort_values(["nivel_questao", "output.id_questao", "grupo"])
    )

    resultados[limiar] = resumo
    
for limiar, tabela in resultados.items():

    print(f"\n ===== PIVOT LIMIAR {limiar} =====")

    pivot = tabela.pivot(
        index="grupo",
        columns=["nivel_questao", "output.id_questao"],
        values="taxa_acerto"
    )

    print(pivot)

 ===== PIVOT LIMIAR 0.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.016949  0.020339  0.044068
media              0.578680  0.611675  0.517766
alta               1.000000  0.996785  0.996785

 ===== PIVOT LIMIAR 1 =====
nivel_questao        fácil     média   difícil
output.id_questao       35        38        9
grupo
baixa              0.00000  0.000000  0.000000
media              0.58815  0.606936  0.563584
alta               1.00000  1.000000  1.000000

 ===== PIVOT LIMIAR 1.5 =====
nivel_questao         fácil     média   difícil
output.id_questao        35        38        9
grupo
baixa              0.000000  0.000000  0.000000
media              0.554545  0.569318  0.535227
alta               1.000000  1.000000  1.000000